import type { PlannedExercise } from '../../shared/types';
import { stableRecordId } from '../../shared/automation-model';
import { useState } from 'react';
import { useAutomations, todayDerived } from '../state/AutomationContext';
import { useBiologicalData } from '../lib/use-biological-data';
import { useQuickLog } from './QuickLog';
import { pendingInbox } from '../../shared/automation-inbox';
import { dateOf, type BioRecord } from '../../shared/biology';
import { atTime } from '../../shared/biological-intelligence';
import { preparedWorkout } from '../../shared/automation-rules';
import { readiness } from '../../shared/biology';
import type { BioInput } from '../state/SupabaseBiologyContext';
import type { InboxItem, DerivedResult } from '../../shared/automation-model';

export function Why({result}:{result:DerivedResult}){return <details className="flow-details"><summary>Why?</summary><p>{result.evidence.explanation}</p><p className="subtle">{result.evidence.quality} confidence · {result.evidence.ids.length} source references · updated {new Date(result.updatedAt).toLocaleString()}</p><details><summary>Audit references</summary><p className="subtle">Event {result.eventId} · {result.automationKey} v{result.version}</p><p className="subtle">{result.evidence.ids.join(', ')||'System configuration'}</p></details></details>;}
export function AutomaticProgress({kind}:{kind?:'goal'|'habit'}){
  const {state}=useAutomations(),{bio}=useBiologicalData();
  const results=todayDerived(state,kind||'goal').concat(kind?[]:todayDerived(state,'habit'));
  if(!results.length)return null;
  return <section className="glass card stack" aria-label="Automatic progress"><h2>{kind==='habit'?'Habits from evidence':kind==='goal'?'Goals from your records':'Goals & habits from your records'}</h2>{results.map(r=>{const p=r.value as {name:string;recordId:string;value:number|null;target:number;percent:number|null;met:boolean};return <article className="automation-progress" key={r.id}><div><strong>{p.name}</strong><p>{p.met?'✓ Verified':p.value===null?'Waiting for evidence':`${Number(p.value.toFixed(1))} / ${p.target}`}</p>{p.percent!==null&&<progress max={100} value={p.percent}/>}</div><Why result={r}/>{r.kind==='habit'&&<button className="btn btn-soft btn-sm" onClick={()=>void bio.save({id:stableRecordId('habit-override',p.recordId,r.date),type:'habitDone',domain:'Today',name:p.name,timestamp:atTime(r.date),metadata:{parentId:p.recordId,userOverride:true,completed:!p.met}})}>{p.met?'Override as incomplete':'Override as complete'}</button>}</article>;})}</section>;
}
export function PreparedWorkoutCard({onClose}:{onClose?:()=>void}){
  const {app,records}=useBiologicalData(),{state,preferences}=useAutomations();
  const [customize,setCustomize]=useState(false),[customized,setCustomized]=useState<PlannedExercise[]>([]);
  if(!preferences.workoutPreparation)return null;
  const date=dateOf(new Date().toISOString()),estimate=readiness(records,date),prepared=(state.derived.preparedWorkout?.value||preparedWorkout({db:app.db!,skin:app.skin,records,userId:'local-user'},date,estimate.score)) as ReturnType<typeof preparedWorkout>;
  const start=(choice:'original'|'adapted'|'customized')=>{
    if(app.tracker){app.setPage('Tracker');onClose?.();return;}
    if(!prepared.weekId||!prepared.dayKey)return;
    const old=app.db!.readiness.find(r=>r.date===date);
    app.setTracker({weekId:prepared.weekId,weekName:prepared.weekName||'',weekNumber:prepared.weekNumber||1,dayKey:prepared.dayKey,dayTitle:prepared.dayTitle||'',date,name:app.db!.profile.displayName,sleep:old?.sleepHours??'',soreness:old?.soreness??'',readiness:old||null,index:0,logs:[],exercises:choice==='adapted'?prepared.adapted:choice==='customized'?customized:prepared.original,startedAt:new Date().toISOString(),gymMode:localStorage.getItem('workout-os-gym-mode')==='1',preparationChoice:choice} as Parameters<typeof app.setTracker>[0]);
    app.setPage('Tracker');onClose?.();
  };
  return <section className="glass card stack" aria-label="Prepared workout"><h2>Today's prepared workout</h2><p>{prepared.dayTitle||'Choose your training plan'}</p>{!customize&&prepared.original.slice(0,5).map((e,i)=><div className="flow-management-row" key={`${e.name}-${i}`}><strong>{e.name}</strong><span>{e.vol} · RIR {e.rirTarget}{e.suggestedWeight?` · suggested ${e.suggestedWeight} ${app.db!.profile.units}`:''}</span></div>)}<p className="subtle">{prepared.reason}</p>{prepared.adaptationRecommended&&<p>Optional: one fewer set and one additional RIR. Compare and choose before logging.</p>}<div className="row wrap"><button className="btn btn-hot" disabled={!prepared.original.length&&!app.tracker} onClick={()=>start('original')}>{app.tracker?'Resume workout':'Use Original'}</button>{prepared.adaptationRecommended&&<button className="btn btn-soft" onClick={()=>start('adapted')}>Use Adapted</button>}<button className="btn btn-soft" disabled={!prepared.original.length} onClick={()=>{setCustomized(prepared.original.map(e=>({...e})));setCustomize(true);}}>Customize</button></div>{customize&&<div className="stack"><p className="subtle">Edit your prescription. Confirm performed sets in the tracker.</p>{customized.map((e,i)=><div className="flow-field-grid" key={i}><label>Exercise<input className="input" value={e.name} onChange={event=>setCustomized(rows=>rows.map((row,index)=>index===i?{...row,name:event.target.value}:row))}/></label><label>Sets × reps<input className="input" value={e.vol} onChange={event=>setCustomized(rows=>rows.map((row,index)=>index===i?{...row,vol:event.target.value}:row))}/></label><label>Target RIR<input className="input" type="number" min={0} max={10} value={e.rirTarget??''} onChange={event=>setCustomized(rows=>rows.map((row,index)=>index===i?{...row,rirTarget:event.target.value}:row))}/></label></div>)}<button className="btn btn-hot" disabled={!customized.length||customized.some(e=>!e.name.trim()||!e.vol.trim())} onClick={()=>start('customized')}>Use customized prescription</button></div>}{state.derived.preparedWorkout&&<Why result={state.derived.preparedWorkout}/>}</section>;
}
export function AutomationCenter(){
  const automation=useAutomations(),{app,bio,stored}=useBiologicalData(),quick=useQuickLog();
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[undo,setUndo]=useState<{ids:string[];previous:BioRecord[];resolved:string[]}|null>(null),[selected,setSelected]=useState<string[]>([]);
  const date=dateOf(new Date().toISOString()),items=pendingInbox(automation.state).slice(0,automation.preferences.maxInbox);
  const care=(automation.state.derived.carePlan?.value||[]) as {id:string;label:string;time:string;status:string;notes:string}[];
  const batch=async(inputs:BioInput[],resolved:InboxItem[]=[])=>{
    if(busy||!inputs.length)return;setBusy(true);setError('');
    try{const ids=inputs.map(i=>i.id!);const previous=bio.records.filter(r=>ids.includes(r.id));await bio.saveMany(inputs);setUndo({ids,previous,resolved:resolved.map(i=>i.id)});for(const item of resolved)await automation.resolve(item.id,'accepted');setSelected([]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  };
  const doseInput=(item:InboxItem,status='Taken'):BioInput=>{const parent=stored.find(r=>r.id===item.suggestedPayload.parentId);if(!parent)throw new Error('This schedule changed.');return {id:stableRecordId('dose',parent.id,date,String(item.suggestedPayload.scheduledTime)),type:'dose',domain:'Health',name:parent.name,source:'Health OS explicit confirmation',metadata:{parentId:parent.id,doseType:parent.type,status,scheduledTime:String(item.suggestedPayload.scheduledTime),dose:parent.metadata.dose||parent.metadata.serving||'',unit:parent.metadata.unit||parent.unit}};};
  const accept=async(item:InboxItem)=>{
    try{
      if(item.type==='dose'){await batch([doseInput(item)],[item]);return;}
      if(item.type==='meal'){const meal=stored.find(r=>r.id===item.suggestedPayload.recordId);if(!meal)throw new Error('The source meal changed.');await batch([{id:stableRecordId('confirm',item.id),type:'meal',domain:'Eat',name:meal.name,source:meal.source,quality:meal.quality,metadata:{...meal.metadata,completeDay:false,repeatedFrom:meal.id,recurringId:String(item.suggestedPayload.recurringId||'')}}],[item]);return;}
      if(item.type==='import'){const record=stored.find(r=>r.id===item.suggestedPayload.recordId);if(record){await bio.save({...record,metadata:{...record.metadata,confirmed:true}});await automation.resolve(item.id,'accepted');}return;}
      if(item.type==='measurement'){if(item.suggestedPayload.metric==='Progress photos'){app.setPage('SkinProgress');return;}quick.open(item.suggestedPayload.metric==='Weight'?'vital':'bodyMeasurement',undefined,undefined,{name:String(item.suggestedPayload.metric),metric:String(item.suggestedPayload.metric),unit:item.suggestedPayload.metric==='Weight'?app.db!.profile.units:'cm'},()=>automation.resolve(item.id,'accepted'));return;}
    }catch(e){setError((e as Error).message);}
  };
  const modify=(item:InboxItem)=>{const record=stored.find(r=>r.id===item.suggestedPayload.recordId);if(record)quick.open(record.type==='meal'?'meal':record.type,item.type==='import'?record:{...record,id:'',timestamp:new Date().toISOString(),endTime:undefined},undefined,{...(item.type==='import'?{confirmed:true}:{}),recurringId:String(item.suggestedPayload.recurringId||'')},()=>automation.resolve(item.id,'modified'));};
  const completeCare=(ids:string[],status='done')=>batch(ids.map(id=>{const task=care.find(t=>t.id===id)!;return {id:stableRecordId('care-confirm',id,date),type:'automationEvent',domain:'Care',name:task.label,source:'Health OS explicit care confirmation',metadata:{subtype:'careAction',careTaskId:id,status}};}));
  const doses=items.filter(i=>i.type==='dose'),insights=automation.state.derived.insights?.value as {id:string;text:string;sample_size:number;confidence:string}[]|undefined;
  return <div className="stack automation-center">
    <section className="glass card stack" aria-label="Health OS Inbox"><div className="flow-section-title"><h2>Health OS Inbox</h2><span className="subtle">Confirm reality once</span></div>{!items.length&&<p className="subtle">No confirmations are due. Suggestions never become records until you confirm.</p>}
      {doses.length>1&&<button className="btn btn-soft" disabled={busy} onClick={()=>void batch(doses.map(i=>doseInput(i)),doses)}>Mark all due doses taken</button>}
      {items.map(item=><article className="automation-inbox-item" key={item.id}><div className="flow-section-title"><strong>{item.title}</strong>{['dose','import'].includes(item.type)&&<label className="row"><input type="checkbox" aria-label={`Select ${item.title}`} checked={selected.includes(item.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,item.id]:s.filter(id=>id!==item.id))}/>Select</label>}</div><p>{item.body}</p><details className="flow-details"><summary>Why this appeared</summary><p>{item.source.explanation}</p><p className="subtle">{item.source.ids.length} source references · {item.source.quality} confidence</p></details><div className="row wrap">{item.type==='anomaly'?<>{['Normal','Tired','Unwell'].map(feeling=><button className="btn btn-soft" key={feeling} onClick={()=>void bio.save({type:'journal',domain:'Recover',name:`Feeling ${feeling.toLowerCase()}`,metadata:{notes:feeling,contextPrompt:item.id}}).then(()=>automation.resolve(item.id,'accepted'))}>{feeling}</button>)}<button className="btn btn-soft" onClick={()=>quick.open('symptom',undefined,undefined,{},()=>automation.resolve(item.id,'modified'))}>Add symptoms</button></>:<><button className="btn btn-hot" disabled={busy} onClick={()=>void accept(item)}>{item.suggestedAction}</button>{['meal','import'].includes(item.type)&&<button className="btn btn-soft" onClick={()=>modify(item)}>Modify</button>}{item.type==='dose'&&<button className="btn btn-soft" disabled={busy} onClick={()=>void batch([doseInput(item,'Skipped')],[item])}>Skip dose</button>}</>}<button className="btn btn-soft" onClick={()=>void automation.resolve(item.id,'ignored')}>Ignore</button><button className="btn btn-soft" onClick={()=>void automation.resolve(item.id,'accepted',30)}>Snooze</button></div></article>)}
      {selected.some(id=>doses.some(i=>i.id===id))&&<button className="btn btn-hot" disabled={busy} onClick={()=>{const selectedDoses=doses.filter(i=>selected.includes(i.id));void batch(selectedDoses.map(i=>doseInput(i)),selectedDoses);}}>Mark selected taken</button>}
      {selected.some(id=>items.some(i=>i.id===id&&i.type==='import'))&&<button className="btn btn-hot" disabled={busy} onClick={()=>{const imported=items.filter(i=>i.type==='import'&&selected.includes(i.id));const inputs=imported.flatMap(i=>{const r=stored.find(r=>r.id===i.suggestedPayload.recordId);return r?[{...r,metadata:{...r.metadata,confirmed:true}}]:[];});void batch(inputs,imported);}}>Confirm selected imports</button>}
      {undo&&<button className="btn btn-soft" disabled={busy} onClick={()=>void bio.undoBatch(undo.ids,undo.previous).then(async()=>{for(const id of undo.resolved)await automation.resolve(id,'undo');setUndo(null);}).catch(e=>setError(e.message))}>Undo last confirmation batch</button>}{(error||automation.error)&&<p role="alert">{error||automation.error}</p>}
    </section>
    <PreparedWorkoutCard/>
    {automation.preferences.carePlan&&care.length>0&&<section className="glass card stack" aria-label="Today's care execution"><h2>Today's care</h2>{['morning','evening','anytime','wash'].map(time=>{const tasks=care.filter(t=>t.time===time),pending=tasks.filter(t=>t.status==='pending');return tasks.length?<div className="stack" key={time}><h3>{time==='wash'?'Wash day':time}</h3>{tasks.map(t=><div className="flow-management-row" key={t.id}><strong>{t.label}</strong><span>{t.status}</span>{t.status==='pending'&&<><button className="btn btn-soft" disabled={busy} onClick={()=>void completeCare([t.id])}>Done</button><button className="btn btn-soft" disabled={busy} onClick={()=>void completeCare([t.id],'skipped')}>Skip</button></>}</div>)}{pending.length>1&&<button className="btn btn-hot" disabled={busy} onClick={()=>void completeCare(pending.map(t=>t.id))}>Complete all {time} care</button>}</div>:null;})}{automation.state.derived.carePlan&&<Why result={automation.state.derived.carePlan}/>}</section>}
    <AutomaticProgress/>
    {insights&&insights.length>0&&<section className="glass card stack"><h2>One useful insight</h2><p>{insights[0].text}</p><p className="subtle">{insights[0].sample_size} observations · {insights[0].confidence} confidence</p><Why result={automation.state.derived.insights}/></section>}
  </div>;
}
