import { useEffect, useRef, useState } from 'react';
import { Modal } from './Modal';
import type { IScannerControls } from '@zxing/browser';
export function BarcodeScanner({open,onClose,onRead}:{open:boolean;onClose:()=>void;onRead:(code:string)=>void}){
  const video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null),generation=useRef(0),[error,setError]=useState(''),[started,setStarted]=useState(false),[busy,setBusy]=useState(false);
  const stop=()=>{generation.current++;controls.current?.stop();controls.current=null;const stream=video.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(t=>t.stop());setStarted(false);};
  useEffect(()=>()=>{generation.current++;controls.current?.stop();const stream=video.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(t=>t.stop());},[]);
  useEffect(()=>{if(!open)stop();},[open]);
  const start=async()=>{setBusy(true);setError('');setStarted(true);const current=++generation.current;try{const {BrowserMultiFormatOneDReader}=await import('@zxing/browser');if(current!==generation.current)return;const reader=new BrowserMultiFormatOneDReader();const scanner=await reader.decodeFromConstraints({video:{facingMode:'environment'},audio:false},video.current!, (result,_error,scanner)=>{if(result&&current===generation.current){const code=result.getText();scanner.stop();stop();onRead(code);onClose();}});if(current!==generation.current)scanner.stop();else controls.current=scanner;}catch{setError('Camera access is unavailable. You can scan a barcode photo or type the digits.');setStarted(false);}finally{setBusy(false);}};
  return <Modal open={open} title="Scan a barcode" onClose={()=>{stop();onClose();}} className="flow-modal"><p className="subtle">Point at the package barcode. Camera images stay in your browser; only the barcode digits are used for lookup.</p><div className="barcode-viewport"><video ref={video} muted playsInline/><div className="barcode-guide"/></div><div className="row wrap"><button className="btn btn-hot" disabled={busy} onClick={()=>started?stop():void start()}>{busy?'Opening camera…':started?'Stop camera':'Use camera'}</button><label className="btn btn-soft">Scan a photo<input type="file" accept="image/*" style={{display:'none'}} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;stop();setError('');const url=URL.createObjectURL(file);try{const {BrowserMultiFormatOneDReader}=await import('@zxing/browser');const result=await new BrowserMultiFormatOneDReader().decodeFromImageUrl(url);onRead(result.getText());onClose();}catch{setError('No readable barcode found. Try a clearer photo, or type the digits.');}finally{URL.revokeObjectURL(url);}}}/></label></div>{error&&<p role="alert">{error}</p>}</Modal>;
}
