import { useEffect, useState } from 'react';
import { invokeCloud } from '../lib/cloud-session';
import { useApp } from '../state/AppContext';
import { useToast } from './Toast';
import { LocalWorkerSettings } from './LocalWorkerSettings';

export function CloudConnections(){
  const app=useApp(),toast=useToast();
  const [status,setStatus]=useState<Record<string,any>|null>(null),[busy,setBusy]=useState(false),[files,setFiles]=useState<any[]>([]);
  const [form,setForm]=useState({googleClientId:'',googleClientSecret:'',telegramBotToken:'',telegramChatId:'',telegramMiniAppUrl:''});
  const refresh=async()=>setStatus(await invokeCloud('body-os-integrations',{action:'/integrations/status'}));
  useEffect(()=>{void refresh().catch(e=>toast.push(e.message,'err'));},[]);
  async function act(work:()=>Promise<unknown>,message:string){setBusy(true);try{await work();await refresh();await app.refresh();toast.push(message,'ok');}catch(e){toast.push((e as Error).message,'err');}finally{setBusy(false);}}
  const field=(key:keyof typeof form,label:string,password=false)=><label className="stack" key={key}>{label}<input className="input" value={form[key]} type={password?'password':'text'} autoComplete={password?'new-password':'off'} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
  return <><LocalWorkerSettings/><hr/><h3 style={{margin:0}}>Google Drive backups</h3><p className="subtle">Backups use a private app folder in your Drive. OAuth tokens and integration secrets stay encrypted in cloud storage.</p><span role="status">{status?.driveConnected?'Drive connected':status?.hasGoogleClient?'Client saved · authorization needed':'Drive is not connected'}</span>
    <details><summary>Configure Google OAuth</summary><div className="stack">{field('googleClientId','Google Web client ID')}{field('googleClientSecret','Google client secret',true)}<p className="subtle">Enable Google Drive API and add this exact authorized redirect URI to your Web application client:</p><code style={{overflowWrap:'anywhere'}}>{status?.redirectUri||'Loading cloud redirect URI…'}</code><button className="btn btn-soft" disabled={busy} onClick={()=>void act(async()=>{await invokeCloud('body-os-integrations',{action:'/integrations/config',googleClientId:form.googleClientId,googleClientSecret:form.googleClientSecret});setForm(f=>({...f,googleClientSecret:''}));},'Google client saved securely.')}>Save Google client</button></div></details>
    <div className="row" style={{flexWrap:'wrap'}}><button className="btn btn-soft" disabled={busy||!status?.hasGoogleClient} onClick={()=>void act(async()=>{const {url}=await app.api.getGdriveAuthUrl();window.location.assign(url);},'Opening Google authorization…')}>Connect Google Drive</button><button className="btn btn-soft" disabled={busy||!status?.driveConnected} onClick={()=>void act(()=>app.api.triggerGdriveBackup(),'Cloud backup uploaded to Drive.')}>Back up now</button><button className="btn btn-soft" disabled={busy||!status?.driveConnected} onClick={()=>void act(async()=>{const result=await app.api.listGdriveBackups() as any;setFiles(result.files||result.backups||[]);},'Backup list refreshed.')}>List backups</button><button className="btn btn-soft" disabled={busy||!status?.driveConnected} onClick={()=>void act(()=>app.api.disconnectGdrive(),'Drive access disconnected.')}>Disconnect</button></div>
    {files.map(file=><div className="page-list-item" key={file.id}><span style={{overflowWrap:'anywhere'}}>{file.name}</span><button className="btn btn-soft btn-sm" disabled={busy} onClick={()=>void act(async()=>{const result=await app.api.restoreGdriveBackup(file.id) as any;await app.refresh();if(result.conflicts)toast.push(`${result.conflicts} conflicting records were kept unchanged. Export and review them before replacing.`,'info');},'Missing records restored. Existing conflicting edits are preserved.')}>Restore missing records</button></div>)}
    <hr/><h3 style={{margin:0}}>Telegram</h3><p className="subtle">Create a bot with @BotFather, start it in Telegram, and enter your chat ID. Delivery occurs when you choose Send Telegram.</p><span role="status">{status?.hasTelegram?'Telegram configured':'Telegram is not configured'}</span>{field('telegramBotToken','Bot token · enter to replace',true)}{field('telegramChatId','Your chat ID')}{field('telegramMiniAppUrl','Public HTTPS Mini App URL (optional)')}<button className="btn btn-soft" disabled={busy} onClick={()=>void act(async()=>{await invokeCloud('body-os-integrations',{action:'/integrations/config',telegramBotToken:form.telegramBotToken,telegramChatId:form.telegramChatId,telegramMiniAppUrl:form.telegramMiniAppUrl});await app.api.saveSettings({telegramEnabled:true} as any);setForm(f=>({...f,telegramBotToken:''}));},'Telegram settings saved securely.')}>Save Telegram connection</button>
  </>;
}
