import { waterMillilitres } from '../../shared/biology';
import { TodayAnswer } from './TodayAnswer';
import { TodayLogGuide } from './TodayLogGuide';
import { useUx } from '../state/UxContext';
import { HomePersonalization } from './HomePersonalization';
import { AppointmentAgenda } from './AppointmentAgenda';
import { HealthOsImage } from './HealthOsImage';
import { MetricRing, MiniSparkline, WhyDetails } from './VisualMetrics';
import { workoutVisual } from '../lib/visual-assets';
import { useAddFood } from './AddFood';
import { useMemo, useState, type ReactNode } from 'react';
import { OSIcon, type OSIconName } from './OSIcon';
import { SignalChart } from './SignalChart';
import { lazy } from 'react';
import { DeferredDetails } from './DeferredDetails';
const AutomationCenter=lazy(()=>import('./AutomationCenter').then(module=>({default:module.AutomationCenter})));
const MedicalActionCenter=lazy(()=>import('./MedicalActionCenter').then(module=>({default:module.MedicalActionCenter})));
import { useQuickLog } from './QuickLog';
import { useBiologicalData } from '../lib/use-biological-data';
import { useTimelineActions } from '../lib/use-timeline-actions';
import { evaluateNudges } from '../../shared/biological-automations';
import { baseline, dateOf, num, nutrition, readiness } from '../../shared/biology';
import { buildTimeline, shiftDay, sleepStats, trainingLoad, weightTrend } from '../../shared/biological-intelligence';
import { careTasksForDate } from '../../shared/skin';
import type { Page } from '../lib/types';
import { DailyReadinessGuidance } from './DailyReadiness';

const fmt=(value:number|null|undefined,d=0)=>value==null?'—':value.toLocaleString(undefined,{maximumFractionDigits:d});
const duration=(hours:number|undefined)=>hours==null?'—':`${Math.floor(Math.round(hours*60)/60)}h ${Math.round(hours*60)%60}m`;
const time=(timestamp:string)=>new Date(timestamp).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});

export function ReadinessRing({score,label}:{score:number|null;label:string}){
  return <div className="health-readiness-ring"><MetricRing value={score} label="Readiness" size={160} tone={score===null?'var(--text-secondary)':score<50?'var(--warning)':'var(--recover)'}><small className={score===null?'health-unknown':score<50?'health-warning':''}>{label}</small></MetricRing></div>;
}

function DomainCard({domain,icon,title,value,detail,footer,action,children,photo=false}:{domain:string;icon:OSIconName;title:string;value:ReactNode;detail:string;footer?:string;action:()=>void;children?:ReactNode;photo?:boolean}){
  return <button className={`health-domain-card ${photo?'health-training-photo':''}`} data-domain={domain} onClick={action}><div className="health-domain-card-title"><span className="health-icon-tile"><OSIcon name={icon} size={23}/></span><h2>{title}</h2><OSIcon name="Forward" size={17}/></div><div className="health-domain-value">{value}</div><p>{detail}</p>{children}<div className="health-domain-footer"><span>{footer||'View details'}</span><span className="health-card-arrow"><OSIcon name="Forward" size={16}/></span></div></button>;
}


export function HealthDashboard(){
  const {app,stored,records,selectedDate,setSelectedDate}=useBiologicalData(),quick=useQuickLog(),addFood=useAddFood(),actions=useTimelineActions(),db=app.db!,today=selectedDate;
  const ux=useUx();
  const [insightRange,setInsightRange]=useState<'Today'|'7D'>('Today');
  const {ready,sleep,food,weight,load}=useMemo(()=>({ready:readiness(records,today),sleep:sleepStats(records,today),food:nutrition(records,today),weight:weightTrend(records,today),load:trainingLoad(db,today)}),[records,db,today]);
  const nudges=evaluateNudges(records,db,app.skin);
  const targets=stored.filter(r=>r.type==='nutritionTarget').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];
  const target=(key:string)=>targets?num(targets,key):null;
  const water=records.filter(r=>r.type==='water'&&dateOf(r.timestamp)===today).reduce((sum,r)=>sum+(waterMillilitres(r)??0),0);
  const {steps,rhr,hrv}=useMemo(()=>({steps:baseline(records,'Steps',today).current,rhr:baseline(records,'Resting HR',today).current,hrv:baseline(records,'HRV',today).current}),[records,today]);
  const events=useMemo(()=>buildTimeline(records,db,app.skin,today),[records,db,app.skin,today]),completed=events.filter(e=>e.status==='done'||e.status==='logged'),planned=events.filter(e=>e.status==='planned');
  const upcoming=[...planned].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  const next=nudges[0];
  const savedReadiness=db.readiness.find(item=>item.date===today);
  const checkedIn=Boolean(savedReadiness);
  const openCheckIn=()=>quick.open('checkIn',stored.find(r=>r.type==='checkIn'&&dateOf(r.timestamp)===today),today);
  const care=careTasksForDate(app.skin.care,today,app.skin.products),doneCareIds=new Set(app.skin.care.events.filter(e=>e.date===today&&e.status==='done').map(e=>e.taskId)),careDone=care.filter(task=>doneCareIds.has(task.id)).length;
  const supplements=stored.filter(r=>r.type==='supplement'&&r.metadata.active!==false),taken=new Set(records.filter(r=>r.type==='dose'&&dateOf(r.timestamp)===today&&r.metadata.status==='Taken').map(r=>String(r.metadata.parentId)));
  const sessions=db.sessions.filter(s=>s.date>=shiftDay(today,-6)&&s.date<=today&&['done','finished','completed'].includes(s.status));
  const chosenDay=db.weeks.find(w=>w.id===db.meta.activeWeekId)?.days.find(d=>d.key===app.activeDay);
  const trainTitle=app.tracker?.dayTitle||chosenDay?.title||'Your next workout';
  const choose=(page:Page,panel='')=>app.setPage(page,panel);
  const doNext=()=>{if(!next){if(checkedIn)choose('Timeline');else openCheckIn();return;}if(next.event)void actions.perform(next.event);else if(next.id.startsWith('checkin'))openCheckIn();else if(next.id.startsWith('water'))quick.open('water',undefined,today);else choose(next.page);};
  const workout=workoutVisual({name:trainTitle,category:chosenDay?.type,muscles:chosenDay?.muscles,exercises:app.tracker?.exercises||chosenDay?.exercises},db.exercises);
  const quickActions:{label:string;icon:OSIconName;action:()=>void}[]=app.tracker?[{label:'Continue workout',icon:'Train',action:()=>choose('Tracker')},{label:'Water',icon:'Water',action:()=>quick.open('water',undefined,today)},{label:'Pain',icon:'Recover',action:()=>quick.open('recoveryNote',undefined,today)}]:[...upcoming.slice(0,2).map(event=>({label:event.type==='careTask'?'Care':event.domain==='Eat'?'Meal':event.domain==='Train'?'Workout':event.title,icon:event.domain as OSIconName,action:()=>event.domain==='Eat'?addFood.open({date:today}):choose(event.page||'Timeline')})),...(!checkedIn?[{label:'Check-in',icon:'Recover' as OSIconName,action:()=>openCheckIn()}]:[]),{label:'Add food',icon:'Eat' as OSIconName,action:()=>addFood.open({date:today})},{label:'Workout',icon:'Train' as OSIconName,action:()=>choose('Dashboard')}].filter((item,i,all)=>all.findIndex(x=>x.label===item.label)===i).slice(0,3);
  const energy=ready.contributors.find(c=>c.label==='Energy')?.score;
  const contributors:[string,OSIconName,string,string][]=[['Sleep','Sleep',fmt(savedReadiness?.sleepHours??sleep.latest?.value,1),'Sleep duration'],['HRV','Health',fmt(hrv?.value),'ms'],['Recovery','Recover',fmt(ready.score),ready.category],['Energy','Energy',fmt(energy===undefined?undefined:energy/10),'Check-in score']];
  const recent=[...events].filter(e=>e.status==='done'||e.status==='logged').sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,4);
  const weekStart=shiftDay(today,-((new Date(`${today}T12:00:00`).getDay()+6)%7));
  const insightRows=insightRange==='Today'?nudges.map(n=>({title:n.title,body:n.reason,page:n.page})):([
    {title:'Your sleep this week',body:sleep.observedDays?`${fmt(sleep.average,1)} hours on average across ${sleep.observedDays} recorded nights.`:'Log your sleep to build a weekly picture.',page:'Recover' as Page},
    {title:'Training, in perspective',body:`${sessions.length} completed workouts over the past 7 days.${load.change===null?'':` Training volume changed ${fmt(load.change)}% from your earlier average.`}`,page:'Analyzer' as Page},
    {title:'Follow your own direction',body:weight.change30===null?'More weigh-ins will help reveal your personal trend.':`${fmt(weight.change30,1)} kg change in your 7-day average compared with 30 days ago.`,page:'Body' as Page}
  ]);
  return <div className="health-dashboard">
    <header className="health-greeting domain-hero"><div><p className="health-overline">YOUR DAILY OVERVIEW</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, {db.profile.displayName||app.settings?.profileName||'Athlete'} <OSIcon name="Sun" size={30}/></h1><p>One connected picture of your health. Make today a little better.</p></div><label className="health-date-pill"><OSIcon name="Calendar" size={17}/><input type="date" aria-label="Overview date" value={today} onChange={e=>{if(e.target.value)setSelectedDate(e.target.value);}}/></label><HomePersonalization iconOnly/></header>
    <nav className="visual-quick-actions" aria-label="Contextual quick actions"><span>FOR YOUR DAY</span>{quickActions.map(item=><button key={item.label} onClick={item.action}><OSIcon name={item.icon} size={18}/>{item.label}</button>)}</nav>
    <div className="web-today-guidance"><TodayAnswer compact/><TodayLogGuide/></div><div className="health-dashboard-layout"><div className="health-dashboard-center">
      {!ux.preferences.setupCompleted && !stored.length && !db.sessions.length && <section className="ux-setup"><h2>A small start is enough</h2><ol><li>Check your profile and preferred units.</li><li>Choose the summaries that matter to you.</li><li>Log your first health moment.</li></ol><div className="row wrap"><button className="btn btn-soft" onClick={()=>choose('Profile')}>Review profile</button><button className="btn btn-hot" onClick={()=>quick.open('journal',undefined,today)}>Log first entry</button><button className="btn btn-soft" onClick={()=>void ux.save({...ux.preferences,setupCompleted:true}).catch(error=>actions.run('setup',async()=>{throw error;}))}>Finish setup later</button></div></section>}
      <AppointmentAgenda date={today} compact/>
      <section className="ux-home-summaries" aria-label="Your selected summaries">{ux.preferences.homeSummaries.map(name=>{
        const values:Record<string,{value:string;detail:string;page:Page;panel?:string}>={Train:{value:`${sessions.length} workouts`,detail:'Completed in the last seven days',page:'Dashboard'},Eat:{value:`${food.calories} kcal`,detail:`${food.protein} g protein recorded today`,page:'Eat'},Recover:{value:ready.score===null?'No score yet':String(ready.score),detail:ready.category,page:'Recover'},Sleep:{value:duration(sleep.latest?.value),detail:'Latest recorded sleep',page:'Recover',panel:'Sleep'},Health:{value:rhr?`${fmt(rhr.value)} bpm`:'Your health records',detail:rhr?'Latest resting heart rate':'Vitals, symptoms, appointments and records',page:'Health'},Body:{value:weight.trend==null?'No trend yet':`${fmt(weight.trend,1)} kg`,detail:'Recorded seven-day weight average',page:'Body'},Care:{value:`${careDone} / ${care.length}`,detail:'Care actions completed today',page:'SkinOverview'},Supplements:{value:`${supplements.filter(r=>taken.has(r.id)).length} taken`,detail:'Your recorded supplement schedule',page:'Health',panel:'Supplements'}};
        const item=values[name];return <button className="ux-home-summary" key={name} onClick={()=>choose(item.page,item.panel)}><span>{name}</span><strong>{item.value}</strong><small>{item.detail}</small></button>;
      })}</section>
      <DeferredDetails className="health-panel web-day-evidence" summary="Readiness evidence & other actions"><div className="health-priority-row">
        <section className="health-next-action health-panel"><div className="health-panel-heading"><h2><OSIcon name="Energy" size={18}/>Next action</h2><span><OSIcon name="Clock" size={14}/>{next?.event?time(next.event.timestamp):'For today'}</span></div><div className="health-next-body"><span className="health-next-icon"><OSIcon name={next?.event&&['supplement','medication'].includes(next.event.type)?'Supplements':next?.domain||'Recover'} size={30}/></span><div><h3>{next?.title||(checkedIn?'You’re all caught up':'Start with a quick check-in')}</h3><p>{next?.reason||(checkedIn?'Your current actions are covered. Take a look at the rest of your day.':'A few seconds to record your energy, stress, and recovery.')}</p></div></div><div className="health-next-buttons"><button className="btn health-next-primary" disabled={Boolean(actions.busy)} onClick={doNext}><OSIcon name="Done" size={17}/>{next?.event&&['supplement','medication'].includes(next.event.type)?'Mark as taken':next?.event?.type==='careTask'?'Mark as done':!next&&checkedIn?'View your day':'Let’s do it'}</button>{next&&<button className="btn btn-soft" disabled={Boolean(actions.busy)} onClick={()=>void actions.dismiss(next.id,30)}><OSIcon name="Clock" size={16}/>Snooze</button>}</div>{actions.error&&<p role="alert" className="health-warning">{actions.error}</p>}</section>
        <section className="health-ready health-panel"><div className="health-panel-heading"><h2><OSIcon name="Recover" size={18}/>{today===dateOf(new Date().toISOString())?'Today’s readiness':`Readiness · ${new Date(`${today}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short'})}`}</h2><button onClick={()=>openCheckIn()}>{savedReadiness?'Edit check-in':'Check in'} <OSIcon name="Arrow" size={15}/></button></div><div className="health-ready-content"><ReadinessRing score={ready.score} label={ready.category}/><div className="health-contributors">{contributors.map(([label,icon,value,note])=><button key={label} data-domain={label==='HRV'?'Health':label} onClick={()=>label==='Sleep'?choose('Recover','Sleep'):label==='HRV'?choose('Health','Heart'):openCheckIn()}><span className="health-icon-tile"><OSIcon name={icon} size={18}/></span><span><small>{label}</small><strong>{value}<em>{label==='HRV'?' ms':label==='Sleep'?' h':label==='Energy'?' /10':''}</em></strong></span><small className="health-contributor-note">{value==='—'?'Add data':note}</small></button>)}</div></div><p className="health-readiness-caption">{savedReadiness?`Saved for ${today} · ${ready.confidence.toLowerCase()} confidence`:ready.score===null?'Complete your daily check-in here to prepare for training.':'Available signals · complete your check-in to prepare for training.'}</p><WhyDetails>{ready.contributors.map(c=><p key={c.label}><strong>{c.label}</strong> · {c.detail}</p>)}<p>{ready.missing.length?`Missing: ${ready.missing.join(', ')}`:'All inputs available'} · Planning estimate</p></WhyDetails>{savedReadiness&&<DailyReadinessGuidance ready={savedReadiness}/>}<button className="flow-text-button" onClick={()=>choose('Recover')}>View recovery details ↗</button></section>
      </div>
      </DeferredDetails><section className="visual-workout-card" data-domain="Train"><HealthOsImage context={workout} alt={trainTitle} variant="hero"/><div className="visual-workout-copy"><span className="bio-eyebrow">{app.tracker?'IN PROGRESS':'TODAY’S WORKOUT'}</span><h2>{trainTitle}</h2><p>{(app.tracker?.exercises||chosenDay?.exercises||[]).length} exercises · {sessions.length} completed this week</p><div className="row"><button className="btn btn-hot" onClick={()=>choose(app.tracker?'Tracker':'Dashboard')}>{app.tracker?'Continue workout':'Start workout'} <OSIcon name="Arrow" size={16}/></button><button className="btn btn-soft" onClick={()=>choose('Planner')}>View plan</button></div></div></section>
      <DeferredDetails className="stitch-domain-summary" summary={<><span><OSIcon name="Activity" size={18}/>Your health at a glance</span><span>8 connected areas <OSIcon name="Forward" size={16}/></span></>}><section className="health-domain-grid" aria-label="Your health domains">
        <DomainCard domain="Train" icon="Train" title="Train" value={app.tracker?'Workout in progress':`${sessions.length} this week`} detail={trainTitle} footer={app.tracker?'Continue workout':'Open training'} action={()=>choose(app.tracker?'Tracker':'Dashboard')} photo><div className="health-mini-bar"><i style={{width:app.tracker?`${app.tracker.index/Math.max(1,app.tracker.exercises.length)*100}%`:'0%'}}/></div></DomainCard>
        <DomainCard domain="Eat" icon="Eat" title="Eat" value={<>{fmt(target('calories')?Math.max(0,target('calories')!-food.calories):food.calories)}<small>{target('calories')?' kcal left':' kcal logged'}</small></>} detail={`${fmt(food.protein)} g protein logged`} footer={target('calories')?'Daily nutrition':'Set your targets'} action={()=>choose('Eat')}><div className="health-mini-bar"><i style={{width:`${Math.min(100,(target('calories')?food.calories/target('calories')!*100:0))}%`}}/></div></DomainCard>
        <DomainCard domain="Recover" icon="Recover" title="Recover" value={ready.score??'—'} detail={ready.score===null?'Your recovery, at a glance':`${ready.category} · readiness score`} footer={ready.score===null?'Check in today':'View recovery'} action={()=>choose('Recover')}><div className="health-mini-bar"><i style={{width:`${ready.score??0}%`}}/></div></DomainCard>
        <DomainCard domain="Sleep" icon="Sleep" title="Sleep" value={duration(sleep.latest?.value)} detail={sleep.latest?'Sleep logged for this day':'No sleep logged yet'} footer={sleep.latest?`${fmt(sleep.average,1)} h weekly average`:'Log last night'} action={()=>choose('Recover','Sleep')}><div className="health-sleep-bars" aria-label="Recorded sleep over the last seven days">{Array.from({length:7},(_,i)=>{const date=shiftDay(today,i-6),r=sleep.history.find(r=>dateOf(r.timestamp)===date);return <i key={date} title={r?`${date}: ${r.value} hours`:`${date}: no data`} style={{height:r?`${Math.max(8,Math.min(100,r.value!/10*100))}%`:'3px',opacity:r?1:.25}}/>;})}</div></DomainCard>
        <DomainCard domain="Health" icon="Health" title="Health" value={rhr?<>{fmt(rhr.value)}<small> bpm</small></>:'Your vital signs'} detail={rhr?'Latest resting heart rate':'Bring your readings together'} footer={rhr?'View your vitals':'Add your first reading'} action={()=>choose('Health')}><div className="health-card-signal"><OSIcon name="Activity" size={48}/></div></DomainCard>
        <DomainCard domain="Body" icon="Body" title="Body" value={<>{fmt(weight.trend,1)}<small> kg</small></>} detail={weight.change30===null?'Your 7-day weight trend':`${weight.change30>0?'+':''}${fmt(weight.change30,1)} kg over 30 days`} footer="View your progress" action={()=>choose('Body')}><MiniSparkline label="Recorded weight" unit="kg" tone="var(--body)" points={weight.points.slice(-14).map(p=>({date:p.date,value:p.weight}))}/></DomainCard>
        <DomainCard domain="Care" icon="Care" title="Care" value={care.length?`${careDone} / ${care.length} done`:'Your daily care'} detail={care.length?'Small rituals. Consistent care.':'Build a routine that fits you'} footer={care.length?'Continue your routine':'Set up your routine'} action={()=>choose('SkinOverview')}><div className="health-care-dots">{care.slice(0,5).map(task=><span className={doneCareIds.has(task.id)?'complete':''} key={task.id}>{doneCareIds.has(task.id)?<OSIcon name="Done" size={12}/>:<span/>}</span>)}</div></DomainCard>
        <DomainCard domain="Supplements" icon="Supplements" title="Supplements" value={supplements.length?`${supplements.filter(r=>taken.has(r.id)).length} / ${supplements.length} taken`:'Your schedule'} detail={supplements.length?'Stay in step with your plan':'Keep your daily doses organized'} footer="View supplements" action={()=>choose('Health','Supplements')}><div className="health-mini-bar"><i style={{width:supplements.length?`${supplements.filter(r=>taken.has(r.id)).length/supplements.length*100}%`:'0%'}}/></div></DomainCard>
      </section>
      </DeferredDetails>
      <section className="health-panel health-insights"><div className="health-panel-heading"><h2><OSIcon name="AI" size={21}/>Insights for you</h2><div className="health-segment">{(['Today','7D'] as const).map(range=><button key={range} aria-pressed={insightRange===range} onClick={()=>setInsightRange(range)}>{range}</button>)}</div></div><div className="health-insight-grid">{(insightRows.filter(insight=>insight.title!==next?.title).length?insightRows.filter(insight=>insight.title!==next?.title):[{title:'A clearer picture starts here',body:'Log a meal, your sleep, or a quick check-in. Your records will reveal your personal patterns.',page:'Insights' as Page}]).slice(0,3).map((insight,i)=><article key={insight.title}><span className="health-insight-icon"><OSIcon name={i===0?'AI':i===1?'Train':'Body'} size={21}/></span><h3>{insight.title}</h3>{/sleep/i.test(insight.title)&&<MiniSparkline table label="Recorded sleep" unit="h" tone="var(--sleep)" points={sleep.history.slice(-7).map(r=>({date:dateOf(r.timestamp),value:r.value}))}/>}{/training/i.test(insight.title)&&<MiniSparkline table label="Recorded training volume" unit={db.profile.units} tone="var(--train)" points={load.history.slice(-7).map(r=>({date:r.date,value:r.load}))}/>}{/direction|weight/i.test(insight.title)&&<MiniSparkline table label="Recorded weight" unit="kg" tone="var(--body)" points={weight.points.slice(-7).map(r=>({date:r.date,value:r.weight}))}/>}<p>{insight.body.split(/(?<=[.!?])\s/)[0]}</p><WhyDetails label="Evidence">{insight.body}</WhyDetails><button onClick={()=>choose(insight.page)}>View details <OSIcon name="Arrow" size={14}/></button></article>)}</div></section>
      <div className="health-bottom-grid"><section className="health-panel health-timeline"><div className="health-panel-heading"><h2><OSIcon name="Clock" size={18}/>Today’s timeline</h2><button onClick={()=>choose('Timeline')}>Full day <OSIcon name="Arrow" size={14}/></button></div>{events.length?<div className="health-timeline-list">{events.slice(0,5).map(event=><button key={event.id} data-domain={event.domain} onClick={()=>choose('Timeline')}><time>{time(event.timestamp)}</time><span className="health-timeline-node"><OSIcon name={event.domain} size={16}/></span><span><strong>{event.title}</strong><small>{event.summary}</small></span><span className={`health-status ${event.status==='planned'?'pending':''}`}>{event.status==='planned'?'Upcoming':event.status==='skipped'?'Skipped':<OSIcon name="Done" size={13}/>}</span></button>)}</div>:<div className="health-empty"><OSIcon name="Clock" size={25}/><h3>Your day starts here</h3><p>Your logs and planned routines appear in one timeline.</p><button className="btn btn-soft" onClick={()=>quick.open('journal',undefined,today)}>Log a moment <OSIcon name="Plus" size={15}/></button></div>}</section><section className="health-panel health-metrics" data-domain="Body"><div className="health-panel-heading"><h2><OSIcon name="Insights" size={18}/>Your weight trend</h2><button onClick={()=>choose('Body')}>View <OSIcon name="Arrow" size={14}/></button></div><strong className="health-metric-number">{fmt(weight.trend,1)}<small> kg</small></strong><p>7-day average · {weight.points.length} weigh-ins</p><SignalChart points={weight.points.slice(-14).map(p=>({date:p.date,value:p.weight}))} label="Recorded weight" unit="kg" height={125}/></section></div>
      <section className="health-panel health-quick-capture"><div><OSIcon name="Energy" size={25}/><span><h2>Quick capture</h2><p>A small log. A fuller picture.</p></span></div><div className="health-capture-options">{([{label:'Log meal',icon:'Eat',domain:'Eat',action:()=>addFood.open({date:today})},{label:'Scan barcode',icon:'Barcode',domain:'Today',action:()=>addFood.open({date:today,mode:'Barcode'})},{label:'Describe meal',icon:'Describe',domain:'Insights',action:()=>addFood.open({date:today,mode:'Describe'})},{label:'Add water',icon:'Water',domain:'Recover',action:()=>quick.open('water',undefined,today)},{label:'Photo log',icon:'Camera',domain:'Care',action:()=>addFood.open({date:today,mode:'Photo'})},{label:'Quick note',icon:'Plus',domain:'Today',action:()=>quick.open('journal',undefined,today)}] satisfies {label:string;icon:OSIconName;domain:string;action:()=>void}[]).map(item=><button key={item.label} data-domain={item.domain} onClick={item.action}><OSIcon name={item.icon} size={21}/><span>{item.label}</span></button>)}</div></section>
      <DeferredDetails className="health-panel health-detail-section" summary={<><span><OSIcon name="Routine" size={19}/>Confirmations, routines & prepared workout</span><OSIcon name="Forward" size={17}/></>}><AutomationCenter/></DeferredDetails>
      <DeferredDetails className="health-panel health-detail-section" summary={<><span><OSIcon name="Health" size={19}/>Health action center</span><OSIcon name="Forward" size={17}/></>}><MedicalActionCenter view="today"/></DeferredDetails>
    </div><aside className="health-dashboard-aside" aria-label="Daily activity">
      <section className="health-panel health-day-progress"><div className="health-panel-heading"><h2>Today’s progress</h2><strong>{events.length?<>{completed.length}<small> / {events.length}</small></>:'—'}</strong></div><div className="health-progress-track"><i style={{width:`${events.length?completed.length/events.length*100:0}%`}}/></div><p className="health-progress-caption">{events.length?`${completed.length} moments logged. Keep your day moving.`:'Your logged moments and planned actions appear here.'}</p><div className="health-progress-items">{[...completed.slice(-2),...upcoming.slice(0,3)].map(event=><button onClick={()=>choose('Timeline')} key={event.id}><span className={event.status==='planned'?'':'done'}>{event.status!=='planned'&&<OSIcon name="Done" size={12}/>}</span><strong>{event.title}</strong><small>{event.status==='planned'?'Upcoming':time(event.timestamp)}</small></button>)}</div><button className="health-panel-link" onClick={()=>choose('Targets')}>Your goals & habits <OSIcon name="Arrow" size={14}/></button></section>
      <section className="health-panel health-calendar"><div className="health-panel-heading"><h2>This week</h2><button onClick={()=>choose('Calendar')}>Calendar <OSIcon name="Arrow" size={14}/></button></div><div className="health-calendar-days">{Array.from({length:7},(_,i)=>{const date=shiftDay(weekStart,i),d=new Date(`${date}T12:00:00`);return <button key={date} className={date===today?'active':''} onClick={()=>setSelectedDate(date)} aria-label={`Show readiness and activity for ${d.toLocaleDateString()}`}><span>{d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}</span><strong>{d.getDate()}</strong><i/></button>;})}</div><div className="health-week-stats">{[{label:'Workouts',icon:'Train' as const,value:`${sessions.length} completed`,domain:'Train',page:'Dashboard' as Page},{label:'Sleep',icon:'Sleep' as const,value:`${sleep.observedDays} nights logged`,domain:'Sleep',page:'Recover' as Page},{label:'Hydration',icon:'Water' as const,value:`${fmt(water/1000,2)} L today`,domain:'Recover',page:'Eat' as Page}].map(item=><button key={item.label} data-domain={item.domain} onClick={()=>choose(item.page)}><OSIcon name={item.icon} size={18}/><span>{item.label}</span><strong>{item.value}</strong></button>)}</div></section>
      <section className="health-panel health-recent"><div className="health-panel-heading"><h2>Recent activity</h2><button onClick={()=>choose('Timeline')}>View all <OSIcon name="Arrow" size={14}/></button></div>{recent.length?recent.map(event=><button className="health-recent-entry" data-domain={event.domain} key={event.id} onClick={()=>choose(event.page)}><span className="health-icon-tile"><OSIcon name={event.type==='sleep'?'Sleep':event.domain} size={21}/></span><span><strong>{event.title}</strong><small>{event.summary}</small></span><time>{time(event.timestamp)}</time></button>):<div className="health-empty"><OSIcon name="Activity" size={26}/><p>Every small action counts.<br/>Your recent logs will appear here.</p><button className="health-panel-link" onClick={()=>quick.open('meal',undefined,today)}>Log your first meal <OSIcon name="Plus" size={15}/></button></div>}</section>
      <section className="health-panel health-health-note"><OSIcon name="Care" size={23}/><h3>Made for your own pace</h3><p>Your health data stays connected. Start with what matters to you today.</p><button onClick={()=>choose('Sync')}>Manage your sources <OSIcon name="Arrow" size={14}/></button></section>
    </aside></div>
  </div>;
}
