import { useCloudAccount } from '../state/CloudAccountContext';
import { TextAreaField } from './TextAreaField';
import { useDraftFields } from '../lib/use-draft';
import { DraftFeedback } from './DraftFeedback';
import { useEffect, useMemo, useState } from 'react';
import { get, post, put, del } from '../lib/api';
import { useBiologicalData } from '../lib/use-biological-data';
import { downloadArtifact } from '../lib/health-os-export';
import { dateOf } from '../../shared/biology';
import { labSchema, labTrends, rangeFlag, LAB_TESTS, identifyTest, type MedicalReport, type LabResult } from '../../shared/medical';
import { calculateMedical, evidenceCards, medicationReview, physiologicalSignals } from '../../shared/medical-intelligence';
import { SignalChart } from './SignalChart';
import { useQuickLog } from './QuickLog';
import { doctorSummaryHtml, type DoctorSummary } from '../lib/medical-summary';
import { MedicalActionCenter } from './MedicalActionCenter';
import { ResearchWorkbench } from './ResearchWorkbench';
import { DocumentPreview } from './DocumentPreview';

const format=(v:number|null|undefined)=>v==null?'—':v.toLocaleString(undefined,{maximumFractionDigits:2});
async function readBase64(file:File){const data=await file.arrayBuffer();let binary='';for(const byte of new Uint8Array(data))binary+=String.fromCharCode(byte);return btoa(binary);}
const calcDefaults:Record<string,Record<string,string>>={BMI:{age:'',weightKg:'',heightCm:''},'waist-height':{age:'',waistCm:'',heightCm:''},eGFR:{age:'',sex:'female',creatinine:'',unit:'mg/dL'},'FIB-4':{age:'',ast:'',alt:'',platelets:''}};
const labels:Record<string,string>={age:'Age (years)',weightKg:'Weight (kg)',heightCm:'Height (cm)',waistCm:'Waist (cm)',sex:'Equation sex parameter',creatinine:'Serum creatinine',unit:'Creatinine unit',ast:'AST (U/L)',alt:'ALT (U/L)',platelets:'Platelets (10^9/L)'};
export function MedicalIntelligence(){
  const cloud=useCloudAccount();
  const {records,bio}=useBiologicalData(),quick=useQuickLog(),date=dateOf(new Date().toISOString());
  const [reports,setReports]=useState<MedicalReport[]>([]),[selected,setSelected]=useState<MedicalReport|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false);
  const importDraft=useDraftFields('medical-import',{text:'',collected:date,laboratory:''});
  const [text,setText]=importDraft.field('text'),[file,setFile]=useState<File|null>(null),[collected,setCollected]=importDraft.field('collected'),[laboratory,setLaboratory]=importDraft.field('laboratory'),[confirm,setConfirm]=useState(false),[deleteId,setDeleteId]=useState('');
  const [summarySections,setSummarySections]=useState({followups:true,questions:true,inbox:true,signals:true});
  const [tab,setTab]=useState('Reports'),[calc,setCalc]=useState('BMI'),[values,setValues]=useState(calcDefaults.BMI),[calculation,setCalculation]=useState<ReturnType<typeof calculateMedical>|null>(null);
  const [consent,setConsent]=useState(false),[purpose,setPurpose]=useState(''),[capabilities,setCapabilities]=useState<Record<string,string>|null>(null);
  const [participantId,setParticipantId]=useState(()=>localStorage.getItem('body-os-medical-participant')||crypto.randomUUID());
  const [aiConsent,setAiConsent]=useState(false),[explanation,setExplanation]=useState(''),[researchStatus,setResearchStatus]=useState<unknown>(null),[ruleRegistry,setRuleRegistry]=useState<unknown>(null);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const reload=async()=>{const result=await get<{reports:MedicalReport[]}>('/api/medical/reports');setReports(result.reports);setConnected(true);window.dispatchEvent(new Event('health-os-medical-changed'));const pending=sessionStorage.getItem('health-os-open-report');if(pending){setSelected(result.reports.find(r=>r.id===pending)||null);sessionStorage.removeItem('health-os-open-report');}};
  useEffect(()=>{void reload().catch(()=>{setConnected(false);});},[]);
  useEffect(()=>{
    const refresh=()=>void get<{reports:MedicalReport[]}>('/api/medical/reports').then(result=>{setReports(result.reports);setConnected(true);}).catch(()=>setConnected(false));
    window.addEventListener('health-os-medical-cloud-applied',refresh);
    return ()=>window.removeEventListener('health-os-medical-cloud-applied',refresh);
  },[]);
  useEffect(()=>{setAiConsent(false);setExplanation('');},[selected?.id]);
  useEffect(()=>{const open=(e:Event)=>{const id=(e as CustomEvent<string>).detail;const report=reports.find(r=>r.id===id);if(report){setSelected(structuredClone(report));setTab('Reports');setConfirm(false);sessionStorage.removeItem('health-os-open-report');}};window.addEventListener('health-os-open-report',open);return()=>window.removeEventListener('health-os-open-report',open);},[reports]);
  const trends=useMemo(()=>labTrends(reports),[reports]),signals=useMemo(()=>physiologicalSignals(records,date),[records,date]),cards=useMemo(()=>evidenceCards(reports,records,date),[reports,records,date]),medications=useMemo(()=>medicationReview(records),[records]);
  const updateResult=(id:string,key:keyof LabResult,value:string)=>setSelected(r=>r?{...r,results:r.results.map(row=>row.id===id?{...row,[key]:['value','referenceLow','referenceHigh'].includes(key)?value===''?undefined:Number(value):key==='loinc'&&value===''?undefined:value}:row)}:r);
  const downloadOriginal=async(id:string)=>{const original=await get<{name:string;mime:string;base64:string}>(`/api/medical/reports/${id}/original`);const bytes=Uint8Array.from(atob(original.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:original.mime}));const a=document.createElement('a');a.href=url;a.download=original.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="glass card stack" aria-label="Medical intelligence"><header><p className="bio-eyebrow">MEDICAL INTELLIGENCE</p><h2>Understand your reports and what changed.</h2><p className="subtle">{cloud.user?'Reports belong to your signed-in account; originals use private Supabase Storage.':'Medical reports are stored on this desktop with machine-key encryption.'} Only reviewed reports inform trends.</p></header>
    <div className="row wrap">{['Reports','Action center','Changes','Signals','Calculators','Medication','Doctor summary','Research','Technology'].map(t=><button className={`btn ${tab===t?'btn-hot':'btn-soft'}`} key={t} onClick={()=>setTab(t)} aria-pressed={tab===t}>{t}</button>)}</div>
    {tab==='Action center'&&<MedicalActionCenter/>}
    {error&&<p role="alert">{error}</p>}
    {cards.filter(c=>c.urgency==='urgent').map(c=><article className="card" role="alert" key={c.id}><h3>{c.summary}</h3><p>{c.detail}</p><a href={c.source} target="_blank" rel="noreferrer">Source guidance</a></article>)}
    {tab==='Reports'&&<>
      {!connected&&<p className="subtle">Report import requires the local Health OS server. <button className="btn btn-soft" disabled={busy} onClick={()=>void run(reload)}>Connect</button></p>}
      <form className="stack" onSubmit={e=>{e.preventDefault();void run(async()=>{const mime=file?(file.name.endsWith('.dcm')?'application/dicom':file.name.endsWith('.json')?'application/fhir+json':file.type||'text/plain'):'text/plain';const source=file||new File([text],'medical-report.txt',{type:'text/plain'});if(source.size>6_000_000)throw new Error('Choose a report smaller than 6 MB.');const result=await post<{report:MedicalReport;duplicate:boolean}>('/api/medical/import',{name:source.name,mime,base64:await readBase64(source),collectedAt:new Date(`${collected}T12:00:00`).toISOString(),laboratory});await importDraft.clear();setSelected(result.report);setConfirm(false);await reload();if(result.duplicate)setError('This original is already in your library. Open the existing report to review it.');});}}>
        <div className="bio-form-grid"><label>Collection date<input className="input" type="date" required value={collected} onChange={e=>setCollected(e.target.value)}/></label><DraftFeedback draft={importDraft}/><label>Laboratory<input className="input" value={laboratory} maxLength={250} onChange={e=>setLaboratory(e.target.value)}/></label></div>
        <label>PDF, report photo, text, FHIR Bundle or DICOM<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.json,.dcm" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
        {!file&&<TextAreaField label="Or paste report text" className="input" rows={5} placeholder={'Hemoglobin 11.8 g/dL 13.0-17.0\nFerritin 11 ng/mL 20-250'} value={text} onChange={e=>setText(e.target.value)} maxLength={200000}/>}
        {file&&<button type="button" className="btn btn-soft" onClick={()=>setFile(null)}>Use pasted text</button>}
        <p className="subtle">Originals are preserved in private Supabase Storage. Photo OCR runs on your personal worker and may download the English language model on first use. Scanned PDFs need page images. Verify the collection date from the report.</p>
        <button className="btn btn-hot" disabled={busy||!connected||(!file&&!text.trim())}>{busy?'Processing…':'Import for review'}</button>
      </form>
      {reports.map(r=><article className="bio-record medical-document-card" key={r.id}><DocumentPreview report={r}/><div><strong>{r.title}</strong><p>{r.collectedAt.slice(0,10)} · {r.laboratory||'Source unspecified'} · {r.category} · {r.results.length} results · {r.status}</p></div><div className="row wrap"><button className="btn btn-soft" disabled={busy} onClick={()=>{setSelected(structuredClone(r));setConfirm(false);}}>Review</button><button className="btn btn-soft" disabled={busy} onClick={()=>void run(()=>downloadOriginal(r.id))}>Original</button>{r.status==='draft'&&<button className="btn btn-soft" disabled={busy} onClick={()=>void run(async()=>{await post(`/api/medical/reports/${r.id}/extract`,{});await reload();})}>Extract on my worker</button>}{r.status==='reviewed'&&<button className="btn btn-soft" disabled={busy} onClick={()=>void run(async()=>downloadArtifact(`${r.id}.fhir.json`,JSON.stringify(await get(`/api/medical/reports/${r.id}/fhir`),null,2)))}>FHIR</button>}<button className="btn btn-soft" disabled={busy} onClick={()=>setDeleteId(r.id)}>Delete</button></div></article>)}
      {deleteId&&<div role="alert"><p>Remove this report from Health OS? Its private original remains in Supabase Storage for recovery.</p><button className="btn btn-hot" disabled={busy} onClick={()=>void run(async()=>{await del(`/api/medical/reports/${deleteId}`);if(selected?.id===deleteId)setSelected(null);setDeleteId('');await reload();})}>Remove report</button><button className="btn btn-soft" onClick={()=>setDeleteId('')}>Cancel</button></div>}
      {selected&&<div className="stack"><h3>Review {selected.title}</h3><div className="overview-signals">{[{label:"Detected results",value:selected.results.length},{label:"Within supplied range",value:selected.results.filter(r=>rangeFlag(r)==="within").length},{label:"Outside supplied range",value:selected.results.filter(r=>["high","low"].includes(rangeFlag(r))).length},{label:"Range unknown",value:selected.results.filter(r=>rangeFlag(r)==="unknown").length}].map(s=><article className="card" key={s.label}><strong>{s.value}</strong><p>{s.label}</p></article>)}</div>{selected.warnings.map((w,i)=><p className="subtle" role={w.startsWith("Extraction failed")?"alert":undefined} key={i}>{w}</p>)}<label>Title<input className="input" value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></label><label>Category<select className="input" value={selected.category} onChange={e=>setSelected({...selected,category:e.target.value as MedicalReport['category']})}>{['laboratory','radiology','ECG','discharge','other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Report collection time (ISO)<input className="input" value={selected.collectedAt} onChange={e=>setSelected({...selected,collectedAt:e.target.value})}/></label><TextAreaField label="Verified report narrative" className="input" rows={6} value={selected.narrative} onChange={e=>setSelected({...selected,narrative:e.target.value})}/>
        {selected.results.map(row=><fieldset className="stack" key={row.id}><legend>{row.name} · {rangeFlag(row)} · {row.sourceFlag?`source flag: ${row.sourceFlag}`:'no source flag'}</legend><p className="subtle">{row.sourceLine}</p><div className="bio-form-grid">{(['name','loinc','value','unit','referenceLow','referenceHigh','referenceText','method','specimen','laboratory','collectedAt','valueText','sourceFlag'] as const).map(key=><label key={key}>{key}<input className="input" type={['value','referenceLow','referenceHigh'].includes(key)?'number':'text'} step="any" value={row[key]??''} onChange={e=>updateResult(row.id,key,e.target.value)}/></label>)}<label>Comparator<select className="input" value={row.comparator||''} onChange={e=>setSelected({...selected,results:selected.results.map(r=>r.id===row.id?{...r,comparator:e.target.value?e.target.value as LabResult['comparator']:undefined}:r)})}><option value="">Exact value</option>{['<','<=','>','>='].map(v=><option key={v}>{v}</option>)}</select></label></div><button className="btn btn-soft" onClick={()=>setSelected({...selected,results:selected.results.filter(r=>r.id!==row.id)})}>Remove result</button></fieldset>)}
        <button className="btn btn-soft" onClick={()=>setSelected({...selected,results:[...selected.results,labSchema.parse({id:crypto.randomUUID(),name:'New result',valueText:'Pending review',unit:'',collectedAt:selected.collectedAt,laboratory:selected.laboratory})]})}>Add missed result</button>
        <button className="btn btn-soft" disabled={busy} onClick={()=>void run(async()=>{const units=await get(`/api/medical/reports/${selected.id}/units`);const fhir=await get(`/api/medical/reports/${selected.id}/validate-fhir`);downloadArtifact("health-os-standards-check.json",JSON.stringify({units,fhir},null,2));})}>Check UCUM units and FHIR structure</button><label className="row"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I checked the patient identity, collection dates, results, units and ranges against the original.</label>
        <div className="row"><button className="btn btn-hot" disabled={busy||!confirm||selected.warnings.some(w=>w.startsWith("Extraction failed"))&&selected.results.length===0&&!selected.narrative.trim()} onClick={()=>void run(async()=>{const result=await put<{report:MedicalReport}>(`/api/medical/reports/${selected.id}/review`,{report:selected,revision:selected.revision,confirmPatient:true});await importDraft.clear();setSelected(result.report);setConfirm(false);await reload();})}>Confirm reviewed record</button><button className="btn btn-soft" onClick={()=>setSelected(null)}>Close review</button></div>
        {selected.status==='reviewed'&&<details><summary>Inbox and follow-up for this report</summary><MedicalActionCenter reportId={selected.id}/></details>}
        {selected.status==='reviewed'&&<details className="stack"><summary>Explain this report with my AI provider</summary><p className="subtle">Shares this report’s test names, dates, numeric results, units and ranges, including comparable prior results. Original documents, patient identity, narrative and medications are excluded.</p><pre className="bio-json">{JSON.stringify(trends.filter(t=>t.points.some(p=>p.reportId===selected.id)).map(t=>({test:t.name,unit:t.unit,points:t.points.map(p=>({date:p.collectedAt,value:p.value,low:p.referenceLow,high:p.referenceHigh})),direction:t.direction,comparison:t.flag})),null,2)}</pre><label className="row"><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/>Send this displayed evidence to my configured AI provider.</label><div className="row wrap"><button className="btn btn-soft" disabled={busy||!aiConsent} onClick={()=>void run(async()=>{const result=await post<{answer:string}>(`/api/medical/reports/${selected.id}/explain`,{consent:true});setExplanation(result.answer);setAiConsent(false);})}>Explain reviewed evidence</button><button className="btn btn-soft" disabled={busy} onClick={()=>void run(async()=>downloadArtifact('health-os-cql-inventory.json',JSON.stringify(await post(`/api/medical/reports/${selected.id}/cql`),null,2)))}>Run CQL record inventory</button></div>{explanation&&<><p style={{whiteSpace:'pre-wrap'}}>{explanation}</p><p className="subtle">AI-generated explanation. Check it against the structured results.</p></>}</details>}
      </div>}
    </>}
    {tab==='Changes'&&<>{trends.length===0&&<p>Review your first report to build a medical timeline.</p>}{trends.map((t,i)=><article className="stack" key={i}><h3>{t.name} · {t.direction}</h3><p>{(t.points.at(-1)?.loinc?LAB_TESTS.find(test=>test.loinc===t.points.at(-1)?.loinc):identifyTest(t.name))?.description||'Discuss this test’s purpose with your clinician.'}</p><SignalChart label={t.name} unit={t.unit} points={t.points.map(p=>({date:p.collectedAt.slice(0,10),value:p.value!}))}/><p>{t.explanation}</p><p className="subtle">{t.question}</p></article>)}<p className="subtle">Results with different units, specimens or methods are kept apart unless a supported unit conversion exists. Associations do not establish a cause.</p></>}
    {tab==='Signals'&&<><h3>Physiological deviation: {signals.level}</h3><p>{signals.unusual} unusual signals · {signals.coverage} signals with enough baseline data</p>{signals.signals.map(s=><div className="bio-record" key={s.metric}><strong>{s.metric}</strong><span>{format(s.current)} {s.unit} · change {format(s.delta)} · {format(s.percent)}% · {s.reason}</span></div>)}<p className="subtle">{signals.explanation}</p><div className="row wrap">{['Normal','Tired','Unwell'].map(feeling=><button className="btn btn-soft" disabled={busy} key={feeling} onClick={()=>void run(()=>bio.save({type:'journal',domain:'Health',name:`Feeling ${feeling.toLowerCase()}`,metadata:{feeling,signalVersion:signals.version}}))}>{feeling}</button>)}<button className="btn btn-soft" onClick={()=>quick.open('symptom')}>Add symptoms</button></div></>}
    {tab==='Calculators'&&<form className="stack" onSubmit={e=>{e.preventDefault();setError('');try{setCalculation(calculateMedical({type:calc,...Object.fromEntries(Object.entries(values).map(([k,v])=>[k,['sex','unit'].includes(k)?v:v===''?undefined:Number(v)]))}));}catch(e){setError((e as Error).message);setCalculation(null);}}}><label>Calculator<select className="input" value={calc} onChange={e=>{setCalc(e.target.value);setValues(calcDefaults[e.target.value]);setCalculation(null);}}>{Object.keys(calcDefaults).map(k=><option key={k}>{k}</option>)}</select></label><div className="bio-form-grid">{Object.keys(values).map(k=><label key={k}>{labels[k]}{['sex','unit'].includes(k)?<select className="input" value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}>{(k==='sex'?['female','male']:['mg/dL','umol/L']).map(v=><option key={v}>{v}</option>)}</select>:<input className="input" type="number" step="any" required value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/>}</label>)}</div><button className="btn btn-hot">Calculate</button>{calculation&&<article><h3>{format(calculation.value)} {calculation.unit}</h3><p>{calculation.version} · {calculation.population}</p><p>{calculation.limitations}</p><a href={calculation.source} target="_blank" rel="noreferrer">Equation source</a></article>}</form>}
    {tab==='Medication'&&<><h3>Medication context</h3>{medications.duplicates.map(d=><p key={d.ids.join(',')}>{d.name}: {d.message}</p>)}<p>{medications.message}</p>{records.filter(r=>r.type==='medication'||r.type==='supplement').map(r=><div className="bio-record" key={r.id}><strong>{r.name}</strong><span>{String(r.metadata.dose||r.metadata.serving||'')} · {String(r.metadata.frequency||'')} · {r.timestamp.slice(0,10)}</span></div>)}</>}
    {tab==='Doctor summary'&&<><p>Export reviewed medical records and recorded vitals, symptoms, illness and medication context from the last 90 days.</p><div className="row wrap">{Object.entries(summarySections).map(([key,value])=><label key={key}><input type="checkbox" checked={value} onChange={e=>setSummarySections({...summarySections,[key]:e.target.checked})}/>{key}</label>)}</div><button className="btn btn-hot" disabled={busy||!connected} onClick={()=>void run(async()=>{const to=new Date().toISOString(),from=new Date(Date.now()-90*86400000).toISOString();const summary=await post<DoctorSummary>('/api/medical/doctor-summary',{date,records,from,to});if(summary.medicalActions){for(const key of Object.keys(summarySections) as (keyof typeof summarySections)[])if(!summarySections[key])delete summary.medicalActions[key];}downloadArtifact('health-os-doctor-summary.json',JSON.stringify(summary,null,2));downloadArtifact('health-os-doctor-summary.html',doctorSummaryHtml(summary),'text/html');})}>Export appointment summary</button></>}
    {tab==='Research'&&<><ResearchWorkbench/><MedicalActionCenter view="research"/><p>Export selected vital, sleep, symptom and illness records for local research. Report text, notes and medications are excluded. Dates and device information may still identify you.</p><label>Stable participant pseudonym<input className="input" value={participantId} pattern="[A-Za-z0-9_-]{8,80}" onChange={e=>setParticipantId(e.target.value)}/></label><label>Research purpose<input className="input" minLength={3} maxLength={500} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to downloading these records for this research purpose.</label><button className="btn btn-hot" disabled={busy||!consent||purpose.length<3||!/^[A-Za-z0-9_-]{8,80}$/.test(participantId)||!connected} onClick={()=>void run(async()=>{const data=await post('/api/medical/research-export',{date,records,consent,purpose,domains:['vital','sleep','symptom','illness'],participantId});localStorage.setItem('body-os-medical-participant',participantId);downloadArtifact('health-os-research.json',JSON.stringify(data,null,2));setConsent(false);})}>Export research dataset</button><p className="subtle">Research models cannot issue disease predictions in the product. The Python engine evaluates models separately using participant and chronological holdouts.</p></>}
    {tab==='Technology'&&<><button className="btn btn-soft" disabled={busy||!connected} onClick={()=>void run(async()=>{setCapabilities(await get('/api/medical/capabilities'));setResearchStatus(await get('/api/medical/research/status'));setRuleRegistry(await get('/api/medical/rules'));})}>Check integration status</button>{capabilities&&Object.entries(capabilities).map(([k,v])=><div className="bio-record" key={k}><strong>{k}</strong><span>{v}</span></div>)}{researchStatus!==null&&<details><summary>Python research libraries</summary><pre className="bio-json">{JSON.stringify(researchStatus,null,2)}</pre></details>}{ruleRegistry!==null&&<details><summary>Clinical rule sources and review status</summary><pre className="bio-json">{JSON.stringify(ruleRegistry,null,2)}</pre></details>}<p className="subtle">FHIR, LOINC, UCUM, CQL and CDS Hooks form the standards layer. Clinical approval, licensed vocabularies, external hospital connections and validated prediction models require separate configuration.</p></>}
  </section>;
}
