import { useDraftState } from '../lib/use-draft';
import { SaveStatus } from './SaveStatus';
import { legacyBiology } from '../lib/biology-legacy';
import { useAutomations } from '../state/AutomationContext';
import { createContext, useContext, useEffect, useState, useRef, type ReactNode } from 'react';
import { Modal } from './Modal';
import { OSIcon } from './OSIcon';
import { useToast } from './Toast';
import { useApp } from '../state/AppContext';
import { useBiology } from '../state/BiologyContext';
import { atTime, scaleNutrition } from '../../shared/biological-intelligence';
import { dateOf, type BioKind, type BioRecord } from '../../shared/biology';
import type { BioInput } from '../state/SupabaseBiologyContext';
import { bioForms } from '../lib/biology-forms';
import { copyLocalPhoto, saveLocalPhoto } from '../lib/local-visuals';
import { HealthOsImage, PersonalPhotoControl } from './HealthOsImage';
import { recordVisual } from '../lib/visual-assets';
import { DailyReadiness } from './DailyReadiness';

export type LogRequest={kind:BioKind;initial?:BioRecord;date?:string;defaults?:Record<string,string|number|boolean>;onSaved?:()=>void|Promise<void>;};
const QuickContext=createContext<{open:(kind:BioKind,initial?:BioRecord,date?:string,defaults?:LogRequest['defaults'],onSaved?:LogRequest['onSaved'])=>void;repeat:(record:BioRecord,date?:string)=>Promise<void>}>({open:()=>{},repeat:async()=>{}});
export const useQuickLog=()=>useContext(QuickContext);
const simpleKinds=new Set<BioKind>(['meal','water','sleep','checkIn','vital','symptom','recoveryNote','supplement','medication','journal','environment','bodyMeasurement']);
export function QuickLogProvider({children,advanced}:{children:ReactNode;advanced:(request:LogRequest,close:()=>void)=>ReactNode}){
  const [request,setRequest]=useState<LogRequest|null>(null),bio=useBiology(),toast=useToast(),app=useApp();
  const open=(kind:BioKind,initial?:BioRecord,date?:string,defaults?:LogRequest['defaults'],onSaved?:LogRequest['onSaved'])=>{if(kind==='checkIn')app.setPage('Today');setRequest({kind,initial,date,defaults,onSaved});};
  const repeating=useRef(new Map<string,{id:string;busy:boolean}>());
  const repeat=async(record:BioRecord,date?:string)=>{
    const key=`${record.id}:${date||'today'}`, attempt=repeating.current.get(key)||{id:crypto.randomUUID(),busy:false};
    if(attempt.busy)return; attempt.busy=true;repeating.current.set(key,attempt);const id=attempt.id;
    try {
    await bio.save({id,type:'meal',domain:'Eat',name:record.name,timestamp:date?atTime(date,new Date().toTimeString().slice(0,5)):undefined,source:record.source,quality:record.quality,metadata:{...record.metadata,completeDay:false,repeatedFrom:record.id}});
    await copyLocalPhoto(record.id,id).catch(()=>undefined);
    toast.push(`${record.name} saved on this device — sync pending`,'ok');repeating.current.delete(key);
    }finally{attempt.busy=false;}
  };
  return <QuickContext.Provider value={{open,repeat}}>{children}{request&&(request.kind==='checkIn'?<DailyReadiness key={`${request.initial?.id||'new'}-${request.date}`} {...request} close={()=>setRequest(null)}/>:simpleKinds.has(request.kind)?<QuickEntry key={`${request.kind}-${request.initial?.id||'new'}-${request.date}`} request={request} close={()=>setRequest(null)}/>:advanced(request,()=>setRequest(null)))}</QuickContext.Provider>;
}
const units:Record<string,string>={HRV:'ms','Resting HR':'bpm','Heart Rate':'bpm',Steps:'steps','Active Calories':'kcal','Blood Pressure Systolic':'mmHg','Blood Pressure Diastolic':'mmHg','Blood Glucose':'mmol/L',Oxygen:'%',Temperature:'°C',Respiration:'breaths/min',Weight:'kg'};
function Choice({values,value,onChange,label}:{values:(string|number)[];value:string|number|boolean|undefined;onChange:(v:string|number)=>void;label:string}){
  return <div className="flow-choices" role="group" aria-label={label}>{values.map(v=><button type="button" key={v} aria-pressed={value===v} className={value===v?'active':''} onClick={()=>onChange(v)}>{v}</button>)}</div>;
}
function QuickEntry({request,close}:{request:LogRequest;close:()=>void}){
  const {kind,initial,defaults={}}=request,bio=useBiology(),app=useApp(),toast=useToast(),automation=useAutomations();
  const suggested={...(automation.preferences.smartDefaults&&!initial?(automation.state.derived.defaults?.value as Record<string,Record<string,string|number|boolean>>|undefined)?.[['vital','bodyMeasurement'].includes(kind)?`${kind}:${defaults.metric||(kind==='vital'?'Weight':'Measurement')}`:kind]||{}:{})};
  if(kind==='vital'&&defaults.metric==='Weight'&&suggested.value!==undefined&&defaults.unit&&suggested.unit!==defaults.unit){if(suggested.unit==='lb'&&defaults.unit==='kg')suggested.value=Number(suggested.value)/2.2046226218;else if(suggested.unit==='kg'&&defaults.unit==='lb')suggested.value=Number(suggested.value)*2.2046226218;}
  const automatic=automation.state.derived.adaptiveCheckin?.value as {inputs:{metric:string;value:number|null;reliable:boolean;kind:string}[]}|undefined;
  const today=dateOf(new Date().toISOString()),date=request.date||today,now=new Date();
  const known=bio.records.filter(r=>r.type==='checkIn'&&!r.deletedAt&&dateOf(r.timestamp)===date&&r.quality!=='estimated'&&(r.metadata.requiresConfirmation!==true||r.metadata.confirmed===true)).sort((a,b)=>b.timestamp.localeCompare(a.timestamp))[0]||(app.db?legacyBiology(app.db).find(r=>r.type==='checkIn'&&dateOf(r.timestamp)===date):undefined);
  const knownValues=kind==='checkIn'&&automation.preferences.adaptiveCheckin&&!initial?Object.fromEntries(Object.entries(known?.metadata||{}).filter(([key,value])=>['energy','soreness','stress','motivation','mood','pain','painAnswer','notes'].includes(key)&&(typeof value!=='number'||value>=(['soreness','stress'].includes(key)?0:1)&&value<=10))):{};
  const draft=useDraftState<Record<string,string|number|boolean>>(`quick:${kind}:${initial?.id || 'new'}:${date}:${defaults.metric || defaults.subtype || ''}`,()=>({__recordId:initial?.id || crypto.randomUUID(),name:initial?.name||({water:'Water',sleep:'Last night’s sleep',checkIn:'Daily check-in',journal:'A moment to reflect',vital:String(defaults.metric||'Weight'),environment:'Today’s environment',bodyMeasurement:'Measurement'} as Record<string,string>)[kind]||'',value:initial?.value??'',unit:initial?.unit||(kind==='water'?'mL':kind==='sleep'?'hours':kind==='vital'?units[String(defaults.metric||'Weight')]:''),...(kind==='meal'?{meal:now.getHours()<11?'Breakfast':now.getHours()<16?'Lunch':'Dinner'}:{}),...(kind==='sleep'?{bedtime:'23:00',wake:'07:00'}:{}),...(['supplement','medication'].includes(kind)?{time:'09:00'}:{}),...knownValues,...suggested,...initial?.metadata,...defaults}));
  const v=draft.value,setV=draft.setValue;
  const [forceQuestions,setForceQuestions]=useState(false);
  const [step,setStep]=useState(()=>kind==='checkIn'&&automation.preferences.adaptiveCheckin&&!initial?['energy','soreness','stress'].findIndex(k=>knownValues[k]===undefined)===-1?3:Math.max(0,['energy','soreness','stress'].findIndex(k=>knownValues[k]===undefined)):0),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const portion=Number(v.__portion || 1),setPortion=(value:number)=>setV(previous=>({...previous,__portion:value}));
  useEffect(()=>{
    if(kind!=='checkIn'||initial||!known||!automation.preferences.adaptiveCheckin||forceQuestions)return;
    // Late local/server hydration must not repeat known questions or replace answers already entered.
    const incoming=Object.fromEntries(Object.entries(knownValues).filter((entry):entry is [string,string|number|boolean]=>v[entry[0]]===undefined&&entry[1]!==null));
    if(!Object.keys(incoming).length)return;
    const merged={...v,...incoming};setV(merged);
    const missing=['energy','soreness','stress'].findIndex(key=>merged[key]===undefined);setStep(missing<0?3:missing);
  },[known?.id,known?.updatedAt,kind,date,automation.preferences.adaptiveCheckin]);
  const set=(key:string,value:string|number|boolean)=>setV(prev=>({...prev,[key]:value}));
  const number=(key:string)=>v[key]===''||v[key]===undefined?undefined:Number(v[key]);
  const numberField=(key:string,label:string,unit='',required=false,min=0,max=200000)=><label className="flow-field">{label}<div><input className="input" type="number" aria-label={label} step="any" min={min} max={max} value={String(v[key]??'')} required={required} onChange={e=>set(key,e.target.value)}/>{unit&&<span>{unit}</span>}</div></label>;
  const textField=(key:string,label:string,placeholder='',required=false)=><label className="flow-field">{label}<input className="input" aria-label={label} placeholder={placeholder} value={String(v[key]??'')} required={required} onChange={e=>set(key,e.target.value)}/></label>;
  const save=async()=>{
    setBusy(true);setError('');try{
      const metadata:BioRecord['metadata']={...initial?.metadata};for(const [key,value]of Object.entries(v))if(!key.startsWith('__')&&!['name','value','unit','recordQuality','source','eatenTime'].includes(key)&&value!=='')metadata[key]=value;
      const numeric=['calories','protein','carbs','fat','fibre','sodium','iron','calcium','vitaminD','saturatedFat','sugars','potassium','magnesium','zinc','folate','vitaminB12','vitaminC','energy','stress','soreness','motivation','mood','quality','severity','deep','rem','light','awake','serving','humidity','temperature'];
      for(const key of numeric)if(v[key]!==undefined&&v[key]!=='')metadata[key]=Number(v[key]);
      let timestamp=initial?.timestamp||(date===today?now.toISOString():atTime(date,'12:00')),value=number('value'),endTime=initial?.endTime;
      if(kind==='sleep'){
        timestamp=atTime(date,String(v.wake||'07:00'));endTime=timestamp;
        if(value===undefined){const bed=String(v.bedtime).split(':').map(Number),wake=String(v.wake).split(':').map(Number);value=((wake[0]*60+wake[1]-bed[0]*60-bed[1]+1440)%1440)/60;}
        if(!value||value>24)throw new Error('Choose your sleep duration or bedtime and wake time.');
        metadata.startTime=new Date(Date.parse(timestamp)-value*3600000).toISOString();
      }
      if(kind==='checkIn'&&['energy','stress','soreness'].some(k=>number(k)===undefined))throw new Error('Choose how you felt for all three check-in questions.');
      if(kind==='vital'){metadata.metric=String(v.metric||'Weight');if(!v.unit)set('unit',units[String(metadata.metric)]||'');}
      if(kind==='meal'){metadata.completeDay=false;Object.assign(metadata,scaleNutrition(metadata,portion));if(v.eatenTime)timestamp=atTime(date,String(v.eatenTime));}
      if(kind==='bodyMeasurement')metadata.metric=String(v.metric||v.name);
      const input:BioInput={id:initial?.id||String(v.__recordId),type:kind,domain:defaults.domain==='Care'?'Care':kind==='vital'&&metadata.metric==='Weight'?'Body':bioForms[kind].domain,name:String(v.name||bioForms[kind].title),timestamp,endTime,value,unit:String(v.unit||(kind==='vital'?units[String(metadata.metric)]||'':'')),quality:initial?.quality||((defaults.recordQuality||suggested.recordQuality)==='estimated'?'estimated':'manual'),source:initial?.source||String(defaults.source||suggested.source||(defaults.recordQuality==='estimated'?'Health OS approved AI estimate':'Health OS manual')),metadata};
      if(kind==='checkIn'&&!initial?.id)input.id=`check-in-${date}`;
      if(kind==='meal'&&!input.id)input.id=crypto.randomUUID();
      if(kind==='checkIn'&&known&&!initial&&['energy','soreness','stress','motivation','mood','pain','painAnswer','notes'].every(k=>v[k]===known.metadata[k]||v[k]===undefined&&known.metadata[k]===undefined)){await request.onSaved?.();toast.push('Your check-in is already recorded','ok');close();return;}
      await bio.save(input);
      if(kind==='meal'&&input.id)try{if(defaults.__localPhoto)await saveLocalPhoto(input.id,String(defaults.__localPhoto));else if(defaults.__photoSource)await copyLocalPhoto(String(defaults.__photoSource),input.id);}catch{toast.push('Meal saved. The private thumbnail could not be retained.','info');}
      await draft.clear().catch(()=>toast.push('Saved locally. The previous draft could not be removed.','info'));
      await request.onSaved?.();toast.push(`${input.name} saved on this device — sync pending`,'ok');close();
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  };
  const checkQuestions=[{key:'energy',title:'How’s your energy?',hint:'From running on empty to ready for anything.',labels:['Drained','Low','Okay','Good','Great']},{key:'soreness',title:'How sore do you feel?',hint:'Think about how movement feels today.',labels:['None','A little','Noticeable','Quite sore','Very sore']},{key:'stress',title:'How’s your stress?',hint:'A quick sense check is enough.',labels:['Calm','Low','Moderate','High','Very high']}];
  const question=checkQuestions[Math.min(step,2)];
  const title=(kind==='checkIn'?'A moment for you':initial?.id?`Edit ${bioForms[kind].title.toLowerCase()}`:kind==='meal'?'What’s on your plate?':kind==='water'?'A water break':kind==='sleep'?'How did you sleep?':kind==='vital'&&v.metric==='Weight'?'A quick weigh-in':`Log ${bioForms[kind].title.toLowerCase()}`);
  return <Modal open title="" ariaLabel={title} onClose={close} className="flow-modal"><div className="flow-modal-top"><span className="flow-icon"><OSIcon name={bioForms[kind].domain==='Today'?'Today':bioForms[kind].domain}/></span></div><p className="bio-eyebrow">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short'})} · {kind==='checkIn'?step===3?'ALREADY RECORDED':`STEP ${step+1} OF 3`:'QUICK LOG'}</p><h2>{title}</h2>
    {automation.preferences.smartDefaults&&Object.keys(suggested).length>0&&<p className="subtle">Suggested from your previous entry. Review or edit before saving.</p>}
    {kind==='checkIn'&&automation.preferences.adaptiveCheckin&&automatic&&<details className="flow-details" open><summary>Already available — no need to enter again</summary>{automatic.inputs.filter(i=>i.reliable).map(i=><p key={i.metric}>{i.metric} AUTO ✓ {i.value} · {i.kind}</p>)}<p className="subtle">Only your subjective signals need an answer.</p></details>}
    <SaveStatus status="idle" detail={draft.status}/><form className="stack" onSubmit={e=>{e.preventDefault();if(kind==='checkIn'&&step<2){if(v[question.key]!==undefined){const next=[1,2].find(i=>i>step&&v[checkQuestions[i].key]===undefined);setStep(forceQuestions?step+1:next??3);}}else void save();}}>
      {kind==='meal'&&initial&&<><HealthOsImage context={{...recordVisual(initial),entityId:String(defaults.__photoSource||initial.id)||undefined,userImage:typeof defaults.__localPhoto==='string'?defaults.__localPhoto:undefined}} variant="cover"/>{initial.id&&<PersonalPhotoControl entityId={initial.id} label="meal photo"/>}</>}
      {kind==='water'&&<><p className="subtle">Tap your usual glass, or choose an amount.</p><Choice label="Water amount" values={[250,350,500,750]} value={Number(v.value)} onChange={value=>set('value',value)}/>{numberField('value','Amount','mL',true,1,20000)}<Choice label="Beverage" values={['Water','Tea','Coffee','Other']} value={v.beverage||'Water'} onChange={value=>{set('beverage',value);set('name',value);}}/></>}
      {kind==='checkIn'&&step===3&&<div className="stack"><h3>Your answers are already available</h3>{checkQuestions.map(q=><p key={q.key}>{q.title} {v[q.key]} /10</p>)}<button type="button" className="btn btn-soft" onClick={()=>{setForceQuestions(true);setStep(0);}}>Update answers</button></div>}
      {kind==='checkIn'&&step<3&&<><div className="flow-progress">{[0,1,2].map(i=><span key={i} className={i<=step?'filled':''}/>)}</div><h3 className="flow-question">{question.title}</h3><p className="subtle">{question.hint}</p><div className="flow-feelings" role="group" aria-label={question.title}>{[1,3,5,7,10].map((value,i)=><button type="button" key={value} aria-pressed={Number(v[question.key])===value} onClick={()=>set(question.key,value)}><span>{['◔','◑','◕','◉','✦'][i]}</span>{question.labels[i]}</button>)}</div>{step===2&&<label className="flow-toggle"><input type="checkbox" checked={Boolean(v.pain)} onChange={e=>set('pain',e.target.checked)}/> Pain is affecting movement today</label>}</>}
      {kind==='meal'&&<><Choice label="Meal" values={['Breakfast','Lunch','Snacks','Dinner']} value={v.meal} onChange={value=>set('meal',value)}/>{textField('name','Name','e.g. Paneer bowl',true)}<div className="flow-field-grid">{numberField('calories','Calories (kcal)','kcal',true)}{numberField('protein','Protein (g)','g')}</div><div className="flow-portion"><span>Portions</span><button type="button" aria-label="Decrease portions" disabled={portion<=.25} onClick={()=>setPortion(Math.max(.25,portion-.25))}>−</button><strong>{portion}</strong><button type="button" aria-label="Increase portions" disabled={portion>=20} onClick={()=>setPortion(Math.min(20,portion+.25))}>＋</button></div><details className="flow-details"><summary>Carbs, fats & nutrients <span>Optional</span></summary><div className="flow-field-grid">{[['carbs','Carbohydrates (g)'],['fat','Fat (g)'],['fibre','Fibre (g)'],['sodium','Sodium (mg)'],['saturatedFat','Saturated fat (g)'],['sugars','Sugars (g)'],['iron','Iron (mg)'],['calcium','Calcium (mg)'],['potassium','Potassium (mg)'],['magnesium','Magnesium (mg)'],['zinc','Zinc (mg)'],['folate','Folate (µg)'],['vitaminB12','Vitamin B12 (µg)'],['vitaminC','Vitamin C (mg)'],['vitaminD','Vitamin D (µg)']].map(([k,l])=><div key={k}>{numberField(k,l)}</div>)}</div></details></>}
      {kind==='sleep'&&<><p className="subtle">Use bed and wake times, or log a duration.</p><div className="flow-field-grid"><label className="flow-field">Bedtime<input className="input" type="time" value={String(v.bedtime)} onChange={e=>{set('bedtime',e.target.value);set('value','');}}/></label><label className="flow-field">Wake time<input className="input" type="time" value={String(v.wake)} onChange={e=>{set('wake',e.target.value);set('value','');}}/></label></div><Choice label="Sleep duration" values={[6,6.5,7,7.5,8,8.5,9]} value={Number(v.value)} onChange={value=>set('value',value)}/>{numberField('value','Sleep duration (hours)','h',false,0,24)}<label className="flow-toggle"><input type="checkbox" checked={Boolean(v.nap)} onChange={e=>set('nap',e.target.checked)}/> This was a nap</label><details className="flow-details"><summary>Quality & sleep stages <span>Optional</span></summary><div className="flow-field-grid">{numberField('quality','Perceived quality','/10',false,1,10)}{numberField('deep','Deep sleep','h',false,0,24)}{numberField('rem','REM sleep','h',false,0,24)}{numberField('light','Light sleep','h',false,0,24)}</div></details></>}
      {kind==='vital'&&<><Choice label="Metric" values={['Weight','HRV','Resting HR','Steps','Blood Glucose','Oxygen','Temperature']} value={v.metric||'Weight'} onChange={value=>{set('metric',value);set('unit',units[String(value)]);set('name',value);}}/>{numberField('value',String(v.metric||'Weight'),String(v.unit||units[String(v.metric||'Weight')]),true,.01)}<details className="flow-details"><summary>Other metric, unit & context</summary><label className="flow-field">Metric<select className="input" value={String(v.metric||'Weight')} onChange={e=>{set('metric',e.target.value);set('name',e.target.value);set('unit',units[e.target.value]||'');}}>{Object.keys(units).map(m=><option key={m}>{m}</option>)}</select></label>{textField('unit','Unit')}{textField('context','Context','Fasting, after a meal, post-workout…')}</details></>}
      {['symptom','recoveryNote'].includes(kind)&&<>{textField('name',kind==='symptom'?'What are you noticing?':'What needs care?',kind==='symptom'?'e.g. Headache':'e.g. Left knee',true)}<span className="subtle">How intense is it?</span><Choice label="Severity" values={[...new Set([0,2,4,6,8,10,...(v.severity!==undefined&&v.severity!==''?[Number(v.severity)]:[])])].sort((a,b)=>a-b)} value={v.severity} onChange={value=>set('severity',value)}/>{kind==='symptom'&&<details className="flow-details"><summary>Symptom details</summary>{textField('concept','Symptom concept','e.g. Sore throat')}{textField('snomedCode','SNOMED CT code (if known)')}{textField('onset','Onset date','YYYY-MM-DD')}{textField('bodyArea','Body area')}{textField('context','Context')}<label className="row"><input type="checkbox" checked={v.emergencyBreathing===true} onChange={e=>set('emergencyBreathing',e.target.checked)}/>Severe difficulty breathing, gasping or unable to speak</label>{v.emergencyBreathing===true&&<p role="alert">Seek emergency medical help now using your local emergency service.</p>}</details>}{kind==='recoveryNote'&&<>{textField('region','Body area','e.g. Knee')}<Choice label="Side" values={['left','right','both']} value={v.side||''} onChange={value=>set('side',value)}/></>}<Choice label="Status" values={['Active','Resolved']} value={v.status||'Active'} onChange={value=>set('status',value)}/></>}
      {['supplement','medication'].includes(kind)&&<>{textField('name',kind==='medication'?'Medication name':'Supplement name','',true)}{kind==='medication'?textField('dose','Prescribed dose','As directed by your clinician',true):<div className="flow-field-grid">{numberField('serving','Serving','',false,.01)}{textField('unit','Unit','e.g. capsule')}</div>}<label className="flow-field">Scheduled time<input className="input" type="time" value={String(v.time)} onChange={e=>set('time',e.target.value)}/></label><details className="flow-details"><summary>Repeat times & schedule details</summary>{kind==='medication'&&<>{textField('ingredient','Active ingredient')}{textField('allergies','Recorded allergies')}<Choice label="Medication status" values={['Active','Stopped']} value={v.status||'Active'} onChange={value=>set('status',value)}/></>}{textField('times','Times','09:00, 21:00')}<fieldset className="ux-fieldset"><legend>Repeat on (none selected means every day)</legend><div className="flow-choices">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,index)=>{const selected=String(v.daysOfWeek||'').split(',').filter(Boolean);return <button type="button" key={day} aria-pressed={selected.includes(String(index))} onClick={()=>set('daysOfWeek',selected.includes(String(index))?selected.filter(d=>d!==String(index)).join(','):[...selected,String(index)].sort().join(','))}>{day}</button>;})}</div></fieldset>{textField('food','With food?')}{textField('reason','Reason')}<div className="flow-field-grid"><label>Start date<input className="input" type="date" value={String(v.start||'')} onChange={e=>set('start',e.target.value)}/></label><label>End date<input className="input" type="date" value={String(v.end||'')} onChange={e=>set('end',e.target.value)}/></label></div></details>{kind==='medication'&&<p className="subtle">Use your prescribed dose and schedule.</p>}</>}
      {kind==='journal'&&defaults.subtype==='careObservation'&&<><label>Care area<select className="input" value={String(v.area||'face')} onChange={e=>set('area',e.target.value)}>{['face','body','hair','scalp'].map(a=><option key={a}>{a}</option>)}</select></label>{textField('concern','What are you noticing?','e.g. Dryness',true)}{numberField('severity','Self-rated severity','/10',false,0,10)}</>}
      {kind==='journal'&&<><p className="subtle">One thought is enough.</p><textarea className="input" aria-label="Reflection" placeholder="What went well? What would you change?" value={String(v.notes||'')} onChange={e=>set('notes',e.target.value)}/></>}
      {kind==='environment'&&<>{numberField('humidity','Humidity','%',false,0,100)}{numberField('temperature','Temperature','°C',false,-30,60)}{textField('climate','Conditions','e.g. Dry, humid, air-conditioned')}</>}
      {kind==='bodyMeasurement'&&<>{textField('metric','Measurement','e.g. Calf',true)}{numberField('value','Measured value',String(v.unit||'cm'),true)}{textField('unit','Unit','cm')}</>}
      {kind==='checkIn'&&step===2&&<details className="flow-details"><summary>Motivation, mood & pain (optional)</summary>{numberField('motivation','Motivation','/10',false,1,10)}{numberField('mood','Mood','/10',false,1,10)}<Choice label="Any pain?" values={['No','Yes']} value={v.painAnswer||''} onChange={value=>set('painAnswer',value)}/><textarea className="input" aria-label="Check-in notes" value={String(v.notes||'')} onChange={e=>set('notes',e.target.value)}/></details>}
      {kind!=='checkIn'&&kind!=='journal'&&<details className="flow-details"><summary>Notes & record time <span>Optional</span></summary><textarea className="input" aria-label="Notes" placeholder="Anything useful to remember…" value={String(v.notes||'')} onChange={e=>set('notes',e.target.value)}/><p className="subtle">Saved for {date}{initial?.source?` · ${initial.source}`:''}. Source and quality are kept with the entry.</p></details>}
      {error&&<p role="alert" className="bio-error">{error}</p>}<div className="flow-footer">{kind==='checkIn'&&step>0&&<button type="button" className="btn btn-soft" onClick={()=>setStep(step-1)}>Back</button>}<button className="btn btn-hot" disabled={busy||!draft.ready||(kind==='checkIn'&&v[question.key]===undefined)}>{busy?'Saving…':kind==='checkIn'&&step<2?'Continue':kind==='checkIn'?'Finish check-in':kind==='meal'?'Log meal':kind==='water'?'Log water':'Save entry'}</button></div>
    </form></Modal>;
}

export function QuickActions({date,compact=false}:{date?:string;compact?:boolean}){
  const quick=useQuickLog(),bio=useBiology(),toast=useToast(),app=useApp();
  const [busy,setBusy]=useState(false),[waterId,setWaterId]=useState(''),[error,setError]=useState('');
  const attempt=useRef(''),locked=useRef(false);
  const water=async()=>{if(locked.current)return;locked.current=true;setBusy(true);setError('');const id=attempt.current||crypto.randomUUID();attempt.current=id;
    try{await bio.save({id,type:'water',domain:'Eat',name:'Water',value:350,unit:'mL',timestamp:date?atTime(date,new Date().toTimeString().slice(0,5)):undefined});setWaterId(id);attempt.current='';}catch(cause){setError((cause as Error).message);}finally{locked.current=false;setBusy(false);}};
  const saved=bio.records.find(row=>row.id===waterId&&!row.deletedAt);
  return <div className="stack"><div className={`flow-actionbar ${compact?'compact':''}`} aria-label="Quick actions"><button disabled={busy} onClick={()=>void water()}><span>＋</span> {busy?'Saving…':'Water'} <small>350 mL</small></button><button onClick={()=>quick.open('meal',undefined,date)}><OSIcon name="Eat" size={18}/> Meal</button><button onClick={()=>quick.open('checkIn',undefined,date)}><OSIcon name="Recover" size={18}/> Check-in</button><button onClick={()=>quick.open('sleep',undefined,date)}><span>☾</span> Sleep</button><button onClick={()=>quick.open('vital',undefined,date,{metric:'Weight',unit:app.db?.profile.units||'kg'})}><OSIcon name="Body" size={18}/> Weight</button>{!compact&&<button onClick={()=>quick.open('journal',undefined,date)}><span>✎</span> Note</button>}</div>
  {error&&<SaveStatus status="failed" detail={error} retry={()=>void water()}/>}{saved&&<div className="row wrap" role="status"><span>350 mL water · {saved.syncState==='saved'?'Saved to account':bio.conflicts.some(row=>row.id===saved.id)?'Conflict needs review':'Saved on this device—sync pending'}</span><button className="btn btn-soft" onClick={()=>void bio.remove(saved).then(()=>setWaterId('')).catch(cause=>toast.push(cause.message,'err'))}>Undo water</button></div>}</div>;
}
