import {useDraftState} from '../lib/use-draft';
import {SaveStatus} from './SaveStatus';
import {useEffect,useState,useRef} from 'react';
import {FlashDeck} from './FlashDeck';
function GoogleFitMark({processing=false}:{processing?:boolean}){return <svg className={`google-fit-mark ${processing?'is-processing':''}`} viewBox="0 0 32 32" aria-hidden="true"><path d="M16 27C5 20 4 12 8.3 8.2c2.6-2.3 6.2-1.5 7.7 1.5 1.5-3 5.1-3.8 7.7-1.5C28 12 27 20 16 27Z" fill="none" stroke="#4285f4" strokeWidth="4" strokeLinecap="round"/><path d="M8.3 8.2c2.6-2.3 6.2-1.5 7.7 1.5" fill="none" stroke="#ea4335" strokeWidth="4" strokeLinecap="round"/><path d="M16 9.7c1.5-3 5.1-3.8 7.7-1.5" fill="none" stroke="#fbbc04" strokeWidth="4" strokeLinecap="round"/><path d="M16 27c11-7 12-15 7.7-18.8" fill="none" stroke="#34a853" strokeWidth="4" strokeLinecap="round"/></svg>}
const questions=[['sleepHours','How long did you sleep?','Hours of sleep last night.','0','24','0.1'],['sleepQuality','How was your sleep?','1 = very poor · 10 = excellent','1','10','1'],['soreness','How sore do you feel?','0 = none · 10 = very sore','0','10','1'],['energy','How is your energy?','1 = drained · 10 = full of energy','1','10','1'],['stress','How much stress today?','0 = calm · 10 = very stressed','0','10','1'],['motivation','Ready to move?','1 = very low · 10 = very motivated','1','10','1'],['mood','How are you feeling?','1 = very low · 10 = great','1','10','1']];
function missingAnswer(values:Record<string,any>,start=0){for(let i=start;i<questions.length;i++)if(values[questions[i][0]]===undefined||values[questions[i][0]]==='')return i;return start<=7&&!['true','false'].includes(String(values.painFlag))?7:8;}
export function ReadinessCards({initial,draftKey,onSave,onGoogleFitImport,reuseAnswers=false}:{initial:Record<string,any>;draftKey:string;onSave:(values:Record<string,any>)=>Promise<void>;reuseAnswers?:boolean;onGoogleFitImport?:()=>Promise<{values:Record<string,any>;labels:string[]}>}) {
 const draft=useDraftState<Record<string,any>>(draftKey,initial),values=draft.value,setValues=draft.setValue;
 const [index,setIndex]=useState(()=>reuseAnswers?missingAnswer(values):0),[reviewAll,setReviewAll]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[importState,setImportState]=useState<'idle'|'processing'|'imported'|'empty'>('idle'),[importedLabels,setImportedLabels]=useState<string[]>([]),[importStep,setImportStep]=useState('');
 const positioned=useRef(false);useEffect(()=>{if(draft.ready&&!positioned.current){positioned.current=true;if(reuseAnswers)setIndex(missingAnswer(values));}},[draft.ready,reuseAnswers,values]);
 useEffect(()=>{if(!draft.ready)return;setValues(current=>({...initial,...Object.fromEntries(Object.entries(current).filter(([,value])=>value!==undefined))}));},[initial,draft.ready]);
 const update=(key:string,value:string)=>setValues(v=>({...v,[key]:value}));
 const importGoogleFit=async()=>{if(!onGoogleFitImport)return;setBusy(true);setImportState('processing');setImportStep('Connecting to Google Fit…');setError('');const timer=window.setTimeout(()=>setImportStep('Reading today’s sleep, heart-rate, and steps…'),650);try{const imported=await onGoogleFitImport();setValues(v=>({...v,...Object.fromEntries(Object.entries(imported.values).filter(([,value])=>value!==undefined&&value!==null&&value!==''))}));setImportedLabels(imported.labels);setImportStep('Readings added to this readiness draft.');setImportState('imported');}catch(e){const message=(e as Error).message;setImportStep('');if(/No sleep, heart-rate, or step data/i.test(message)){setImportState('empty');}else{setImportState('idle');setError(message);}}finally{window.clearTimeout(timer);setBusy(false);}};
 return <section className="readiness-cards">{onGoogleFitImport?<><button type="button" className="google-fit-import-button" title="Import sleep and vitals from Google Fit" aria-label="Import sleep and vitals from Google Fit" disabled={busy} onClick={()=>void importGoogleFit()}><GoogleFitMark processing={importState==='processing'}/></button>{importState==='processing'?<p className="subtle">{importStep}</p>:null}{importState==='imported'?<p className="text-ok">✓ Imported {importedLabels.join(', ')} into today’s readiness draft. Review the cards, then select <strong>Save readiness</strong> to save it for this day.</p>:null}{importState==='empty'?<p className="subtle">Google Fit is connected, but it has no sleep, heart-rate, or step record for today. Complete these values manually.</p>:null}</>:null}<FlashDeck label="Daily check-in" index={index} onIndexChange={next=>setIndex(reuseAnswers&&!reviewAll&&next>index?missingAnswer(values,next):next)}>
 {questions.map(([key,title,hint,min,max,step],i)=><div key={key}><span className="flash-icon" aria-hidden="true">{['☾','✦','◌','ϟ','≈','↗','☺'][i]}</span><p className="page-eyebrow">A moment for yourself</p><h3>{title}</h3><p className="subtle">{hint}</p>{key==='sleepHours'?<label className="flash-number">Sleep hours<input aria-label="Sleep hours" type="number" min={min} max={max} step={step} required value={values[key]??''} onChange={e=>update(key,e.target.value)}/></label>:<><div className="flash-rating">{Array.from({length:10},(_,j)=><button key={j} type="button" aria-label={`${title} ${j+1}`} aria-pressed={Number(values[key])===j+1} className={Number(values[key])===j+1?'selected':''} onClick={()=>update(key,String(j+1))}>{j+1}</button>)}</div><input className="input" aria-label={title} type="number" min={min} max={max} step={step} required value={values[key]??''} onChange={e=>update(key,e.target.value)}/></>}</div>)}
 <div><span className="flash-icon">◎</span><h3>Anything else to know?</h3><label>Pain or injury?<select aria-label="Pain or injury?" className="input" required value={String(values.painFlag??'')} onChange={e=>update('painFlag',e.target.value)}><option value="">Choose an answer</option><option value="false">No pain flagged</option><option value="true">Yes, pain or injury</option></select></label><label>Resting heart rate · optional<input className="input" type="number" min="25" max="250" value={values.restingHeartRate??''} onChange={e=>update('restingHeartRate',e.target.value)}/></label><label>Steps · optional<input className="input" type="number" min="0" value={values.steps??''} onChange={e=>update('steps',e.target.value)}/></label><label>Notes · optional<textarea aria-label="Notes · optional" className="input" value={values.notes??''} onChange={e=>update('notes',e.target.value)}/></label></div>
 <div><span className="flash-icon">✓</span><h3>Your check-in, in perspective.</h3><p className="subtle">These inputs inform an estimated readiness score, not a medical assessment.</p><dl className="flash-review">{questions.map(([key,title])=><div key={key}><dt>{title}</dt><dd>{values[key]??'Not recorded'}</dd></div>)}<div><dt>Pain flagged</dt><dd>{String(values.painFlag)==='true'?'Yes':String(values.painFlag)==='false'?'No':'Not recorded'}</dd></div></dl><button type="button" className="btn btn-soft" onClick={()=>{setReviewAll(true);setIndex(0);}}>Edit answers</button><button type="button" className="btn btn-hot w-full" disabled={busy||!draft.ready} onClick={async()=>{for(let i=0;i<questions.length;i++){const [key,,,min,max]=questions[i];if(values[key]==null||values[key]===''||!Number.isFinite(Number(values[key]))||Number(values[key])<Number(min)||Number(values[key])>Number(max)){setIndex(i);setError('Please complete this answer.');return;}}if(!['true','false'].includes(String(values.painFlag))){setIndex(7);return;}setBusy(true);setError('');try{await onSave(values);await draft.clear();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save readiness'}</button></div>
 </FlashDeck>{error&&<p role="alert">{error}</p>}<SaveStatus status="idle" detail={draft.status}/><p className="subtle">Drafts are stored for this account on this device.</p></section>;
}
