import { TextAreaField } from './TextAreaField';
import { useDraftFields } from '../lib/use-draft';
import { DraftFeedback } from './DraftFeedback';
import { HealthOsImage } from './HealthOsImage';
import { compressVisualPhoto, saveLocalPhoto } from '../lib/local-visuals';
import { useState } from 'react';
import { Modal } from './Modal';
import { useBiologicalData } from '../lib/use-biological-data';
import { useToast } from './Toast';
import type { BioRecord } from '../../shared/biology';
import { scaleNutrition } from '../../shared/biological-intelligence';
export interface RecipeIngredient {recordId:string;name:string;grams:number;}
export function recipeIngredients(record:BioRecord):RecipeIngredient[]{try{const rows=JSON.parse(String(record.metadata.ingredientsJson||'[]'));return Array.isArray(rows)?rows.filter((r:any)=>typeof r.recordId==='string'&&typeof r.name==='string'&&typeof r.grams==='number'&&r.grams>0):[];}catch{return[];}}
export function RecipeBuilder({initial,close}:{initial?:BioRecord;close:()=>void}){
  const {bio,stored}=useBiologicalData(),toast=useToast();
  const draft=useDraftFields('recipe:'+(initial?.id||'new'),()=>({visualId:initial?.id||crypto.randomUUID(),name:initial?.name||'',servings:Number(initial?.metadata.servings)||2,ingredients:initial?recipeIngredients(initial):[] as RecipeIngredient[],foodId:'',grams:100,diet:String(initial?.metadata.diet||'Any'),minutes:Number(initial?.metadata.minutes)||20,cuisine:String(initial?.metadata.cuisine||''),cost:String(initial?.metadata.cost||''),instructions:String(initial?.metadata.instructions||'')}));
  const [visualId]=draft.field('visualId'),[cover,setCover]=useState('');
  const [name,setName]=draft.field('name'),[servings,setServings]=draft.field('servings'),[ingredients,setIngredients]=draft.field('ingredients'),[foodId,setFoodId]=draft.field('foodId'),[grams,setGrams]=draft.field('grams'),[diet,setDiet]=draft.field('diet'),[minutes,setMinutes]=draft.field('minutes'),[cuisine,setCuisine]=draft.field('cuisine'),[cost,setCost]=draft.field('cost'),[instructions,setInstructions]=draft.field('instructions'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const foods=stored.filter(r=>r.type==='food'),keys=['calories','protein','carbs','fat','fibre','saturatedFat','sugars','sodium','iron','calcium','potassium','magnesium','zinc','folate','vitaminB12','vitaminC','vitaminD'];
  const totals:Record<string,number>={},coverage:Record<string,number>={};for(const k of keys){const available=ingredients.filter(i=>typeof foods.find(f=>f.id===i.recordId)?.metadata[k]==='number');coverage[k]=available.length;if(available.length)totals[k]=available.reduce((sum,i)=>{const food=foods.find(f=>f.id===i.recordId)!;return sum+Number(food.metadata[k])*i.grams/Number(food.metadata.serving||100);},0)/Math.max(1,servings);}
  return <Modal open title="Make a meal worth repeating" onClose={close} className="flow-modal"><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(!ingredients.length)throw new Error('Add at least one ingredient.');const allergens=[...new Set(ingredients.flatMap(i=>String(foods.find(f=>f.id===i.recordId)?.metadata.allergens||'').split(',').map(s=>s.trim()).filter(Boolean)))].join(', ');await bio.save({id:visualId,type:'recipe',domain:'Eat',name,quality:'estimated',source:'Health OS recipe calculation',metadata:{...initial?.metadata,...totals,ingredients:ingredients.map(i=>`${i.grams} g ${i.name}`).join(', '),ingredientsJson:JSON.stringify(ingredients),nutrientCoverage:JSON.stringify(coverage),servings,diet,minutes,cuisine,allergens,instructions,...(cost!==''?{cost:Number(cost)}:{})}});if(cover)try{await saveLocalPhoto(visualId,cover);}catch{toast.push('Recipe saved. Its private cover could not be retained.','info');}await draft.clear();toast.push('Recipe saved on this device; account sync may be pending','ok');close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
<HealthOsImage context={{entityType:'recipe',entityId:initial?.id,name:name||'Recipe cover',userImage:cover||undefined}} variant="cover"/><label className="btn btn-soft">Choose private recipe cover<input type="file" accept="image/jpeg,image/png,image/webp" className="visual-file-input" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{setCover(await compressVisualPhoto(file));}catch(error){setError((error as Error).message);}}}/></label><small className="subtle">Cover stays in this browser, outside sync and backups.</small>
    <label>Give it a name<input className="input" required placeholder="e.g. My paneer bowl" value={name} onChange={e=>setName(e.target.value)}/></label><div className="flow-field-grid"><label>Makes<input className="input" type="number" min="1" max="100" value={servings} onChange={e=>setServings(Number(e.target.value))}/></label><label>Prep time (min)<input className="input" type="number" min="0" max="1440" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div>
    <div className="recipe-ingredient-picker"><label>Ingredient<select className="input" value={foodId} onChange={e=>setFoodId(e.target.value)}><option value="">Choose a saved food…</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Grams<input className="input" type="number" min="1" max="20000" value={grams} onChange={e=>setGrams(Number(e.target.value))}/></label><button type="button" className="btn btn-soft" disabled={!foodId||grams<=0} onClick={()=>{const food=foods.find(f=>f.id===foodId)!;setIngredients(prev=>[...prev,{recordId:food.id,name:food.name,grams}]);setFoodId('');}}>Add</button></div>{!foods.length&&<p className="subtle">Save foods from search first. Recipes reuse their nutrition data.</p>}
    <div className="recipe-ingredients">{ingredients.map((i,index)=><div key={index}><strong>{i.name}</strong><span>{i.grams} g</span><button type="button" aria-label={`Remove ${i.name}`} onClick={()=>setIngredients(items=>items.filter((_,n)=>n!==index))}>×</button></div>)}</div><div className="journey-day-summary"><span><strong>{Math.round(totals.calories||0)}</strong> kcal / serving</span><span><strong>{Math.round(totals.protein||0)}</strong> g protein</span></div><details className="flow-details"><summary>Preferences & instructions</summary><div className="stack"><label>Diet<select className="input" value={diet} onChange={e=>setDiet(e.target.value)}>{['Any','Vegetarian','Vegan'].map(d=><option key={d}>{d}</option>)}</select></label><label>Cuisine<input className="input" value={cuisine} onChange={e=>setCuisine(e.target.value)}/></label><label>Cost per serving<input className="input" type="number" min="0" step="any" value={cost} onChange={e=>setCost(e.target.value)}/></label><TextAreaField label="Instructions" className="input" value={instructions} onChange={e=>setInstructions(e.target.value)}/></div></details><p className="subtle">Nutrition is calculated from available ingredient data. Missing nutrients stay unknown.</p><DraftFeedback draft={draft}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-hot" disabled={busy||!draft.ready||!ingredients.length}>{busy?'Saving…':'Save recipe'}</button></form></Modal>;
}
