import { useState } from 'react';
import { get,post } from '../lib/api';
import { downloadArtifact } from '../lib/health-os-export';
import { researchWorkbenchSchema } from '../../shared/research-workbench';

const operations=['forecast','features','train','sequence','autoencoder','isolation','change-points'] as const;
function example(operation:string){
  const day=(i:number)=>new Date(Date.UTC(2026,0,1+i)).toISOString();
  const base={operation,consent:false,purpose:'Synthetic workflow demonstration',track:false};
  if(operation==='forecast')return {...base,horizonDays:7,rows:Array.from({length:90},(_,i)=>({date:day(i),value:60+i*.03+2*Math.sin(i*2*Math.PI/7),metric:'Synthetic resting HR',unit:'bpm',source:'synthetic',deviceId:'demo'}))};
  if(operation==='features')return {...base,export:{consent:{at:day(100),purpose:'Synthetic demonstration'},rows:Array.from({length:60},(_,i)=>({participantId:'synthetic-person',date:day(i),type:'vital',metric:'Resting HR',unit:'bpm',value:60+i*.1,source:'synthetic',deviceId:'demo'}))}};
  if(operation==='change-points')return {...base,values:Array.from({length:90},(_,i)=>i<45?60:70)};
  if(operation==='autoencoder'||operation==='isolation')return {...base,baseline:Array.from({length:60},(_,i)=>[Math.sin(i),Math.cos(i)]),current:[[4,5]]};
  const rows=Array.from({length:12*120},(_,i)=>{const value=Math.sin(i*1.7);return operation==='train'?{participantId:`synthetic-${Math.floor(i/120)}`,date:day(i%120),signal:value,label:value>0?1:0}:{participantId:`synthetic-${Math.floor(i/120)}`,date:day(i%120+7),windowEnd:day(i%120+6),values:Array.from({length:7},()=>[value]),label:value>0?1:0};});
  return {...base,model:operation==='train'?'logistic':'aeon-forest',features:['signal'],outcomeDefinition:'Synthetic outcome copied from the input signal; demonstrates execution only',horizonDays:3,epochs:5,explain:operation==='train',rows};
}

export function ResearchWorkbench(){
  const [operation,setOperation]=useState<string>('forecast'),[payload,setPayload]=useState(''),[purpose,setPurpose]=useState(''),[consent,setConsent]=useState(false),[track,setTrack]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Record<string,unknown>|null>(null);
  const loadExample=()=>{setPayload(JSON.stringify(example(operation),null,2));setPurpose('Synthetic workflow demonstration');setResult(null);setConsent(false);};
  const run=async()=>{setBusy(true);setError('');setResult(null);try{const input=researchWorkbenchSchema.parse({...JSON.parse(payload),operation,consent,purpose,track});const response=await post<{ok:boolean;result:Record<string,unknown>}>('/api/medical/research/workbench',input);setResult(response.result);setConsent(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className="stack" aria-label="Research workbench"><h3>Research workbench</h3><p>Run local data preparation, metric forecasts and model evaluations. Synthetic examples demonstrate execution; their results do not establish medical accuracy. Consented inputs are queued privately in Supabase, processed by your personal worker, and results return to your account. Local experiment records remain on your computer.</p>
    <label>Workflow<select className="input" value={operation} disabled={busy} onChange={e=>{setOperation(e.target.value);setPayload('');setResult(null);setConsent(false);}}>{operations.map(v=><option key={v}>{v}</option>)}</select></label>
    <div className="row wrap"><button className="btn btn-soft" disabled={busy} onClick={loadExample}>Load synthetic example</button><label>Load research JSON<input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>4_000_000){setError('Maximum dataset size is 4 MB.');return;}setPayload(await file.text());setConsent(false);setResult(null);}}/></label><button className="btn btn-soft" onClick={()=>void get<unknown>('/api/medical/research/notebook').then(notebook=>downloadArtifact('medical-workbench.ipynb',JSON.stringify(notebook,null,2),'application/x-ipynb+json')).catch(e=>setError(e.message))}>Download runnable notebook</button></div>
    <p className="subtle">Forecast: one metric, unit, source and device with consecutive measured daily rows. Train: explicitly labeled participant/day rows. Sequence: 7–28 measured days ending before prediction; models: aeon-forest, cnn, gru, lstm, transformer. Change the model field in the JSON to compare algorithms. Features accepts a consented export inside the export field. Missing values are never silently treated as healthy outcomes.</p>
    <label>Dataset and model settings<textarea className="input" rows={10} value={payload} disabled={busy} onChange={e=>{setPayload(e.target.value);setConsent(false);}}/></label>
    <label>Research purpose<input className="input" value={purpose} maxLength={500} disabled={busy} onChange={e=>{setPurpose(e.target.value);setConsent(false);}}/></label>
    <label><input type="checkbox" checked={track} disabled={busy} onChange={e=>{setTrack(e.target.checked);setConsent(false);}}/>Track aggregate metrics and library versions in local MLflow</label>
    <label><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>I consent to privately storing this dataset temporarily in my Supabase account and processing it on my personal worker for the stated research purpose.</label>
    <button className="btn btn-hot" disabled={busy||!consent||purpose.trim().length<3||!payload} onClick={()=>void run()}>{busy?'Running local workflow…':'Run research workflow'}</button>
    {error&&<p role="alert">{error}</p>}{result&&<article className="stack"><h4>Research result</h4><div className="overview-signals">{Object.entries(result).filter(([,v])=>typeof v==='number').map(([key,value])=><div className="card" key={key}><strong>{Number(value).toLocaleString(undefined,{maximumFractionDigits:4})}</strong><p>{key}</p></div>)}</div>{Array.isArray(result.forecast)&&<div style={{overflowX:'auto'}}><table><thead><tr><th>Date</th><th>Seasonal baseline</th><th>Autoregression</th></tr></thead><tbody>{(result.forecast as Record<string,unknown>[]).map(row=><tr key={String(row.date)}><td>{String(row.date).slice(0,10)}</td><td>{Number(row['seasonal-naive']).toFixed(2)}</td><td>{Number(row.autoregression).toFixed(2)}</td></tr>)}</tbody></table></div>}<p>{String(result.limitations||'Research only; no diagnosis.')}</p><button className="btn btn-soft" onClick={()=>downloadArtifact(`research-${result.runId}.json`,JSON.stringify(result,null,2))}>Download result and provenance</button><details><summary>Evaluation, model settings and library versions</summary><pre className="bio-json">{JSON.stringify(result,null,2)}</pre></details></article>}
  </section>;
}
