import { useState } from 'react';
import { StatePanel } from './DesignSystem';
export function SignalChart({points,label,unit='',height=140,variant='line'}:{points:{date:string;value:number|null}[];label:string;unit?:string;height?:number;variant?:'line'|'area'|'bar'}){
  const signalColor = /sleep|bedtime|wake/i.test(label) ? 'var(--sleep)' : /water|hydrat/i.test(label) ? 'var(--water)' : /calori|protein|carb|fat|nutrition/i.test(label) ? 'var(--eat)' : /heart|hrv|resting hr|blood pressure/i.test(label) ? 'var(--health)' : /weight|waist|body/i.test(label) ? 'var(--body)' : /volume|sets|training|strength/i.test(label) ? 'var(--train)' : /readiness|energy|stress|soreness|recovery/i.test(label) ? 'var(--recover)' : 'var(--domain-color)';
  const [selected,setSelected]=useState<number|null>(null),valid=points.map((p,i)=>({...p,index:i})).filter((p):p is typeof p&{value:number}=>p.value!==null&&Number.isFinite(p.value));
  if(!valid.length)return <StatePanel state="no-data" title={`No ${label.toLowerCase()} data yet`} body={`Record ${label.toLowerCase()} to build this trend. Missing days stay missing.`}/>;
  const lo=Math.min(...valid.map(p=>p.value)),hi=Math.max(...valid.map(p=>p.value)),margin=(hi-lo)*.1||Math.max(Math.abs(lo)*.05,1),min=variant==='bar'?Math.min(0,lo-margin):lo-margin,max=hi+margin,range=max-min,width=600,pad=40;
  const x=(i:number)=>pad+i/Math.max(points.length-1,1)*(width-pad*2),y=(v:number)=>height-pad-(v-min)/range*(height-pad*2);
  const segments:typeof valid[]=[];
  for(const point of valid){const previous=segments.at(-1);if(previous&&previous.at(-1)!.index===point.index-1)previous.push(point);else segments.push([point]);}
  const areas=segments.map(group=>`M${x(group[0].index)},${height-pad} ${group.map(point=>`L${x(point.index)},${y(point.value)}`).join(' ')} L${x(group.at(-1)!.index)},${height-pad} Z`);
  const path=valid.map((p,i)=>`${i&&p.index===valid[i-1].index+1?'L':'M'}${x(p.index)},${y(p.value)}`).join(' '),active=selected!==null?points[selected]:null;
  return <div className="signal-chart" style={{color:signalColor}}><div className="signal-chart-readout">{active&&active.value!==null?<><strong>{active.value.toLocaleString(undefined,{maximumFractionDigits:2})} {unit}</strong><span>{active.date}</span></>:<><strong>{label}{unit&&` · ${unit}`}</strong><span>{valid.length} observed days · select a point</span></>}</div><svg viewBox={`0 0 ${width} ${height}`} role="group" aria-label={`${label} across ${valid.length} days`}><defs><linearGradient id={`signal-${label.replace(/\W/g,'')}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".2"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><g className="signal-chart-grid">{[min,(min+max)/2,max].map(v=><g key={v}><line x1={pad} x2={width-pad} y1={y(v)} y2={y(v)}/><text x={pad-6} y={y(v)+3} textAnchor="end">{v.toLocaleString(undefined,{maximumFractionDigits:1})}</text></g>)}</g>{variant==='area'&&areas.map((area,index)=><path key={index} d={area} fill="currentColor" opacity=".14"/>)}{variant==='bar'&&valid.map(point=><rect key={point.date} x={x(point.index)-Math.min(14,(width-pad*2)/Math.max(1,points.length)*.6)/2} y={y(point.value)} width={Math.min(14,(width-pad*2)/Math.max(1,points.length)*.6)} height={Math.max(2,height-pad-y(point.value))} rx="3" fill="currentColor"/>)}<path d={variant==='bar'?'':path} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{valid.map(p=><g key={p.date}><circle cx={x(p.index)} cy={y(p.value)} r={selected===p.index?5:3} fill="currentColor"/><circle cx={x(p.index)} cy={y(p.value)} r="13" fill="transparent" tabIndex={0} role="button" aria-label={`${p.date}: ${p.value} ${unit}`} onMouseEnter={()=>setSelected(p.index)} onFocus={()=>setSelected(p.index)} onClick={()=>setSelected(p.index)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(p.index);}}}><title>{p.date}: {p.value} {unit}</title></circle></g>)}</svg><div className="signal-chart-axis"><span>{points[0]?.date}</span><span>{points.at(-1)?.date}</span></div><details className="signal-data-table"><summary>View {label.toLowerCase()} as a table</summary><p>{valid.length} recorded values. First: {valid[0].value} {unit}. Latest: {valid.at(-1)!.value} {unit}. Missing dates remain missing.</p><table><caption>{label}{unit ? ` (${unit})` : ""}</caption><thead><tr><th scope="col">Date</th><th scope="col">Value</th></tr></thead><tbody>{points.map((point,index)=><tr key={`${point.date}-${index}`}><th scope="row">{point.date}</th><td>{point.value == null ? "Not recorded" : `${point.value} ${unit}`}</td></tr>)}</tbody></table></details></div>;
}
