import { useMemo, useState } from 'react';
import { adaptTrainingSession } from '../../shared/training-adaptation';
import type { Exercise, PlannedExercise } from '../../shared/types';

export function TrainingAdaptation({original,library,reduced,onUse}:{original:PlannedExercise[];library:Exercise[];reduced:boolean;onUse:(exercises:PlannedExercise[])=>void}) {
  const [minutes,setMinutes]=useState(''),[equipment,setEquipment]=useState(''),[regions,setRegions]=useState(''),[lighter,setLighter]=useState(reduced);
  const valid=!minutes||Number(minutes)>=5&&Number(minutes)<=240;
  const proposal=useMemo(()=>valid?adaptTrainingSession(original,library,{minutes:minutes?Number(minutes):undefined,equipment:equipment.split(',').filter(Boolean),soreRegions:regions.split(',').filter(Boolean),recoveryReduced:lighter}):null,[original,library,minutes,equipment,regions,lighter,valid]);
  return <details className="glass card" aria-label="Session adaptation"><summary>Adapt this session to today</summary><div className="stack"><p className="subtle">Preview a change for this session. Choose the original plan whenever you prefer.</p><div className="flow-field-grid"><label>Available minutes<input className="input" type="number" min={5} max={240} value={minutes} onChange={event=>setMinutes(event.target.value)} placeholder="No limit"/></label><label>Available equipment<input className="input" value={equipment} onChange={event=>setEquipment(event.target.value)} placeholder="All, or comma-separated names"/></label><label>Sore muscle regions<input className="input" value={regions} onChange={event=>setRegions(event.target.value)} placeholder="e.g. shoulders, quads"/></label><label><input type="checkbox" checked={lighter} onChange={event=>setLighter(event.target.checked)}/> Lighter volume & intensity</label></div>{!valid&&<p role="alert">Choose 5–240 available minutes.</p>}{proposal&&<><p>Estimated {proposal.estimatedMinutes} min · {proposal.proposed.length} exercises</p>{proposal.proposed.map((exercise,index)=><div className="flow-management-row" key={`${exercise.name}-${index}`}><strong>{exercise.name}</strong><span>{exercise.vol} · target RIR {exercise.rirTarget??'as prescribed'}</span></div>)}<details><summary>Changes & limitations</summary>{[...proposal.changes,...proposal.warnings,...proposal.limitations].map(message=><p key={message}>{message}</p>)}</details><button className="btn btn-soft" disabled={!proposal.proposed.length} onClick={()=>onUse(proposal.proposed)}>Use this session proposal</button></>}</div></details>;
}
