import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import {setup} from './cloud-fixture';
const instrumentation=fs.readFileSync('node_modules/web-vitals/dist/web-vitals.iife.js','utf8')+`;window.__uxVitals={};for(const [name,hook] of [['LCP',webVitals.onLCP],['CLS',webVitals.onCLS],['INP',webVitals.onINP]])hook(metric=>{window.__uxVitals[name]=metric.value;if(name==='LCP'){const entry=metric.entries.at(-1);window.__uxLcpPaint={tag:entry?.element?.tagName||null,classes:typeof entry?.element?.className==='string'?entry.element.className:null,loadMs:entry?.loadTime||0,renderMs:entry?.renderTime||0};}},{reportAllChanges:true});`;
const diagnostic=process.env.HEALTH_OS_PROFILE?`;window.__uxDiagnostic={frames:[],events:[]};new PerformanceObserver(list=>{for(const e of list.getEntries())window.__uxDiagnostic.frames.push({start:e.startTime,duration:e.duration,blocking:e.blockingDuration,renderStart:e.renderStart,styleStart:e.styleAndLayoutStart,scripts:e.scripts?.map(s=>({duration:s.duration,forcedStyle:s.forcedStyleAndLayoutDuration,source:s.sourceURL?.split('/').at(-1),function:s.sourceFunctionName,invoker:s.invokerType}))});}).observe({type:'long-animation-frame',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.interactionId)window.__uxDiagnostic.events.push({name:e.name,start:e.startTime,duration:e.duration,inputDelay:e.processingStart-e.startTime,processing:e.processingEnd-e.processingStart,presentation:e.startTime+e.duration-e.processingEnd});}).observe({type:'event',buffered:true,durationThreshold:16});`:'';
for(const profile of [{name:'desktop',width:1440,cpu:1},{name:'mobile-throttled',width:390,cpu:4}])test(`production lab ${profile.name}`,async({page})=>{
  const samples=[];await setup(page);await page.addInitScript({content:instrumentation+diagnostic});for(let run=0;run<3;run++){
    await page.setViewportSize({width:profile.width,height:900});
    const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});
    if(profile.cpu>1){await cdp.send('Emulation.setCPUThrottlingRate',{rate:profile.cpu});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:80,downloadThroughput:1_600_000/8,uploadThroughput:750_000/8});}
    await page.goto('/?ux-lab='+run+'#Today');await expect(page.getByRole('button',{name:'Customize Today',exact:true})).toBeVisible({timeout:60000});
    await page.getByRole('button',{name:'Customize Today',exact:true}).click();await expect(page.getByRole('dialog',{name:'Make Health OS yours'})).toBeVisible();await page.keyboard.press('Escape');
    await expect.poll(()=>page.evaluate(()=>(window as any).__uxVitals.INP),{timeout:15000}).not.toBeUndefined();
    if(diagnostic)await page.waitForTimeout(1000);
    const sample=await page.evaluate(()=>({metrics:(window as any).__uxVitals,paint:(window as any).__uxLcpPaint,diagnostic:(window as any).__uxDiagnostic,assets:performance.getEntriesByType('resource').filter((entry:any)=>new URL(entry.name).origin===location.origin&&/\.(js|mjs|css)(?:\?|$)/.test(entry.name)).map((entry:any)=>({name:entry.name.split('/').at(-1),transferBytes:entry.transferSize,durationMs:entry.duration}))}));samples.push(sample);await cdp.detach();
  }
  const report={profile,samples,targets:{LCP:2500,INP:200,CLS:.1},notes:['Three synthetic HTTP cold-load navigations; account data caches persist across the repeat visits. These are not production population percentiles.','Cloud responses and Google Fonts are stubbed; remote API and real font-loading latency are not measured.','No health values, page paths or free text are included.']};fs.mkdirSync('outputs/ux-acceptance',{recursive:true});fs.writeFileSync(`outputs/ux-acceptance/performance-${profile.name}.json`,JSON.stringify(report,null,2));console.log(profile.name,JSON.stringify(samples.map(s=>s.metrics)));
});
