import { test } from 'node:test';
import assert from 'node:assert/strict';
import { bioSchema, nutrition, preferredVitals, baseline, correlation, readiness, experimentResult, type BioRecord } from './biology.js';
function record(patch: Partial<BioRecord> = {}): BioRecord { return bioSchema.parse({id:crypto.randomUUID(),userId:'local-user',domain:'Health',type:'vital',name:'Reading',timestamp:'2026-09-30T10:00:00Z',value:50,unit:'ms',source:'Watch A',deviceId:'web',quality:'measured',syncState:'saved',revision:1,createdAt:'2026-09-30T10:00:00Z',updatedAt:'2026-09-30T10:00:00Z',metadata:{metric:'HRV'},...patch}); }
test('missing readiness remains unknown rather than fabricated',()=>{const result=readiness([],'2026-09-30');assert.equal(result.score,null);assert.equal(result.confidence,'Unavailable');assert.equal(result.missing.length,6);});
test('nutrition excludes deleted records and preserves optional nutrient missingness',()=>{const a=record({type:'meal',domain:'Eat',metadata:{calories:500,protein:30}});const b=record({type:'meal',domain:'Eat',metadata:{calories:600},deletedAt:'2026-09-30T11:00:00Z'});assert.equal(nutrition([a,b],'2026-09-30').calories,500);assert.equal(a.metadata.iron,undefined);});
test('source priority selects one device per day without summing overlapping measurements',()=>{const a=record({source:'Watch A',value:50}),b=record({source:'Watch B',value:90});const priority=record({type:'sourcePriority',name:'HRV',metadata:{sources:'Watch B, Watch A'}});assert.deepEqual(preferredVitals([a,b,priority],'HRV').map(r=>r.value),[90]);});
test('a manual correction preserves the imported vital and undo restores its preferred value',()=>{const original=record({id:'imported-vital',quality:'imported',value:50});const correction=record({id:'correction:imported-vital',value:60,source:'Manual correction',metadata:{metric:'HRV',correctionOf:original.id}});assert.deepEqual(preferredVitals([original,correction],'HRV').map(r=>r.value),[60]);assert.equal(original.value,50);assert.deepEqual(preferredVitals([original,{...correction,deletedAt:'2026-09-30T11:00:00Z'}],'HRV').map(r=>r.value),[50]);});
test('baseline excludes today and requires sufficient history for anomaly flags',()=>{const history=Array.from({length:15},(_,i)=>record({timestamp:`2026-09-${String(i+10).padStart(2,'0')}T10:00:00Z`,value:50+i%2}));const result=baseline([...history,record({value:80})],'HRV','2026-09-30');assert.equal(result.samples,15);assert.ok(result.average!<51);assert.equal(result.anomalous,true);});
test('constant correlation data yields unknown instead of NaN or causality',()=>{const r=correlation(Array.from({length:8},(_,i)=>({date:String(i),x:1,y:i})));assert.equal(r.r,null);assert.equal(correlation([{date:'a',x:1,y:2}]).confidence,'Insufficient data');});
test('experiments separate baseline and intervention dates and do not count duplicate days',()=>{const e=record({type:'experiment',metadata:{start:'2026-09-20',baselineDays:14,days:21,metric:'Sleep'}});const data=[record({type:'sleep',value:7,unit:'hours',timestamp:'2026-09-19T10:00:00Z'}),record({type:'sleep',value:8,unit:'hours',timestamp:'2026-09-20T10:00:00Z'})];const r=experimentResult(e,data);assert.equal(r.before,7);assert.equal(r.during,8);assert.equal(r.difference,1);assert.equal(r.confidence,'Insufficient data');});
test('schema rejects invalid hydration, reversed intervals and negative macros',()=>{assert.throws(()=>record({type:'water',value:-1}));assert.throws(()=>record({endTime:'2026-09-29T10:00:00Z'}));assert.throws(()=>record({metadata:{protein:-10}}));});
