import assert from 'node:assert/strict';
import test from 'node:test';
import { labSchema, parseReportText, normalizeLab, rangeFlag, reportBundle, labTrends, type MedicalReport } from './medical.js';
import { calculateMedical, physiologicalSignals, statistics, evidenceCards } from './medical-intelligence.js';
import { bioSchema } from './biology.js';
const date='2026-09-30T10:00:00Z';
const lab=(extra:Record<string,unknown>={})=>labSchema.parse({id:'hb',name:'Hemoglobin',loinc:'718-7',value:118,unit:'g/L',referenceLow:130,referenceHigh:170,collectedAt:date,...extra});
const report=(extra:Partial<MedicalReport>={}):MedicalReport=>({id:'test-report',title:'CBC',category:'laboratory',status:'reviewed',revision:1,createdAt:date,collectedAt:date,laboratory:'Local lab',narrative:'',results:[lab()],warnings:[],original:{name:'cbc.txt',mime:'text/plain',sha256:'a',size:1},...extra});
test('lab conversion preserves comparable ranges and leaves unknown intervals unknown',()=>{const n=normalizeLab(lab());assert.equal(n.value,11.8);assert.equal(n.referenceLow,13);assert.equal(rangeFlag(n),'low');assert.equal(rangeFlag(lab({referenceLow:undefined,referenceHigh:undefined})),'unknown');assert.equal(rangeFlag(lab({comparator:'<'})),'unknown');assert.equal(rangeFlag(lab({referenceLow:undefined,value:140})),'unknown');assert.equal(normalizeLab(lab({loinc:undefined})).unit,'g/L');});
test('conservative extraction retains unsupported text and source ranges',()=>{const result=parseReportText('Hemoglobin 11.8 g/dL 13.0-17.0\nFerritin <5 ng/mL 20-250\nNo diagnosis here\nUnknown 42 mmol/L',date);assert.equal(result.results.length,2);assert.equal(result.results[0].referenceLow,13);assert.equal(result.results[1].comparator,'<');assert.equal(rangeFlag(result.results[1]),'unknown');assert.match(result.warnings[0],/2 lines/);});
test('trend engine excludes drafts, comparator values and incompatible methods',()=>{const rows=labTrends([report(),report({id:'earlier',results:[lab({value:140,collectedAt:'2026-08-01T10:00:00Z'})]}),report({id:'draft',status:'draft',results:[lab({value:20})]}),report({id:'other-assay',results:[lab({method:'alternative',value:20})]})]);assert.equal(rows.length,2);assert.equal(rows[0].direction,'declining');assert.equal(rows[0].points.length,2);assert.ok(Math.abs(rows[0].change+2.2)<1e-10);});
test('FHIR export connects individual observations to the diagnostic report',()=>{const b=reportBundle(report());assert.equal(b.resourceType,'Bundle');const diagnostic=b.entry!.find(e=>e.resource?.resourceType==='DiagnosticReport')!.resource;assert.equal(diagnostic?.resourceType,'DiagnosticReport');if(diagnostic?.resourceType==='DiagnosticReport')assert.equal(diagnostic.result?.length,1);const o=b.entry!.find(e=>e.resource?.resourceType==='Observation')!.resource;if(o?.resourceType==='Observation'){assert.equal(o.valueQuantity?.value,118);assert.equal(o.referenceRange?.[0].low?.value,130);assert.equal(o.valueQuantity?.system,'http://unitsofmeasure.org');}});
test('FHIR draft observations and diagnostic report remain preliminary',()=>{for(const state of ['draft','reviewed'] as const){const b=reportBundle(report({status:state}));const resources=b.entry!.map(e=>e.resource).filter(r=>r?.resourceType==='Observation'||r?.resourceType==='DiagnosticReport');assert.equal(resources.length,2);for(const r of resources)assert.equal(r?.status,state==='reviewed'?'final':'preliminary');}});
test('calculators enforce input requirements and published equations',()=>{assert.equal(calculateMedical({type:'BMI',age:30,weightKg:72,heightCm:180}).value,72/1.8**2);assert.ok(Math.abs(calculateMedical({type:'eGFR',age:50,sex:'male',creatinine:1,unit:'mg/dL'}).value-91.691)<.01);assert.equal(calculateMedical({type:'FIB-4',age:40,ast:30,alt:25,platelets:200}).value,1.2);assert.throws(()=>calculateMedical({type:'eGFR',age:16,sex:'male',creatinine:1,unit:'mg/dL'}));assert.throws(()=>calculateMedical({type:'FIB-4',age:40,ast:30,alt:25,platelets:0}));});
function vital(day:number,value:number,source='watch'){const timestamp=new Date(Date.UTC(2026,8,day,8)).toISOString();return bioSchema.parse({id:`v-${day}`,userId:'local',domain:'Health',type:'vital',timestamp,name:'RHR',value,unit:'bpm',source,deviceId:source,createdAt:timestamp,updatedAt:timestamp,quality:'measured',syncState:'saved',revision:1,metadata:{metric:'Resting HR'}});}
test('robust baseline excludes present and future readings and refuses source mixing',()=>{const rows=Array.from({length:28},(_,i)=>vital(i+1,60));rows.push(vital(29,75),vital(30,120));const s=physiologicalSignals(rows,'2026-09-29').signals[0];assert.equal(s.windows[2].samples,28);assert.equal(s.windows[2].median,60);assert.equal(s.delta,15);assert.equal(s.unusual,true);assert.equal(physiologicalSignals([...rows.filter(r=>r.id!=='v-29'),vital(29,75,'new-watch')],'2026-09-29').signals[0].robustZ,null);assert.equal(statistics([]).median,null);});
test('explicit severe breathing symptom creates urgent guidance; resolved symptoms do not',()=>{const base=vital(30,60);const symptom=bioSchema.parse({...base,type:'symptom',name:'Breathing difficulty',metadata:{emergencyBreathing:true,status:'Active'}});assert.equal(evidenceCards([], [symptom],'2026-09-30')[0].urgency,'urgent');assert.equal(evidenceCards([], [{...symptom,metadata:{...symptom.metadata,status:'Resolved'}}],'2026-09-30').length,0);});

test('vitamin D coding preserves total versus D3 identity and leaves a vague label unmapped',()=>{const results=parseReportText('Vitamin D 18 ng/mL 20-50\n25-OH Vitamin D 22 ng/mL 20-50\n25-OH Vitamin D3 19 ng/mL 20-50',date).results;assert.equal(results[0].loinc,undefined);assert.equal(results[1].loinc,'62292-8');assert.equal(results[2].loinc,'1989-3');});
