import type { AppDb, Session } from './types.js';
import { computeMetrics } from './metrics.js';
import { formatWorkoutSet } from './workout-entry.js';
import { REPORT_LOGO_DATA_URI } from './report-logo.js';
export function escapeReportText(value:unknown):string{return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
function table(headers:string[],rows:unknown[][]){return `<table><thead><tr>${headers.map(h=>`<th>${escapeReportText(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${escapeReportText(value)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
export function reportHtml(data:AppDb,kind:'progress'|'session'|'week',id?:string):string {
  let sessions:Session[]=data.sessions.filter(s=>s.status==='finished'||s.status==='completed');
  if(kind==='session')sessions=sessions.filter(s=>s.id===id);
  if(kind==='week')sessions=sessions.filter(s=>s.weekId===id);
  if(kind!=='progress'&&!sessions.length)throw new Error('No completed sessions are available for this report.');
  const units=data.profile.units,metrics=computeMetrics({...data,sessions});
  const title=kind==='session'?sessions[0].dayTitle:kind==='week'?data.weeks.find(w=>w.id===id)?.name||'Week report':'Progress report';
  const summary=table(['Completed sessions',`Working volume (${units})`,'Average minutes'],[[metrics.totals.sessions,metrics.totals.tonnage.toFixed(1),metrics.totals.avgSessionMinutes||0]]);
  const details=sessions.map(s=>`<section><h2>${escapeReportText(s.date)} · ${escapeReportText(s.dayTitle)}</h2><p>${escapeReportText(s.notes)}</p><p>${escapeReportText(s.aiOverallSummary)}</p>${table(['Exercise','Status','Sets','Notes','Coach comment'],s.logs.map(log=>[log.name,log.status,log.sets.map(set=>formatWorkoutSet(set,units)).join('; '),log.journal||'',log.aiCoachComment||'']))}</section>`).join('');
  const strength=table(['Exercise',`Estimated 1RM (${units})`,'Date'],metrics.personalRecords.map(p=>[p.exercise,p.bestE1rm,p.date]));
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#202124;font-size:11px}.brand{display:flex;align-items:center;gap:12px;padding:0 0 17px;border-bottom:2px solid #806b40}.brand img{width:42px;height:42px;object-fit:contain}.eyebrow{margin:0;color:#806b40;font-size:9px;font-weight:800;letter-spacing:1.7px}.brand-name{margin:2px 0 0;font-size:18px;font-weight:900;letter-spacing:-.5px;color:#202124}h1{font-size:26px;margin:20px 0 5px;color:#202124;letter-spacing:-.7px}h2{font-size:15px;margin-top:24px;color:#202124;border-left:4px solid #c4ac7a;padding-left:8px}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{padding:8px;border:1px solid #e3e0d9;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#eeece7;color:#202124;font-weight:800}tbody tr:nth-child(even){background:#f7f6f3}tr{break-inside:avoid}thead{display:table-header-group}p{line-height:1.5}.muted{color:#686863}.meta{color:#686863;margin:0}.summary{background:linear-gradient(110deg,#eeece7,#f4eee1);border:1px solid #e3e0d9;border-radius:12px;padding:2px 14px;margin:18px 0}</style></head><body><header class="brand"><img src="${REPORT_LOGO_DATA_URI}" alt="Health OS logo"/><div><p class="eyebrow">YOUR HEALTH. YOUR PROGRESS.</p><p class="brand-name">Health OS</p></div></header><h1>${escapeReportText(title)}</h1><p class="meta">${escapeReportText(data.profile.displayName)} · Generated ${escapeReportText(new Date().toISOString())}</p><div class="summary">${summary}</div><h2>Strength estimates</h2>${strength}<p class="muted">Estimated strength is calculated from logged sets and is not a tested maximum. Missing records are not filled with assumed results.</p>${details}</body></html>`;
}
