import { createTimeoutSignal, normalizeCloudConfig, type CloudConfig } from './cloud.js';
export interface SupabaseAccountSession {uid:string;email:string;accessToken:string;refreshToken:string;expiresAt:number;config:CloudConfig;}
function message(data:any,fallback:string){return String(data?.msg||data?.error_description||data?.message||fallback);}
function sessionFrom(data:any,config:CloudConfig):SupabaseAccountSession{const user=data?.user;if(!data?.access_token||!data?.refresh_token||!user?.id)throw new Error('Supabase did not return an active session. Confirm the email address if required, then sign in.');return {uid:user.id,email:user.email||'',accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+Math.max(60,Number(data.expires_in||3600)-60)*1000,config:normalizeCloudConfig(config)};}
async function authRequest(config:CloudConfig,path:string,body:unknown){const safe=normalizeCloudConfig(config);const response=await fetch(`${safe.url}/auth/v1/${path}`,{method:'POST',headers:{apikey:safe.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body),signal:createTimeoutSignal(30000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(message(data,`Supabase account request failed (${response.status}).`)),{status:response.status,code:data.code||data.error_code});return {data,safe};}
export async function supabaseSignIn(config:CloudConfig,email:string,password:string){const {data,safe}=await authRequest(config,'token?grant_type=password',{email:email.trim(),password});return sessionFrom(data,safe);}
export async function supabaseSignUp(config:CloudConfig,email:string,password:string){const {data,safe}=await authRequest(config,'signup',{email:email.trim(),password});return sessionFrom(data,safe);}
export async function refreshSupabaseSession(session:SupabaseAccountSession){if(Date.now()<session.expiresAt)return session;const {data,safe}=await authRequest(session.config,'token?grant_type=refresh_token',{refresh_token:session.refreshToken});return sessionFrom(data,safe);}
export async function verifySupabaseSession(config:CloudConfig,accessToken:string){const safe=normalizeCloudConfig(config);const response=await fetch(`${safe.url}/auth/v1/user`,{headers:{apikey:safe.publishableKey,Authorization:`Bearer ${accessToken}`},signal:createTimeoutSignal(30000)});const data=await response.json().catch(()=>({}));if(!response.ok||!data?.id)throw new Error('Supabase could not verify this session. Sign in again.');return {uid:String(data.id),email:String(data.email||'')};}
