import type { BioDomain, BioKind } from '../../shared/biology';
export interface BioField { key: string; label: string; kind?: 'number' | 'date' | 'time' | 'text' | 'checkbox'; options?: string[]; required?: boolean; min?: number; max?: number; }
export interface BioForm { domain: BioDomain; title: string; unit?: string; fields: BioField[] }
const n = (key: string, label: string, min = 0, max = 100000): BioField => ({ key, label, kind: 'number', min, max });
const macros = [n('calories','Calories (kcal)'),n('protein','Protein (g)'),n('carbs','Carbohydrates (g)'),n('fat','Fat (g)'),n('fibre','Fibre (g)'),n('sodium','Sodium (mg)'),n('iron','Iron (mg)'),n('calcium','Calcium (mg)'),n('vitaminD','Vitamin D (µg)')];
export const bioForms: Record<BioKind, BioForm> = {
  meal: {domain:'Eat', title:'Meal',fields:[{key:'meal',label:'Meal',options:['Breakfast','Lunch','Snacks','Dinner']},...macros,{key:'completeDay',label:'This finishes a complete day of food logging',kind:'checkbox'}]},
  food: {domain:'Eat',title:'Food',fields:[n('serving','Serving size (g)'),...macros,{key:'barcode',label:'Barcode'},{key:'favorite',label:'Favorite',kind:'checkbox'}]},
  recipe: {domain:'Eat',title:'Recipe / saved meal',fields:[{key:'ingredients',label:'Ingredients & quantities'},n('servings','Servings',1),...macros,{key:'diet',label:'Diet',options:['Any','Vegetarian','Vegan']},{key:'allergens',label:'Allergens'},n('minutes','Preparation (minutes)'),{key:'cuisine',label:'Cuisine'}]},
  water: {domain:'Eat',title:'Water',unit:'mL',fields:[{...n('value','Amount (mL)',1,20000),required:true},{key:'beverage',label:'Beverage',options:['Water','Tea','Coffee','Other']}]},
  nutritionTarget: {domain:'Eat',title:'Nutrition targets',fields:[{key:'approach',label:'Approach',options:['Maintenance','Deficit','Surplus','Custom']},...macros,n('water','Water (mL)',100,10000),n('maintenance','Initial maintenance estimate (kcal)',500,7000)]},
  sleep: {domain:'Recover',title:'Sleep',unit:'hours',fields:[{...n('value','Sleep duration (hours)',0,24),required:true},{key:'bedtime',label:'Bedtime',kind:'time'},{key:'wake',label:'Wake time',kind:'time'},n('deep','Deep sleep (hours)',0,24),n('rem','REM sleep (hours)',0,24),n('quality','Perceived quality (1–10)',1,10),{key:'nap',label:'Nap',kind:'checkbox'}]},
  checkIn: {domain:'Recover',title:'Daily check-in',fields:[{...n('energy','Energy (1–10)',1,10),required:true},{...n('soreness','Soreness (1–10)',1,10),required:true},{...n('stress','Stress (1–10)',1,10),required:true},n('motivation','Motivation (1–10)',1,10),{key:'pain',label:'Pain affecting movement',kind:'checkbox'}]},
  vital: {domain:'Health',title:'Health reading',fields:[{key:'metric',label:'Metric',required:true,options:['HRV','Resting HR','Heart Rate','Steps','Active Calories','Blood Pressure Systolic','Blood Pressure Diastolic','Blood Glucose','Oxygen','Temperature','Respiration','Weight']},{...n('value','Measured value',0,200000),required:true},{key:'unit',label:'Unit',required:true},{key:'context',label:'Context (fasting, after meal, exercise…)'}]},
  symptom: {domain:'Health',title:'Symptom',fields:[{key:'concept',label:'Symptom concept',options:['Sore throat','Headache','Cough','Fatigue','Chills','Nausea','Diarrhea','Congestion','Muscle aches','Shortness of breath','Other']},{key:'snomedCode',label:'SNOMED CT code (if known)'},{key:'onset',label:'Onset date',kind:'date'},{key:'bodyArea',label:'Body area'},{key:'side',label:'Side',options:['Left','Right','Both']},{key:'context',label:'Context'},{key:'emergencyBreathing',label:'Severe difficulty breathing, gasping or unable to speak',kind:'checkbox'},n('severity','Severity (0–10)',0,10),{key:'associated',label:'Associated symptoms'},{key:'status',label:'Status',options:['Active','Resolved']}]},
  illness: {domain:'Health',title:'Illness event',fields:[{key:'start',label:'Started',kind:'date'},{key:'end',label:'Ended',kind:'date'},{key:'symptoms',label:'Symptoms'}]},
  supplement: {domain:'Health',title:'Supplement',fields:[n('serving','Serving'),{key:'unit',label:'Serving unit'},{key:'time',label:'Scheduled time',kind:'time'},{key:'food',label:'Food requirement'},{key:'start',label:'Start date',kind:'date'},{key:'end',label:'End date',kind:'date'},{key:'reason',label:'Reason'}]},
  medication: {domain:'Health',title:'Medication',fields:[{key:'ingredient',label:'Active ingredient'},{key:'allergies',label:'Recorded allergies'},{key:'status',label:'Status',options:['Active','Stopped']},{key:'dose',label:'Prescribed dose'},{key:'time',label:'Scheduled time',kind:'time'},{key:'frequency',label:'Frequency'},{key:'start',label:'Start date',kind:'date'},{key:'end',label:'End date',kind:'date'}]},
  dose: {domain:'Health',title:'Dose log',fields:[{key:'parentId',label:'Schedule record ID'},{key:'status',label:'State',options:['Taken','Skipped']}]},
  habit: {domain:'Today',title:'Habit',fields:[{key:'domain',label:'Domain',options:['Today','Train','Eat','Recover','Health','Body','Care']},{key:'time',label:'Reminder time',kind:'time'},n('target','Daily target',1,1000)]},
  habitDone: {domain:'Today',title:'Habit completion',fields:[{key:'parentId',label:'Habit ID'}]},
  experiment: {domain:'Insights',title:'Personal experiment',fields:[{key:'question',label:'Question / hypothesis',required:true},{key:'start',label:'Intervention start',kind:'date',required:true},n('baselineDays','Baseline days',7,365),n('days','Intervention days',7,365),{key:'metric',label:'Primary metric',options:['Sleep','HRV','Resting HR','Steps','Weight']},{key:'intervention',label:'What will you change?'},{key:'adherenceMetric',label:'Track adherence using',options:['None','Water','Protein']},n('target','Daily target (water in mL or protein in g)',0,20000),{key:'status',label:'Status',options:['Planned','Running','Completed']}]},
  researchConsent: {domain:'Insights',title:'Research preference',fields:[{key:'consent',label:'Include selected records in a local research export',kind:'checkbox'},{key:'domains',label:'Included domains (comma separated)'},{key:'purpose',label:'Purpose'},{key:'retention',label:'Retention / deletion plan'}]},
  sourcePriority: {domain:'Health',title:'Source priority',fields:[{key:'sources',label:'Sources in priority order (comma separated)',required:true}]},
  nudgePreference: {domain:'Today',title:'Nudge preferences',fields:[{key:'enabled',label:'Enable in-app nudges',kind:'checkbox'},n('dailyLimit','Daily limit',0,20),{key:'quietStart',label:'Quiet hours start',kind:'time'},{key:'quietEnd',label:'Quiet hours end',kind:'time'}]},
  recoveryNote: {domain:'Recover',title:'Recovery note',fields:[{key:'region',label:'Body area'},{key:'side',label:'Side',options:['Both','Left','Right']},n('severity','Severity (0–10)',0,10),{key:'trigger',label:'Trigger / affected movements'},{key:'status',label:'Status',options:['Active','Resolved']}]},
  mealPlan: {domain:'Eat',title:'Meal plan',fields:[{key:'date',label:'Planned date',kind:'date',required:true},{key:'meal',label:'Meal',options:['Breakfast','Lunch','Snacks','Dinner']},{key:'recipeId',label:'Recipe / food ID'},{key:'ingredients',label:'Shopping list'}]},
  goal: {domain:'Today',title:'Goal',fields:[{key:'metric',label:'Track',options:['Workouts','Weight','Protein','Calories','Sleep','Steps','Care adherence','Custom']},n('target','Target',.01),{key:'direction',label:'Direction',options:['Increase','Decrease']},n('windowDays','Average across days',1,90),{key:'deadline',label:'Target date',kind:'date'}]},
  goalCheckIn: {domain:'Today',title:'Goal check-in',fields:[{key:'parentId',label:'Goal'},n('value','Progress')]},
  automation: {domain:'Today',title:'Automation',fields:[{key:'trigger',label:'When',options:['time','afterWorkout','waterBelow','proteinBelow','bedtime']},{key:'time',label:'Time',kind:'time'},{key:'message',label:'Reminder'},{key:'enabled',label:'Enabled',kind:'checkbox'}]},
  automationEvent: {domain:'Today',title:'Reminder activity',fields:[{key:'status',label:'Status',options:['done','dismissed','snoozed','notified']}]},
  sleepPreference: {domain:'Recover',title:'Sleep schedule',fields:[n('target','Sleep target (hours)',1,16),{key:'bedtime',label:'Bedtime',kind:'time'},{key:'wake',label:'Wake time',kind:'time'}]},
  nutritionDay: {domain:'Eat',title:'Food day',fields:[{key:'complete',label:'Day complete',kind:'checkbox'}]},
  journal: {domain:'Today',title:'Reflection',fields:[{key:'wins',label:'Wins'},{key:'blockers',label:'Blockers'},{key:'adjustment',label:'Next adjustment'}]},
  environment: {domain:'Care',title:'Environment',fields:[n('humidity','Humidity (%)',0,100),n('temperature','Temperature (°C)',-30,60),{key:'climate',label:'Climate'}]},
  bodyMeasurement: {domain:'Body',title:'Measurement',fields:[{key:'metric',label:'Location'},n('value','Value'),{key:'unit',label:'Unit'}]},
  routine: {domain:'Today',title:'Routine',fields:[{key:'time',label:'Time',kind:'time'},{key:'actions',label:'Actions'}]},
};
