export const legacyViewIds: Record<string,string> = {
  "Today:overview": "001",
  "Timeline:overview": "002",
  "Targets:overview": "003",
  "Habits:overview": "004",
  "Nudges:overview": "005",
  "Habits:Weekly Review": "006",
  "Dashboard:overview": "007",
  "Tracker:overview": "008",
  "Dashboard:Flexible": "009",
  "Planner:overview": "010",
  "Programs:overview": "011",
  "Library:Splits": "012",
  "Calendar:overview": "013",
  "Library:Plans": "014",
  "Library:overview": "015",
  "Records:overview": "016",
  "ExerciseHistory:overview": "017",
  "Analyzer:PRs": "018",
  "Recover:Cardio": "019",
  "Coach:overview": "020",
  "Eat:overview": "021",
  "Eat:Food Diary": "022",
  "Eat:Search Food": "023",
  "Eat:Scan Barcode": "024",
  "Eat:Describe Meal": "025",
  "Eat:Snap Meal": "026",
  "Eat:Quick Add": "027",
  "Eat:My Foods": "028",
  "Eat:Saved Meals": "029",
  "Eat:Recipes": "030",
  "Eat:Favorites": "031",
  "Eat:Macros": "032",
  "Eat:Micronutrients": "033",
  "Eat:Water": "034",
  "Eat:Meal Planner": "035",
  "Eat:Targets": "036",
  "Eat:Adaptive TDEE": "037",
  "Recover:overview": "038",
  "Recover:Daily Check-in": "039",
  "Recover:Recovery Notes": "040",
  "Recover:Sleep": "041",
  "Recover:Pain & Injury": "042",
  "Recover:Readiness History": "043",
  "Recover:Training Load": "044",
  "Recover:Fatigue": "045",
  "Recover:Recovery Trends": "046",
  "Health:overview": "047",
  "Health:Heart": "048",
  "Health:Activity": "049",
  "Health:Blood Pressure": "050",
  "Health:Blood Glucose": "051",
  "Health:Oxygen": "052",
  "Health:Temperature": "053",
  "Health:Respiration": "054",
  "Health:Symptoms": "055",
  "Health:Illness Events": "056",
  "Health:Medications": "057",
  "Health:Supplements": "058",
  "Health:Manual Readings": "059",
  "Health:Connected Sources": "060",
  "Health:Source Priority": "061",
  "Health:Data Quality": "062",
  "Health:Medical Intelligence": "063",
  "Body:overview": "064",
  "Body:Weight": "065",
  "Body:Measurements": "066",
  "Body:Body Composition": "067",
  "Body:Measurement History": "068",
  "SkinOverview:overview": "069",
  "SkinProfile:overview": "070",
  "SkinGoals:overview": "071",
  "SkinRoutine:overview": "072",
  "SkinCheckIn:overview": "073",
  "SkinCalendar:overview": "074",
  "SkinProgress:overview": "075",
  "SkinProgress:Photos": "076",
  "SkinProducts:overview": "077",
  "SkinAi:Research": "078",
  "SkinAi:overview": "079",
  "SkinReviews:overview": "080",
  "Insights:overview": "081",
  "Analyzer:overview": "082",
  "Insights:Analytics Nutrition": "083",
  "Insights:Analytics Recovery": "084",
  "Insights:Analytics Sleep": "085",
  "Insights:Analytics Body": "086",
  "Insights:Analytics Care": "087",
  "Insights:Trends": "088",
  "Insights:Personal Baselines": "089",
  "Insights:Correlations": "090",
  "Insights:Anomalies": "091",
  "Experiments:overview": "092",
  "BodyCoach:overview": "093",
  "Reports:overview": "094",
  "Reports:Workout Reports": "095",
  "Research:overview": "096",
  "Search:overview": "097",
  "Sync:overview": "098",
  "Settings:overview": "099",
  "Permissions:overview": "100",
  "Profile:overview": "101"
};
