import type { HealthAppointment } from '../../shared/appointments';
import type { BioRecord } from '../../shared/biology';
import { labTrends, rangeFlag, type MedicalReport } from '../../shared/medical';
import { escapeHtml } from './health-os-export';
import type { DoctorQuestion, MedicalFollowUp, MedicalInboxItem } from '../../shared/medical-actions';
import type { physiologicalSignals } from '../../shared/medical-intelligence';

export interface DoctorSummary {warnings?:string[];appointment?:HealthAppointment;unreviewedReports?:{id:string;title:string;status:string}[];generatedAt:string;period:{from:string;to:string};reports:MedicalReport[];trends:ReturnType<typeof labTrends>;vitals:BioRecord[];symptoms:BioRecord[];illness:BioRecord[];medications:BioRecord[];notes:BioRecord[];limitations:string;medicalActions?:{followups?:MedicalFollowUp[];questions?:DoctorQuestion[];inbox?:MedicalInboxItem[];signals?:ReturnType<typeof physiologicalSignals>}}
export function doctorSummaryHtml(s:DoctorSummary){
  const esc=(v:unknown)=>escapeHtml(String(v??'—'));
  const table=(headings:string[],rows:unknown[][])=>rows.length?`<table><thead><tr>${headings.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p>No records in this period.</p>';
  const labs=s.reports.flatMap(report=>report.results.map(r=>[r.collectedAt.slice(0,10),r.name,`${r.comparator||''}${r.value??r.valueText??'—'} ${r.unit}`,r.referenceText||`${r.referenceLow??'—'} – ${r.referenceHigh??'—'} ${r.unit}`,rangeFlag(r),r.laboratory||report.laboratory]));
  const vitals=s.vitals.map(r=>[r.timestamp.slice(0,10),r.metadata.metric||r.name,`${r.value??'—'} ${r.unit}`,r.source,r.quality]);
  const symptoms=[...s.symptoms,...s.illness].map(r=>[r.timestamp.slice(0,10),r.metadata.concept||r.name,r.metadata.severity,r.metadata.status||r.metadata.end||'Not specified']);
  const medications=s.medications.map(r=>[r.timestamp.slice(0,10),r.name,r.metadata.ingredient||'',r.metadata.dose||r.metadata.serving||'',r.metadata.frequency||r.metadata.scheduledTime||'',r.metadata.status||'Not specified']);
  const actions=s.medicalActions;
  const appointmentHtml=s.appointment?`<h2>Appointment</h2><p>${esc(s.appointment.title)} · ${esc(s.appointment.scheduledAt)} · ${esc(s.appointment.timezone)}\n${esc(s.appointment.clinician)} · ${esc(s.appointment.location)}</p><h2>Reason for visit</h2><p>${esc(s.appointment.reason)}</p><h2>User-authored visit notes</h2><p>${esc(s.appointment.visitNotes)}</p><h2>Recorded next steps</h2><p>${esc(s.appointment.nextSteps)}</p>`:'';
  const unreviewedHtml=s.unreviewedReports?.length?`<h2>Unreviewed documents — excluded from reviewed results</h2>${table(['Document','Status'],s.unreviewedReports.map(report=>[report.title,report.status]))}`:'';
  const actionHtml=(actions?.followups?`<h2>Active follow-ups</h2>${table(['Follow-up','Due','Status','Provenance','Evidence available'],actions.followups.map(f=>[f.title,f.dueAt?.slice(0,10),f.status,f.provenance,f.sourceInvalid?'Source unavailable':'See local evidence']))}`:'')+(actions?.questions?`<h2>Questions for the next visit</h2>${table(['Question','Authorship'],actions.questions.map(q=>[q.text,q.source]))}`:'')+(actions?.inbox?`<h2>Medical evidence to review</h2>${table(['Item','Evidence summary'],actions.inbox.map(i=>[i.title,i.summary]))}`:'')+(actions?.signals?`<h2>Physiological changes (calculated)</h2><p>${esc(actions.signals.explanation)}</p>${table(['Metric','Recorded value','Prior median','Difference','Comparable prior days'],actions.signals.signals.filter(s=>s.unusual).map(s=>[s.metric,`${s.current} ${s.unit}`,s.windows[2].median,s.delta,s.windows[2].samples]))}`:'');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Health OS doctor summary</title><style>body{font:14px system-ui;color:#202020;max-width:1000px;margin:30px auto;padding:20px}h1,h2{color:#73310e}table{width:100%;border-collapse:collapse;margin:12px 0 24px}th,td{text-align:left;border-bottom:1px solid #ddd;padding:8px;overflow-wrap:anywhere}p{white-space:pre-wrap}tr{break-inside:avoid}@media print{body{margin:0;padding:0}h2{break-after:avoid}}</style></head><body><h1>Health OS — doctor summary</h1><p>${esc(s.period.from.slice(0,10))} to ${esc(s.period.to.slice(0,10))}</p><p>${esc(s.limitations)}</p>${appointmentHtml}${s.warnings?.length?`<h2>Selection needs review</h2>${s.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}`:''}${unreviewedHtml}${actionHtml}<h2>Important laboratory changes</h2>${table(['Test','Direction','Comparable measurements','Latest supplied-range comparison'],s.trends.map(t=>[t.name,t.direction,t.points.length,t.flag]))}<h2>Reviewed medical results</h2>${table(['Collected','Test','Result','Laboratory interval','Comparison','Laboratory'],labs)}<h2>Vitals</h2>${table(['Recorded','Metric','Result','Source','Quality'],vitals)}<h2>Symptoms and illness episodes</h2>${table(['Recorded','Reported symptom / episode','Severity (0–10)','Status'],symptoms)}<h2>Medication, supplements and dose logs</h2>${table(['Recorded','Name','Ingredient','Recorded dose','Schedule','Status'],medications)}<h2>Radiology and other report narratives</h2>${s.reports.filter(r=>r.category!=='laboratory').map(r=>`<h3>${esc(r.title)} · ${esc(r.collectedAt.slice(0,10))}</h3><p>${esc(r.narrative)}</p>`).join('')||'<p>No reports in this period.</p>'}<h2>Patient notes</h2>${s.notes.map(r=>`<p>${esc(r.timestamp.slice(0,10))} — ${esc(r.name)}\n${esc(r.metadata.notes||r.metadata.wins||'')}</p>`).join('')||'<p>No notes recorded.</p>'}<p>Generated ${esc(s.generatedAt)}. Original reports remain in your private Supabase library for verification.</p></body></html>`;
}
