import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
process.env.BODY_OS_DATA_DIR=mkdtempSync(path.join(tmpdir(),'body-os-catalog-test-'));
process.env.BODY_OS_BACKUP_DIR=path.join(process.env.BODY_OS_DATA_DIR,'backups');
const repo=await import('../db/repository.js');
const {migrate}=await import('../db/migrate.js');
const catalog=await import('./exercise-catalog.js');
import { ExerciseCatalogRepository, type CatalogExercise, type CatalogSnapshot } from '../../shared/global-exercises.js';
import type { Week } from '../../shared/types.js';
const row:CatalogExercise={id:'00000000-0000-4000-8000-000000000001',name:'Barbell Bench Press',normalized_name:'barbell bench press',slug:'bench',equipment:['barbell'],muscles:['Chest'],movement_pattern:'horizontal_press',body_part:'Chest',family_id:'bench',catalog_status:'active',source_payload:{legacyId:'builtin-v240-bench-press-1'},created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:00Z'};
const snapshot:CatalogSnapshot={full:true,syncedAt:row.updated_at,exercises:[row],aliases:[],media:[]};
const week:Week={id:'catalog-week',name:'Import',weekNumber:1,startDate:'',notes:'',active:false,days:[{key:'Mon',type:'push',title:'Push',subtitle:'',muscles:['Chest'],exercises:[{name:row.name,target:'Chest',vol:'3 x 8',cue:'Keep stable'}]}]};
test('catalog cache, unknown imports, media updates and user data preservation',async()=>{
 const {getDb}=await import('../db/connection.js');
 migrate(getDb());
 repo.saveExercise({id:'custom-curl',name:'My Curl',aliases:[],muscles:['Biceps'],equipment:'Dumbbell',movementPattern:'curl',substitutions:[],meta:{favorite:true}});
 repo.saveExercise({id:'builtin-v240-bench-press-1',name:'Legacy Bench',aliases:[],muscles:[],equipment:'',movementPattern:'',substitutions:[],meta:{favorite:true,notes:'Personal note'}});
 catalog.writeCatalogCache(snapshot);
 assert.equal(repo.listExercises().find(e=>e.id===row.id)?.meta?.favorite,true);
 assert.equal(repo.listExercises().find(e=>e.id==='custom-curl')?.meta?.favorite,true);
 repo.upsertWeek({...week,days:week.days.map(d=>({...d,exercises:d.exercises.map(e=>({...e,exerciseId:'builtin-v240-bench-press-1'}))}))});
 repo.saveSession({id:'catalog-history',status:'finished',date:'2026-09-01',createdAt:row.created_at,weekId:week.id,weekName:week.name,weekNumber:1,dayKey:'Mon',dayTitle:'Push',name:'User',sleep:'',soreness:'',logs:[{name:row.name,target:'Chest',exerciseId:'builtin-v240-bench-press-1',status:'completed',sets:[{s:1,w:40,r:8}]}]});
 const sets=structuredClone(repo.listSessions().find(s=>s.id==='catalog-history')!.logs[0].sets);
 catalog.migrateExerciseReferences();
 assert.equal(repo.getWeek(week.id)?.days[0].exercises[0].exerciseId,row.id);
 assert.equal(repo.listSessions().find(s=>s.id==='catalog-history')?.logs[0].exerciseId,row.id);
 assert.deepEqual(repo.listSessions().find(s=>s.id==='catalog-history')?.logs[0].sets,sets);
 const offline=await catalog.resolveWeekExercises(week);
 assert.equal(offline.days[0].exercises[0].exerciseId,row.id);
 const unknown={...week,days:[{...week.days[0],exercises:[{...week.days[0].exercises[0],name:'Bayesian Curl Variation'},{...week.days[0].exercises[0],name:'Bayesian Curl Variation'}]}]};
 let calls=0;
 const backend=new ExerciseCatalogRepository({url:'https://test.supabase.co',publishableKey:'public'},'user',async()=>{calls++;return new Response(JSON.stringify({status:'created',exerciseId:'00000000-0000-4000-8000-000000000002',exercise:{...row,id:'00000000-0000-4000-8000-000000000002',name:'Bayesian Curl Variation',source_payload:{}},matchMethod:'created',confidence:1}));});
 const created=await catalog.resolveWeekExercises(unknown,backend);
 assert.equal(calls,1);assert.equal(created.days[0].exercises[0].exerciseId,created.days[0].exercises[1].exerciseId);
 const failing=new ExerciseCatalogRepository({url:'https://test.supabase.co',publishableKey:'public'},'user',async()=>{throw new Error('Provider/network outage');});
 assert.equal((await catalog.resolveWeekExercises(unknown,failing)).days[0].exercises.length,2);
 const original=JSON.stringify(repo.getWeek(week.id));
 catalog.writeCatalogCache({...snapshot,full:false,syncedAt:'2026-09-02T00:00:00Z',media:[{id:'media',exercise_id:row.id,media_type:'animation',provider:'manual',provider_asset_id:null,url:'https://example.com/new.gif',embed_url:null,thumbnail_url:null,source_url:null,status:'verified',is_primary:true,match_method:null,match_confidence:null,inherited_from_exercise_id:null,metadata:{},created_at:row.created_at,updated_at:row.updated_at}]});
 assert.equal(repo.listExercises().find(e=>e.id===row.id)?.media?.[0].url,'https://example.com/new.gif');
 assert.equal(JSON.stringify(repo.getWeek(week.id)),original);
 repo.saveExercise({...repo.listExercises().find(e=>e.id===row.id)!,name:'Attempted global overwrite',meta:{favorite:true}});
 assert.equal(repo.listExercises().find(e=>e.id===row.id)?.name,row.name);
});
