import { useDraftFields } from '../lib/use-draft';
import { DraftFeedback } from '../components/DraftFeedback';
import { useState } from 'react';
import { useBiologicalData } from '../lib/use-biological-data';
import { useTimelineActions } from '../lib/use-timeline-actions';
import { useQuickLog } from '../components/QuickLog';
import { Modal } from '../components/Modal';
import { OSIcon } from '../components/OSIcon';
import { dateOf, type BioRecord } from '../../shared/biology';
import { evaluateNudges, reminderPreference, routineActions, type RoutineAction } from '../../shared/biological-automations';
import { careTasksForDate } from '../../shared/skin';

const actionNames:Record<string,string>={water:'Log water',meal:'Log a meal',checkIn:'Check in',sleep:'Log sleep',weight:'Weigh in',routine:'Start a routine',journal:'Reflect'};
export function RoutineCards({compact=false}:{compact?:boolean}){
  const {stored,app}=useBiologicalData(),actions=useTimelineActions(),[running,setRunning]=useState<BioRecord|null>(null),[selected,setSelected]=useState<number[]>([]);
  const routines=stored.filter(r=>r.type==='routine'),today=dateOf(new Date().toISOString());
  const label=(a:RoutineAction)=>a.type==='water'?`${a.amount} mL water`:a.type==='care'?app.skin.care.tasks.find(t=>t.id===a.recordId)?.label||'Care action':`${stored.find(r=>r.id===a.recordId)?.name||'Removed item'}${a.type==='meal'?` · ${a.servings} serving${a.servings===1?'':'s'}`:''}`;
  let items:RoutineAction[]=[];if(running)try{items=routineActions(running);}catch{items=[];}
  return <><div className={`routine-cards ${compact?'compact':''}`}>{routines.slice(0,compact?3:50).map(r=>{let count=0;try{count=routineActions(r).length;}catch{}const done=stored.some(s=>s.type==='automationEvent'&&s.metadata.parentId===r.id&&s.metadata.routine&&dateOf(s.timestamp)===today);return <button key={r.id} className={`routine-card glass ${done?'done':''}`} onClick={()=>{setRunning(r);try{setSelected(routineActions(r).map((_,i)=>i));}catch{setSelected([]);}}}><span className="routine-symbol">{done?'✓':'↗'}</span><strong>{r.name}</strong><small>{done?'Completed today':`${count} small actions · ${r.metadata.time||'Anytime'}`}</small></button>;})}{!routines.length&&<button className="routine-card glass" onClick={()=>app.setPage('Nudges')}><span className="routine-symbol">＋</span><strong>Make mornings easier</strong><small>Put your repeated actions into one routine.</small></button>}</div><Modal open={Boolean(running)} title={running?.name||''} onClose={()=>setRunning(null)} className="flow-modal"><p className="subtle">Select what you actually completed. A routine never records things on its own.</p><div className="routine-checklist">{items.map((a,i)=><label key={i}><input type="checkbox" checked={selected.includes(i)} onChange={e=>setSelected(values=>e.target.checked?[...values,i]:values.filter(v=>v!==i))}/><span>{label(a)}</span></label>)}</div><button className="btn btn-hot" disabled={!selected.length||Boolean(actions.busy)} onClick={()=>void actions.completeRoutine(running!,items.filter((_,i)=>selected.includes(i))).then(success=>{if(success)setRunning(null);})}>Log selected actions</button>{actions.error&&<p role="alert">{actions.error}</p>}</Modal></>;
}
export function AutomationsWorkspace(){
  const {app,bio,stored,records}=useBiologicalData(),actions=useTimelineActions(),quick=useQuickLog();
  const [tab,setTab]=useState('Your day'),[ruleEditor,setRuleEditor]=useState<BioRecord|'new'|null>(null),[routineEditor,setRoutineEditor]=useState<BioRecord|'new'|null>(null);
  const ruleDraft=useDraftFields('reminder:'+(typeof ruleEditor==='object'?ruleEditor?.id||'closed':ruleEditor),()=>{const r=typeof ruleEditor==='object'?ruleEditor:null;return {id:r?.id||crypto.randomUUID(),name:r?.name||'Water break',trigger:String(r?.metadata.trigger||'time'),time:String(r?.metadata.time||'09:00'),action:String(r?.metadata.action||'water'),message:String(r?.metadata.message||'A small pause to hydrate.'),threshold:Number(r?.metadata.threshold||1500),routineId:String(r?.metadata.routineId||'')};});
  const [name,setName]=ruleDraft.field('name'),[trigger,setTrigger]=ruleDraft.field('trigger'),[time,setTime]=ruleDraft.field('time'),[action,setAction]=ruleDraft.field('action'),[message,setMessage]=ruleDraft.field('message'),[threshold,setThreshold]=ruleDraft.field('threshold'),[routineId,setRoutineId]=ruleDraft.field('routineId');
  const routineDraft=useDraftFields('routine:'+(typeof routineEditor==='object'?routineEditor?.id||'closed':routineEditor),()=>{const r=typeof routineEditor==='object'?routineEditor:null;let items:RoutineAction[]=[];if(r)try{items=routineActions(r);}catch{}return {id:r?.id||crypto.randomUUID(),routineName:r?.name||'Morning rhythm',routineTime:String(r?.metadata.time||'08:00'),water:r?items.find(a=>a.type==='water')?.amount||0:350,selected:items.filter(a=>a.type!=='water').map(a=>`${a.type}:${a.recordId}`)};});
  const [routineName,setRoutineName]=routineDraft.field('routineName'),[routineTime,setRoutineTime]=routineDraft.field('routineTime'),[water,setWater]=routineDraft.field('water'),[selected,setSelected]=routineDraft.field('selected');
  const rules=stored.filter(r=>r.type==='automation'),pref=reminderPreference(stored);
  const today=dateOf(new Date().toISOString()),nudges=evaluateNudges(records,app.db!,app.skin);
  const savePref=(metadata:BioRecord['metadata'])=>actions.run('preferences',()=>bio.save({id:pref?.id&&pref.id!=='health-os-automation-settings'?pref.id:'nudge-preferences',type:'nudgePreference',domain:'Today',name:'Reminder preferences',metadata:{enabled:true,dailyLimit:3,quietStart:'22:00',quietEnd:'07:00',scheduled:true,contextual:true,system:true,insight:true,...pref?.metadata,...metadata}}));
  const beginRule=(r:BioRecord|'new')=>setRuleEditor(r);
  const beginRoutine=(r:BioRecord|'new')=>setRoutineEditor(r);
  const template=async(name:string,trigger:string,time:string,action:string,message:string)=>actions.run(name,()=>bio.save({type:'automation',domain:action==='water'||action==='meal'?'Eat':action==='sleep'||action==='checkIn'?'Recover':'Today',name,metadata:{trigger,time,action,message,enabled:true,threshold:action==='meal'?100:1500}}));
  return <div className="flow-workspace stack"><header className="bio-page-head"><p className="bio-eyebrow">A LIGHTER WAY TO KEEP UP</p><h1>Your day, on autopilot<span>.</span></h1><p className="subtle">Reminders find the right moment. You stay in charge of what gets logged.</p></header><div className="journey-segment" role="tablist" aria-label="Automation sections">{['Your day','Routines','Reminders','Preferences'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Your day'&&<><div className="flow-section-title"><h2>What matters next</h2><span className="subtle">{nudges.length} gentle prompts</span></div><div className="nudge-grid">{nudges.map(n=><article className="nudge-card glass" key={n.id}><OSIcon name={n.domain}/><span className="bio-eyebrow">{n.kind}</span><h3>{n.title}</h3><p>{n.reason}</p><div className="row"><button className="btn btn-hot" disabled={Boolean(actions.busy)} onClick={()=>{if(n.event)void actions.perform(n.event);else if(n.id.startsWith('water-'))quick.open('water');else if(n.id.startsWith('checkin-'))quick.open('checkIn');else app.setPage(n.page);}}>{n.event&&['medication','supplement'].includes(n.event.type)?'Taken':n.event?.type==='careTask'?'Complete':'Open action'}</button><button className="icon-btn" aria-label={`Snooze ${n.title}`} onClick={()=>void actions.dismiss(n.id,30)}>◷</button><button className="icon-btn" aria-label={`Dismiss ${n.title}`} onClick={()=>void actions.dismiss(n.id)}>×</button></div></article>)}</div>{!nudges.length&&<div className="journey-empty"><h3>A little breathing room</h3><p>There’s nothing due right now. Quiet hours and your preferences apply.</p></div>}<div className="flow-section-title"><h2>Your daily rhythms</h2><button className="btn btn-soft" onClick={()=>beginRoutine('new')}>＋ New routine</button></div><RoutineCards compact/><section className="glass card stack"><h3>Start with something useful</h3><div className="automation-templates"><button onClick={()=>void template('Hydration breaks','time','09:00','water','A water break between things.')}><span>◉</span><strong>Hydration breaks</strong><small>Daily · quick water logging</small></button><button onClick={()=>void template('After training','afterWorkout','17:00','meal','Review your next meal after training.')}><span>↗</span><strong>After your workout</strong><small>When a workout is completed</small></button><button onClick={()=>void template('Time to wind down','bedtime','21:00','sleep','Start your wind-down routine.')}><span>☾</span><strong>Evening wind-down</strong><small>Daily · a quieter evening</small></button></div></section></>}
    {tab==='Routines'&&<><div className="flow-section-title"><h2>Do the small things together</h2><button className="btn btn-hot" onClick={()=>beginRoutine('new')}>＋ Build a routine</button></div><RoutineCards/>{stored.filter(r=>r.type==='routine').map(r=><div className="flow-management-row" key={r.id}><strong>{r.name}</strong><button className="btn btn-soft" onClick={()=>beginRoutine(r)}>Edit routine</button><button className="btn btn-soft" onClick={()=>void actions.run(r.id,()=>bio.remove(r))}>Remove</button></div>)}</>}
    {tab==='Reminders'&&<><div className="flow-section-title"><h2>Set it once</h2><button className="btn btn-hot" onClick={()=>beginRule('new')}>＋ New reminder</button></div>{rules.map(r=><article key={r.id} className="automation-rule glass"><div className="routine-symbol">{r.metadata.enabled===false?'Ⅱ':'↗'}</div><div><strong>{r.name}</strong><p className="subtle">{r.metadata.trigger==='time'?`At ${r.metadata.time}`:r.metadata.trigger==='afterWorkout'?'After a completed workout':r.metadata.trigger==='waterBelow'?`When water is below ${r.metadata.threshold} mL`:r.metadata.trigger==='proteinBelow'?`When protein is below ${r.metadata.threshold} g`:`At wind-down time ${r.metadata.time}`} → {actionNames[String(r.metadata.action)]||'Reminder'}</p><small>{r.metadata.message}</small></div><div className="row"><button className="btn btn-soft" aria-label={`${r.metadata.enabled===false?'Enable':'Pause'} ${r.name}`} onClick={()=>void actions.run(r.id,()=>bio.save({...r,metadata:{...r.metadata,enabled:r.metadata.enabled===false}}))}>{r.metadata.enabled===false?'Enable':'Pause'}</button><button className="icon-btn" aria-label={`Edit ${r.name}`} onClick={()=>beginRule(r)}>✎</button><button className="icon-btn" aria-label={`Remove ${r.name}`} onClick={()=>void actions.run(r.id,()=>bio.remove(r))}>×</button></div></article>)}{!rules.length&&<p className="subtle">Create a reminder, or choose a starter from Your day.</p>}<p className="subtle">Reminders run while Health OS is open. Your data is recorded when you complete an action.</p></>}
    {tab==='Preferences'&&<section className="glass card stack"><h2>Keep it gentle</h2><label className="flow-toggle"><span><strong>In-app nudges</strong><small>Only show useful prompts.</small></span><input type="checkbox" checked={pref?.metadata.enabled!==false} onChange={e=>void savePref({enabled:e.target.checked})}/></label><div className="flow-field-grid"><label>Daily notification limit<select className="input" value={Number(pref?.metadata.dailyLimit??3)} onChange={e=>void savePref({dailyLimit:Number(e.target.value)})}>{[0,1,2,3,5,8].map(n=><option key={n}>{n}</option>)}</select></label><label>Quiet from<input className="input" type="time" value={String(pref?.metadata.quietStart||'22:00')} onChange={e=>void savePref({quietStart:e.target.value})}/></label><label>Quiet until<input className="input" type="time" value={String(pref?.metadata.quietEnd||'07:00')} onChange={e=>void savePref({quietEnd:e.target.value})}/></label></div>{[['scheduled','Scheduled reminders'],['contextual','Contextual nudges'],['system','Important system alerts'],['insight','Insights']].map(([key,label])=><label className="flow-toggle" key={key}><span>{label}</span><input type="checkbox" checked={pref?.metadata[key]!==false} onChange={e=>void savePref({[key]:e.target.checked})}/></label>)}<label className="flow-toggle"><span><strong>Browser notifications</strong><small>Optional, while the app is running.</small></span><input type="checkbox" checked={pref?.metadata.browserNotifications===true} onChange={async e=>{if(e.target.checked){if(!('Notification'in window)){app.setPage('Permissions');return;}const granted=await Notification.requestPermission();await savePref({browserNotifications:granted==='granted'});}else await savePref({browserNotifications:false});}}/></label><p className="subtle">Notifications use a generic prompt so health details stay inside the app.</p></section>}
    <Modal open={Boolean(ruleEditor)} title={ruleEditor==='new'?'A helpful reminder':'Edit reminder'} onClose={()=>setRuleEditor(null)} className="flow-modal"><form className="stack" onSubmit={e=>{e.preventDefault();void actions.run('rule-editor',async()=>{await bio.save({id:ruleDraft.value.id,type:'automation',domain:action==='meal'||action==='water'?'Eat':action==='sleep'||action==='checkIn'?'Recover':'Today',name,metadata:{trigger,time,action,message,threshold,routineId,enabled:true}});await ruleDraft.clear();setRuleEditor(null);});}}><DraftFeedback draft={ruleDraft}/><label>Name<input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label>When<select className="input" value={trigger} onChange={e=>setTrigger(e.target.value)}><option value="time">At a time each day</option><option value="afterWorkout">After a completed workout</option><option value="waterBelow">Water is behind target</option><option value="proteinBelow">Protein is behind target</option><option value="bedtime">Time to wind down</option></select></label>{trigger!=='afterWorkout'&&<label>Time<input className="input" type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label>}{['waterBelow','proteinBelow'].includes(trigger)&&<label>Below<input className="input" type="number" min="1" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label>}<label>Then<select className="input" value={action} onChange={e=>setAction(e.target.value)}>{Object.entries(actionNames).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{action==='routine'&&<label>Routine<select className="input" value={routineId} required onChange={e=>setRoutineId(e.target.value)}><option value="">Choose…</option>{stored.filter(r=>r.type==='routine').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}<label>Your reminder<input className="input" value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="btn btn-hot" disabled={!ruleDraft.ready||Boolean(actions.busy)}>Save reminder</button></form></Modal>
    <Modal open={Boolean(routineEditor)} title="Build your rhythm" onClose={()=>setRoutineEditor(null)} className="flow-modal"><form className="stack" onSubmit={e=>{e.preventDefault();void actions.run('routine-editor',async()=>{const id=routineDraft.value.id,items:RoutineAction[]=[];if(water>0)items.push({type:'water',amount:water});for(const selectedId of selected){const [type,...rest]=selectedId.split(':');const recordId=rest.join(':');items.push(type==='meal'?{type:'meal',recordId,servings:1}:{type:type as 'habit'|'care'|'dose',recordId});}if(!items.length)throw new Error('Choose at least one action.');await bio.saveMany([{id,type:'routine',domain:'Today',name:routineName,metadata:{time:routineTime,actions:JSON.stringify(items)}},{id:`routine-reminder-${id}`,type:'automation',domain:'Today',name:routineName,metadata:{time:routineTime,trigger:'time',action:'routine',routineId:id,enabled:true,message:'Your routine is ready.'}}]);await routineDraft.clear();setRoutineEditor(null);});}}><DraftFeedback draft={routineDraft}/><label>Call it<input className="input" required value={routineName} onChange={e=>setRoutineName(e.target.value)}/></label><label>Usual time<input className="input" type="time" value={routineTime} onChange={e=>setRoutineTime(e.target.value)}/></label><label>Water (mL, 0 to leave out)<input className="input" type="number" min="0" max="20000" value={water} onChange={e=>setWater(Number(e.target.value))}/></label><div className="routine-checklist">{[...stored.filter(r=>['habit','supplement','medication','food','recipe'].includes(r.type)).map(r=>({id:`${r.type==='habit'?'habit':['supplement','medication'].includes(r.type)?'dose':'meal'}:${r.id}`,name:r.name})),...careTasksForDate(app.skin.care,today,app.skin.products).map(t=>({id:`care:${t.id}`,name:t.label}))].map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(values=>e.target.checked?[...values,item.id]:values.filter(v=>v!==item.id))}/><span>{item.name}</span></label>)}</div><button className="btn btn-hot" disabled={!routineDraft.ready||Boolean(actions.busy)}>Save routine</button></form></Modal>{actions.error&&<p role="alert" className="bio-error">{actions.error}</p>}
  </div>;
}
