import { SignalChart } from '../components/SignalChart';
import { assistantEvidence, buildHealthIntelligence } from '../../shared/health-intelligence';
import { useCloudAccount } from '../state/CloudAccountContext';
import { EvidenceScatter } from '../components/VisualMetrics';
import { SearchWorkspace } from '../components/SearchWorkspace';
import { useDraftState } from '../lib/use-draft';
import { SaveStatus } from '../components/SaveStatus';
import { StatePanel } from '../components/DesignSystem';
import { MedicalIntelligence } from '../components/MedicalIntelligence';
import { confirmedDose, scheduledDoseTimes } from '../../shared/automation-rules';
import { stableRecordId } from '../../shared/automation-model';
import { AnalysisJobs } from '../components/AutomaticReview';
import { useAutomations } from '../state/AutomationContext';
import { Records } from './Records';
import { useMemo, useState, type ReactNode } from 'react';
import { useBiology } from '../state/BiologyContext';
import { useToast } from '../components/Toast';
import { Modal } from '../components/Modal';
import { CloudSyncPanel } from '../components/CloudSyncPanel';
import { bioForms, type BioField } from '../lib/biology-forms';
import { useBiologicalData } from '../lib/use-biological-data';
import { today } from '../lib/utils';
import { post } from '../lib/api';
import { adaptiveTdee, baseline, correlation, dateOf, experimentResult, live, mean, nutrition, num, preferredVitals, readiness, type BioKind, type BioRecord } from '../../shared/biology';
import type { Page } from '../lib/types';
import { useQuickLog } from '../components/QuickLog';

const formatted = (value: number | null | undefined, digits = 0) => value == null ? '—' : value.toLocaleString(undefined, {maximumFractionDigits:digits});
function Metric({ label, value, note, action }: { label: string; value: ReactNode; note?: string; action?: () => void }) {
  return <button className="bio-metric glass" onClick={action} disabled={!action}><span className="bio-eyebrow">{label}</span><strong data-kind={typeof value==='string'&&value.length>14?'status':'numeric'}>{value}</strong>{note && <small>{note}</small>}</button>;
}
function Sparkline({ values }: { values: number[] }) {
  if (!values.length) return <p className="subtle">Your records will build this trend.</p>;
  const min = Math.min(...values), range = Math.max(...values)-min || 1;
  const points = values.map((v,i) => `${10+i/Math.max(1,values.length-1)*480},${85-(v-min)/range*70}`).join(' ');
  return <svg viewBox="0 0 500 100" className="bio-spark" role="img" aria-label={`Trend across ${values.length} records; first ${values[0]}, latest ${values.at(-1)}`}><path d="M10 85H490" stroke="var(--line)"/><polyline points={points} fill="none" stroke="var(--bio-accent)" strokeWidth="3" strokeLinejoin="round"/><circle cx={values.length === 1 ? 10 : 490} cy={85-(values.at(-1)!-min)/range*70} r="4" fill="var(--bio-accent)"/></svg>;
}
function download(name: string, data: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); const a = document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }

export function BioEditor({ kind, initial, defaults={}, onSaved, onClose }: { kind: BioKind; initial?: BioRecord; defaults?:Record<string,string|number|boolean>;onSaved?:()=>void|Promise<void>; onClose: () => void }) {
  const bio = useBiology(), toast = useToast(); const def = bioForms[kind];
  const draft = useDraftState<Record<string,string|boolean>>(`advanced:${kind}:${initial?.id || 'new'}`,() => ({__recordId:initial?.id || crypto.randomUUID(),name:initial?.name || '',timestamp:initial ? new Date(Date.parse(initial.timestamp)-new Date(initial.timestamp).getTimezoneOffset()*60000).toISOString().slice(0,16) : new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),source:initial?.source || 'Health OS manual',value:initial?.value?.toString() || '',unit:initial?.unit || def.unit || '',...Object.fromEntries(Object.entries(initial?.metadata || {}).map(([k,v])=>[k,typeof v === 'boolean' ? v : String(v ?? '')])),...Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,typeof v==='boolean'?v:String(v)]))}));
  const values=draft.value,setValues=draft.setValue;
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const fields: BioField[] = [{key:'name',label:kind === 'sourcePriority' ? 'Metric name (e.g. HRV)' : 'Name',required:true},...def.fields,{key:'notes',label:'Notes'}];
  return <Modal open title={`${initial?.id ? 'Edit' : 'Log'} ${def.title.toLowerCase()}`} onClose={onClose}><form className="stack" onSubmit={async e=>{
    e.preventDefault();setBusy(true);setError('');try {
      const metadata: BioRecord['metadata'] = {...initial?.metadata,...Object.fromEntries(Object.entries(defaults).filter(([key])=>!['name','value','unit','timestamp','source','recordQuality'].includes(key)))};
      for (const f of [...def.fields,{key:'notes',kind:'text'} as BioField]) { if (['value','unit'].includes(f.key)) continue; const val=values[f.key]; if (val !== undefined && val !== '') metadata[f.key] = f.kind === 'number' ? Number(val) : val; }
      await bio.save({id:initial?.id || String(values.__recordId),type:kind,domain:def.domain,name:String(values.name),timestamp:new Date(String(values.timestamp)).toISOString(),value:values.value !== '' ? Number(values.value) : undefined,unit:String(values.unit || def.unit || ''),source:String(values.source || 'Health OS manual'),quality:initial?.quality || 'manual',metadata});
      await draft.clear().catch(()=>{});await onSaved?.();toast.push('Entry saved on this device — sync pending','ok');onClose();
    } catch(ex){setError((ex as Error).message);}finally{setBusy(false);}
  }}>
    <p className="subtle">{kind==='medication' ? 'Record the schedule prescribed to you. Health OS does not change doses.' : 'Leave unavailable optional values blank. Every record keeps its source.'}</p>
    <div className="bio-form-grid">{fields.map(f=><label key={f.key}>{f.label}{f.options ? <select className="input" value={String(values[f.key] || '')} required={f.required} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}><option value="">Choose…</option>{f.options.map(o=><option key={o}>{o}</option>)}</select> : <input className="input" type={f.kind === 'checkbox' ? 'checkbox' : f.kind==='number' ? 'number' : f.kind==='date' ? 'date' : f.kind==='time' ? 'time' : 'text'} min={f.min} max={f.max} step={f.kind==='number' ? 'any' : undefined} required={f.required} checked={f.kind==='checkbox' ? Boolean(values[f.key]) : undefined} value={f.kind==='checkbox' ? undefined : String(values[f.key] ?? '')} onChange={e=>setValues(v=>({...v,[f.key]:f.kind==='checkbox' ? e.target.checked : e.target.value}))}/>}</label>)}</div>
    <label>Record time<input className="input" type="datetime-local" required value={String(values.timestamp)} onChange={e=>setValues(v=>({...v,timestamp:e.target.value}))}/></label>
    <label>Source<input className="input" value={String(values.source)} onChange={e=>setValues(v=>({...v,source:e.target.value}))}/></label>
    <SaveStatus status="idle" detail={draft.status}/>{error && <p role="alert">{error}</p>}<button className="btn btn-hot" disabled={busy || !draft.ready}>{busy ? 'Saving…' : 'Save record'}</button>
  </form></Modal>;
}

export function BiologicalOS({page,panel=''}: {page: Page;panel?: string}) {
  const {app,records:all}=useBiologicalData(),automation=useAutomations(),bio=useBiology(),toast=useToast(),quick=useQuickLog();
  const cloud=useCloudAccount();
  const [editor,setEditor]=useState<{kind:BioKind;initial?:BioRecord}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[confirmDelete,setConfirmDelete]=useState<BioRecord|null>(null);
  const [description,setDescription]=useState(''),[photo,setPhoto]=useState(''),[consent,setConsent]=useState(false),[estimate,setEstimate]=useState<Record<string,unknown>|null>(null),[aiBusy,setAiBusy]=useState(false);
  const [importText,setImportText]=useState(''),[preview,setPreview]=useState<unknown[]|null>(null);
  const db=app.db!; const stored=live(bio.records);
  const date=today();const todays=all.filter(r=>dateOf(r.timestamp)===date);const ready=readiness(all,date);const totals=nutrition(all,date);
  const targets=stored.filter(r=>r.type==='nutritionTarget').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];
  const target=(k:string)=>targets ? num(targets,k) : null;
  const water=todays.filter(r=>r.type==='water').reduce((s,r)=>s+(r.value||0),0);
  const sleep=todays.filter(r=>r.type==='sleep').sort((a,b)=>b.timestamp.localeCompare(a.timestamp))[0];
  const weights=all.filter(r=>r.type==='vital' && r.metadata.metric==='Weight' && r.value!==undefined).map(r=>({date:dateOf(r.timestamp),weight:r.unit==='lb' ? r.value!/2.2046226218 : r.value!}));
  const tdee=adaptiveTdee(all,weights);
  const run=async(fn:()=>Promise<unknown>)=>{setError('');try{await fn();}catch(e){setError((e as Error).message);}};
  const log=(kind:BioKind,initial?:BioRecord)=>quick.open(kind,initial);
  const collection=(kind:BioKind,title=bioForms[kind].title)=>{const rows=stored.filter(r=>r.type===kind);return <section className="glass card stack"><div className="bio-section-title"><h3>{title}</h3>{rows.length>0&&<button className="btn btn-hot" onClick={()=>log(kind)}>＋ Add {bioForms[kind].title.toLowerCase()}</button>}</div>{rows.length?listRecords(rows):<StatePanel state="empty" title={kind==='sourcePriority'?'No source priorities configured':`No ${title.toLowerCase()} yet`} body={kind==='medication'?'Add your prescribed schedule to keep dose confirmations and history together.':kind==='supplement'?'Add a supplement and its schedule to record your own use.':kind==='sourcePriority'?'Import or log readings first, then choose which source should be preferred for each metric.':kind==='illness'?'Record an episode with its dates and notes when you need to track one.':kind==='symptom'?'Record what you noticed, when it started and its severity.':`Your first entry starts this ${title.toLowerCase()} history.`} action={<div className="row wrap"><button className="btn btn-hot" onClick={()=>log(kind)}>Add {bioForms[kind].title.toLowerCase()}</button>{kind==='sourcePriority'&&<button className="btn btn-soft" onClick={()=>app.setPage('Health','Connected Sources')}>Open sources</button>}</div>}/>}</section>;};
  function listRecords(rows:BioRecord[]) { return rows.length ? <div className="bio-record-list">{[...rows].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,100).map(r=><article className="bio-record" key={r.id}><div><strong>{r.name}</strong><p className="subtle">{new Date(r.timestamp).toLocaleString()} · {r.source} · {r.quality}</p>{r.value!==undefined && <b>{formatted(r.value,2)} {r.unit}</b>}<p className="bio-record-meta">{Object.entries(r.metadata).filter(([k])=>!['notes','parentId','consent'].includes(k)).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p>{r.metadata.notes && <p>{String(r.metadata.notes)}</p>}</div><div className="row"><button className="btn btn-soft" onClick={()=>log(r.type,r)}>Edit</button><button className="icon-btn" aria-label={`Delete ${r.name}`} onClick={()=>setConfirmDelete(r)}>×</button></div></article>)}</div> : <StatePanel title="No records yet" body="Log your first entry to start this history."/>; }
  const readinessCard=<section className="glass card bio-readiness"><div><span className="bio-eyebrow">READINESS · {ready.confidence} CONFIDENCE</span><div className="bio-score">{ready.score ?? '—'}<span>{ready.category}</span></div><p className="subtle">Experimental planning estimate · not a medical assessment</p></div><div>{ready.contributors.map(c=><div className="bio-contributor" key={c.label}><strong>{c.label}</strong><span>{c.detail}</span></div>)}<p className="subtle">Missing: {ready.missing.join(', ') || 'No missing inputs'}</p><button className="btn btn-soft" onClick={()=>app.setPage('Recover')}>Review recovery →</button></div></section>;
  const macros=<section className="glass card stack"><div className="bio-section-title"><h3>Nutrition</h3><button className="btn btn-soft" onClick={()=>log('meal')}>＋ Log meal</button></div>{(['calories','protein','carbs','fat','fibre'] as const).map(k=><div key={k} className="bio-macro"><div><strong>{k}</strong><span>{formatted(totals[k])} / {target(k) ?? 'Set target'} {k==='calories'?'kcal':'g'}</span></div><progress max={target(k) || Math.max(1,totals[k])} value={totals[k]}/></div>)}</section>;
  const unifiedTimeline=[...all.filter(r=>!['food','recipe','nutritionTarget','sourcePriority','researchConsent','nudgePreference'].includes(r.type)).map(r=>({id:r.id,time:r.timestamp,title:r.name,domain:r.domain,detail:`${r.value??''} ${r.unit} · ${r.source}`})),
    ...db.sessions.map(s=>({id:`session-${s.id}`,time:s.startedAt || `${s.date}T12:00:00`,title:`Workout · ${s.name || s.dayTitle}`,domain:'Train',detail:`${s.logs?.length || 0} exercises · ${s.status}`})),
    ...app.skin.care.events.map(e=>({id:`care-${e.id}`,time:`${e.date}T12:00:00`,title:`Care · ${e.status}`,domain:'Care',detail:'Care routine event'})),
    ...db.habitLogs.map(h=>({id:`habit-${h.id}`,time:`${h.date}T12:00:00`,title:'Habit logged',domain:'Today',detail:'Existing habit history'}))].sort((a,b)=>b.time.localeCompare(a.time));
  const timeline=<section className="glass card stack"><h3>One record of your day</h3><input className="input" aria-label="Filter timeline" placeholder="Search events or domains" value={query} onChange={e=>setQuery(e.target.value)}/><div className="bio-timeline">{unifiedTimeline.filter(r=>`${r.title} ${r.domain} ${r.detail}`.toLowerCase().includes(query.toLowerCase())).slice(0,200).map(r=><article key={r.id}><time>{new Date(r.time).toLocaleString()}</time><span className="bio-timeline-dot"/><div><small>{r.domain}</small><strong>{r.title}</strong><p className="subtle">{r.detail}</p></div></article>)}</div>{!unifiedTimeline.length && <p className="subtle">Your first logged event starts the timeline.</p>}</section>;
  const nudges=useMemo(()=>{
    const pref=stored.filter(r=>r.type==='nudgePreference').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];
    if (pref && !pref.metadata.enabled) return [];
    const hour=new Date().toTimeString().slice(0,5), start=String(pref?.metadata.quietStart||'22:00'),end=String(pref?.metadata.quietEnd||'07:00');
    if (start>end ? hour>=start || hour<end : hour>=start && hour<end) return [];
    const result:{title:string;reason:string;page:Page}[]=[];
    if (ready.score===null) result.push({title:'Take a moment for your check-in',reason:'No recovery inputs recorded today.',page:'Recover'});
    if (target('water') && water<target('water')!) result.push({title:'Water target is still open',reason:`${water} / ${target('water')} mL logged.`,page:'Eat'});
    if (target('protein') && totals.protein<target('protein')!) result.push({title:'Plan your next protein serving',reason:`${totals.protein} / ${target('protein')} g recorded.`,page:'Eat'});
    const due=stored.filter(r=>['supplement','medication'].includes(r.type)&&r.metadata.time&&String(r.metadata.time)<=hour&&!todays.some(d=>d.type==='dose'&&d.metadata.parentId===r.id));
    if(due.length) result.push({title:`${due.length} scheduled doses need a log`,reason:'Record taken or skipped; follow your existing schedule.',page:'Health'});
    return result.slice(0,Number(pref?.metadata.dailyLimit??3));
  },[bio.records,db]);
  let content:ReactNode;
  if(page==='Today') content=<>
    <section className="bio-hero"><div><p className="bio-eyebrow">YOUR BIOLOGICAL COMMAND CENTER</p><h1>{new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening'}, {db.profile.displayName || app.settings?.profileName || 'Athlete'}<span>.</span></h1><p>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} · A little more in tune with yourself.</p></div><div className="bio-orbit" aria-hidden="true"><img src="/body-os-logo-v5.png" alt=""/></div></section>
    {readinessCard}<div className="bio-grid"><Metric label="Sleep" value={`${formatted(sleep?.value,1)} h`} note={sleep?.source || 'Log sleep to begin'} action={()=>app.setPage('Recover')}/><Metric label="Water" value={`${formatted(water/1000,1)} L`} note={target('water') ? `${target('water')!/1000} L target` : 'Set your own target'} action={()=>app.setPage('Eat')}/><Metric label="Weight trend" value={`${formatted(mean(weights.slice(-7).map(w=>w.weight)),1)} kg`} note={`${weights.slice(-7).length} recent weigh-ins`} action={()=>app.setPage('Body')}/><Metric label="Resting HR" value={`${formatted(baseline(all,'Resting HR',date).current?.value)} bpm`} note="Latest preferred source today" action={()=>app.setPage('Health')}/></div>
    <div className="bio-two-col">{macros}<section className="glass card stack"><span className="bio-eyebrow">NEXT NUDGE</span>{nudges.length?nudges.map(n=><button key={n.title} className="bio-nudge" onClick={()=>app.setPage(n.page)}><strong>{n.title} ↗</strong><span>{n.reason}</span></button>):<p className="subtle">No pending nudges. Quiet hours and your preferences are respected.</p>}<button className="btn btn-soft" onClick={()=>app.setPage('Nudges')}>Nudge preferences</button></section></div>
    <div className="bio-two-col"><section className="glass card stack"><span className="bio-eyebrow">TODAY’S TRAINING</span><h3>{db.weeks.find(w=>w.id===db.meta.activeWeekId)?.name || 'Your next session'}</h3><p className="subtle">Your complete training system, programs and history are preserved.</p><button className="btn btn-hot" onClick={()=>app.setPage('Dashboard')}>Open Train →</button></section><section className="glass card stack"><span className="bio-eyebrow">CARE & HEALTH</span><h3>{app.skin.care.events.filter(e=>e.date===date&&e.status==='done').length} care actions completed</h3><p>{todays.filter(r=>r.type==='dose'&&r.metadata.status==='Taken').length} doses logged</p><div className="row"><button className="btn btn-soft" onClick={()=>app.setPage('SkinOverview')}>Care →</button><button className="btn btn-soft" onClick={()=>app.setPage('Health')}>Health →</button></div></section></div>
    <section className="glass card stack"><span className="bio-eyebrow">HEALTH OS COACH · EVIDENCE FIRST</span><h3>{ready.score===null?'Build your personal baseline.':`${ready.category}: ${ready.contributors.length} inputs inform today’s estimate.`}</h3><p className="subtle">{ready.contributors.map(c=>`${c.label}: ${c.detail}`).join(' • ') || 'Log sleep, a check-in and health readings to connect your daily signals.'}</p><button className="btn btn-soft" onClick={()=>app.setPage('BodyCoach')}>Explore the evidence →</button></section>
  </>;
  else if(page==='Timeline') content=timeline;
  else if(page==='Eat') {
    const mode=panel || 'Today';
    const logs=['Today','Food Diary','Breakfast','Lunch','Snacks','Dinner'].includes(mode);
    const library=['Search Food','Scan Barcode','My Foods','Saved Meals','Recipes','Favorites'].includes(mode);
    content=<><div className="bio-page-head"><span className="bio-eyebrow">EAT / {mode.toUpperCase()}</span><h1>Fuel your day<span>.</span></h1><p className="subtle">Food, water and a clearer picture of your energy balance.</p></div>
      {logs&&<>{macros}<div className="row wrap"><button className="btn btn-hot" onClick={()=>log('meal')}>＋ Log meal</button><button className="btn btn-soft" onClick={()=>log('water')}>＋ Water</button><button className="btn btn-soft" onClick={()=>log('nutritionTarget',targets)}>Set targets</button></div>{listRecords(stored.filter(r=>r.type==='meal'&&dateOf(r.timestamp)===date&&(!['Breakfast','Lunch','Snacks','Dinner'].includes(mode)||r.metadata.meal===mode)))}</>}
      {mode==='Quick Add'&&collection('meal','Quick add calories & macros')}
      {library&&<section className="glass card stack"><h3>{mode}</h3><input className="input" aria-label="Search foods or barcode" placeholder={mode==='Scan Barcode'?'Enter barcode from the package':'Search your local foods and recipes'} value={query} onChange={e=>setQuery(e.target.value)}/><div className="row wrap"><button className="btn btn-hot" onClick={()=>log('food')}>＋ My food</button><button className="btn btn-soft" onClick={()=>log('recipe')}>＋ Recipe / saved meal</button></div>{stored.filter(r=>['food','recipe'].includes(r.type)&&(mode!=='Favorites'||r.metadata.favorite===true)&&`${r.name} ${r.metadata.barcode||''}`.toLowerCase().includes(query.toLowerCase())).map(r=><div className="bio-record" key={r.id}><div><strong>{r.name}</strong><p className="subtle">{r.metadata.calories ?? 'Unknown'} kcal · {r.metadata.protein ?? 'Unknown'} g protein · {r.source}</p></div><div className="row"><button className="btn btn-soft" onClick={()=>log(r.type,r)}>Edit</button><button className="btn btn-hot" onClick={()=>log('meal',{...r,id:'',type:'meal',timestamp:new Date().toISOString(),metadata:{...r.metadata,completeDay:false}})}>Review & log</button></div></div>)}{!stored.some(r=>r.type==='food'||r.type==='recipe')&&<p className="subtle">Add foods once, then reuse them offline. Barcode lookup searches this local library.</p>}</section>}
      {['Describe Meal','Snap Meal'].includes(mode)&&<section className="glass card stack"><h3>Estimate, review, then log</h3><textarea className="input" aria-label="Describe meal" placeholder="Describe the foods and portions…" value={description} onChange={e=>setDescription(e.target.value)}/>{mode==='Snap Meal'&&<label>Select a meal photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){setError('Choose an image smaller than 4 MB');return;}const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(f);}}/>{photo&&<img className="bio-meal-photo" src={photo} alt="Meal selected for review"/>}</label>}<label className="row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send only this description{photo?' and selected photo':''} to my configured AI provider for an estimate.</label><button className="btn btn-hot" disabled={aiBusy||!consent||(!description&&!photo)} onClick={()=>void run(async()=>{setAiBusy(true);try{const result=await automation.request<{estimate:Record<string,unknown>}>('/api/biology/estimate-meal',{description,photo,consent});setEstimate(result.estimate);}finally{setAiBusy(false);}})}>{aiBusy?'Estimating…':'Estimate meal'}</button><p className="subtle">Portions and nutrition are estimates. Review all numbers before saving. A configured AI provider is required.</p>{estimate&&<><pre className="bio-json">{JSON.stringify(estimate,null,2)}</pre><button className="btn btn-soft" onClick={()=>log('meal',{id:'',name:String(estimate.name||description),quality:'estimated',timestamp:new Date().toISOString(),metadata:estimate as BioRecord['metadata']} as BioRecord)}>Review editable estimate</button></>}</section>}
      {mode==='Water'&&<><div className="bio-grid"><Metric label="Logged today" value={`${formatted(water/1000,2)} L`} note={target('water')?`${target('water')} mL target`:'Set a target'}/></div><div className="row wrap">{[250,350,500].map(amount=><button className="btn btn-soft" key={amount} onClick={()=>void run(()=>bio.save({type:'water',domain:'Eat',name:'Water',value:amount,unit:'mL'}))}>＋ {amount} mL</button>)}<button className="btn btn-hot" onClick={()=>log('water')}>Custom amount</button></div>{listRecords(stored.filter(r=>r.type==='water'))}</>}
      {mode==='Targets'&&collection('nutritionTarget')}{mode==='Macros'&&macros}
      {mode==='Micronutrients'&&<section className="glass card stack"><h3>Micronutrient coverage</h3>{['iron','calcium','vitaminD','sodium'].map(k=>{const meals=todays.filter(r=>r.type==='meal');const covered=meals.filter(r=>num(r,k)!==null);return <div className="bio-contributor" key={k}><strong>{k}</strong><span>{formatted(covered.reduce((s,r)=>s+num(r,k)!,0),1)} {k==='vitaminD'?'µg':'mg'} · {covered.length}/{meals.length} meals have data</span></div>;})}<p className="subtle">Missing nutrient fields are unknown. Totals include only covered foods.</p></section>}
      {mode==='Adaptive TDEE'&&<section className="glass card stack"><span className="bio-eyebrow">ENERGY BALANCE ESTIMATE</span><h2>{formatted(tdee.value)} kcal / day</h2><p>{tdee.confidence}</p><p>{tdee.days} days · {tdee.weighIns} weigh-ins · {tdee.completeDays} complete nutrition days</p><p className="subtle">Requires at least 21 days, 14 weigh-ins and 80% complete food days. Uses 7-reading weight averages and a rough 7,700 kcal/kg conversion; water changes and logging error affect this estimate.</p></section>}
      {mode==='Meal Planner'&&<>{collection('mealPlan')}<section className="glass card stack"><h3>Recipes for your remaining targets</h3><p className="subtle">Ranked by fit to remaining calories and protein. Review ingredients for dietary suitability.</p>{stored.filter(r=>r.type==='recipe').sort((a,b)=>Math.abs((num(a,'protein')||0)-Math.max(0,(target('protein')||0)-totals.protein))-Math.abs((num(b,'protein')||0)-Math.max(0,(target('protein')||0)-totals.protein))).slice(0,5).map(r=><div key={r.id} className="bio-record"><strong>{r.name}</strong><span>{r.metadata.calories} kcal · {r.metadata.protein} g protein · {r.metadata.allergens || 'Allergens not recorded'}</span></div>)}</section></>}
    </>;
  }
  else if(page==='Recover') {
    const mode=panel||'Overview';
    content=<><div className="bio-page-head"><span className="bio-eyebrow">RECOVER / {mode.toUpperCase()}</span><h1>Make room to recover<span>.</span></h1></div>
      {['Overview','Readiness','Fatigue','Recovery Balance','Recovery Trends'].includes(mode)&&<>{readinessCard}<div className="row wrap"><button className="btn btn-hot" onClick={()=>log('checkIn')}>＋ Daily check-in</button><button className="btn btn-soft" onClick={()=>log('sleep')}>＋ Sleep</button></div></>}
      {['Daily Check-in','Soreness','Stress & Energy','Readiness History'].includes(mode)&&collection('checkIn')}
      {mode==='Daily Check-in'&&<section className="glass card stack"><h3>Your shared daily readiness</h3><p>Complete or edit every readiness answer on Today. Your workout uses the same check-in.</p><button className="btn btn-hot" onClick={()=>quick.open('checkIn')}>Edit on Today ↗</button></section>}
      {['Sleep','Sleep History'].includes(mode)&&<>{collection('sleep')}<section className="glass card stack"><h3>Sleep duration trend</h3><Sparkline values={all.filter(r=>r.type==='sleep').sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).slice(-28).map(r=>r.value||0)}/><p className="subtle">Sleep stages appear only when entered or provided by an imported source.</p></section></>}
      {['Pain & Injury','Recovery Notes'].includes(mode)&&<>{collection('recoveryNote',mode)}{db.painLogs.map(p=><article key={p.id} className="glass card"><strong>Existing pain record · {p.date}</strong><p>{JSON.stringify(p)}</p></article>)}</>}
      {['Training Load','Fatigue','Recovery Balance'].includes(mode)&&<section className="glass card stack"><h3>Training load</h3>{[7,28].map(days=>{const sessions=db.sessions.filter(s=>Date.parse(`${s.date}T12:00:00`)>=Date.now()-days*86400000);const volume=sessions.reduce((sum,s)=>sum+s.logs.reduce((n,e)=>n+e.sets.filter(set=>set.type!=='warmup').reduce((v,set)=>v+(Number(set.w)||0)*(Number(set.r)||0),0),0),0);return <div className="bio-contributor" key={days}><strong>Last {days} days</strong><span>{sessions.length} sessions · {formatted(volume)} {db.profile.units} recorded volume</span></div>;})}<p className="subtle">External-load volume excludes warm-ups. It does not capture every source of fatigue.</p></section>}
      {mode==='Cardio'&&<section className="glass card stack"><h3>Cardio history</h3>{db.cardio.map(c=><p key={c.id}>{JSON.stringify(c)}</p>)}<button className="btn btn-soft" onClick={()=>app.setPage('Calendar')}>Open training calendar</button></section>}
    </>;
  }
  else if(page==='Health') {
    const mode=panel||'Overview';const types:Record<string,BioKind>={Symptoms:'symptom','Illness Events':'illness',Medications:'medication',Supplements:'supplement','Manual Readings':'vital','Source Priority':'sourcePriority'};
    const metricMap:Record<string,string[]>={Heart:['HRV','Resting HR','Heart Rate'],Activity:['Steps','Active Calories'],'Blood Pressure':['Blood Pressure Systolic','Blood Pressure Diastolic'],'Blood Glucose':['Blood Glucose'],Oxygen:['Oxygen'],Temperature:['Temperature'],Respiration:['Respiration']};
    const scheduled=mode==='Medications'?'medication':'supplement';
    content=<><div className="bio-page-head"><span className="bio-eyebrow">HEALTH / {mode.toUpperCase()}</span><h1>{{'Illness Events':'Illness episodes','Manual Readings':'Health readings','Blood Glucose':'Blood glucose','Blood Pressure':'Blood pressure',Respiration:'Respiratory rate',Oxygen:'Blood oxygen'}[mode]||mode}</h1></div>
      {(mode==='Overview'||metricMap[mode])&&<><div className="bio-grid">{(metricMap[mode]||[...new Set(all.filter(r=>r.type==='vital').map(r=>String(r.metadata.metric)))]).map(metric=>{const b=baseline(all,metric,date);return <Metric key={metric} label={metric} value={`${formatted(b.current?.value,1)} ${b.current?.unit||({HRV:'ms','Resting HR':'bpm','Heart Rate':'bpm',Steps:'steps','Active Calories':'kcal','Blood Pressure Systolic':'mmHg','Blood Pressure Diastolic':'mmHg','Blood Glucose':'mmol/L',Oxygen:'%',Temperature:'°C',Respiration:'breaths/min'} as Record<string,string>)[metric]||''}`} note={b.current?`${dateOf(b.current.timestamp)} · ${b.current.source} · ${b.current.quality}`:'No reading for today'}/>;})}</div><button className="btn btn-hot" onClick={()=>log('vital')}>＋ Manual reading</button></>}
      {mode==='Medical Intelligence'&&<MedicalIntelligence/>}
      {mode==='Health Timeline'&&timeline}
      {types[mode]&&collection(types[mode],mode)}
      {['Medications','Supplements'].includes(mode)&&stored.some(r=>r.type===scheduled)&&<section className="glass card stack"><h3>Today’s schedule & adherence</h3>{stored.filter(r=>r.type===scheduled).flatMap(r=>scheduledDoseTimes(r,date).map(time=>{const dose=confirmedDose(stored,r,date,time);return <div key={`${r.id}:${time}`} className="bio-record"><div><strong>{r.name}</strong><p className="subtle">{time} · {dose?.metadata.status || 'Pending'}</p></div><div className="row">{['Taken','Skipped'].map(status=><button className="btn btn-soft" key={status} onClick={()=>void run(()=>bio.save({id:dose?.id||stableRecordId('dose',r.id,date,time),type:'dose',domain:'Health',name:`${r.name} · ${status}`,source:'Health OS explicit confirmation',metadata:{parentId:r.id,status,scheduledTime:time,doseType:r.type}}))}>{status}</button>)}</div></div>;}))}{listRecords(stored.filter(r=>r.type==='dose'))}</section>}
      {['Health Connect','Connected Sources'].includes(mode)&&<section className="glass card stack"><h3>{mode}</h3><p className="subtle">This web app can review and import a normalized health export. It does not connect to native device sensors.</p><div className="bio-contributor"><strong>Available sources</strong><span>{[...new Set(all.map(r=>r.source))].join(', ')||'No sources yet'}</span></div><p>{all.filter(r=>r.quality==='imported'||r.quality==='measured').length} imported / measured · {all.filter(r=>r.quality==='estimated').length} estimated records</p><p className="subtle">Repeated source + source record IDs are skipped. Overlapping daily vitals use one preferred source.</p><label>Normalized JSON export<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const data=JSON.parse(await f.text());setPreview(Array.isArray(data)?data:data.records);});}}/></label><details className="flow-details"><summary>Advanced · paste normalized JSON</summary><label>Normalized health records<textarea className="input" aria-label="Health import JSON" placeholder="Paste an array of Health OS biological records" value={importText} onChange={e=>setImportText(e.target.value)}/></label><button className="btn btn-soft" onClick={()=>void run(async()=>setPreview(JSON.parse(importText)))}>Preview import</button></details>{preview&&<><p>{preview.length} records to review</p><pre className="bio-json">{JSON.stringify(preview.slice(0,3),null,2)}</pre><button className="btn btn-hot" onClick={()=>void run(async()=>{await bio.importRecords(preview);setPreview(null);toast.push('Import saved','ok');})}>Confirm import</button></>}<button className="btn btn-soft" onClick={()=>download('body-os-health-export.json',{version:1,records:stored.filter(r=>['Health','Recover'].includes(r.domain))})}>Export health records</button></section>}
      {mode==='Data Quality'&&<section className="glass card stack"><h3>Your data, in context</h3><div className="bio-grid">{['manual','measured','imported','estimated'].map(quality=><Metric key={quality} label={quality} value={all.filter(r=>r.quality===quality).length} note="saved records"/>)}</div><div className="bio-contributor"><strong>Available sources</strong><span>{[...new Set(all.map(r=>r.source))].join(', ')||'None yet'}</span></div><p className="subtle">Overlapping daily vitals use one preferred source. Missing readings are unknown and do not become zero.</p></section>}
      {mode==='Progress Photos'&&<section className="glass card stack"><h3>Private progress photos</h3><p className="subtle">Use the existing private photo library, with explicit consent for AI analysis.</p><button className="btn btn-hot" onClick={()=>app.setPage('SkinProgress')}>Open private photo library</button></section>}
    </>;
  }
  else if(page==='Insights'||page==='BodyCoach') {
    const metrics=['HRV','Resting HR','Steps','Weight'];const sleeps=new Map(all.filter(r=>r.type==='sleep').map(r=>[dateOf(r.timestamp),r.value!]));
    const checks=new Map(all.filter(r=>r.type==='checkIn').map(r=>[dateOf(r.timestamp),num(r,'energy')]));
    const pairs=[...sleeps].filter(([d])=>checks.get(d)!=null).map(([d,x])=>({date:d,x,y:checks.get(d)!})); const corr=correlation(pairs);
    const coachEvidence={date,readiness:ready,nutrition:totals,water,sleepHours:sleep?.value||null,trainingSessions:db.sessions.filter(s=>s.date>=new Date(Date.now()-7*86400000).toISOString().slice(0,10)).length,baselines:metrics.map(m=>baseline(all,m,date)),tdee,progress:Object.values(automation.state.derived).filter(d=>['goal','habit'].includes(d.kind)&&d.date===date).map(d=>({value:d.value,evidence:d.evidence})),insights:automation.state.derived.insights?.value||[],intelligence:page==='BodyCoach'?assistantEvidence(buildHealthIntelligence({db,skin:app.skin,records:bio.records,userId:cloud.user?.id||'local-user'},date)):undefined};
    content=<><div className="bio-page-head"><span className="bio-eyebrow">{page==='BodyCoach'?'HEALTH OS COACH':'INSIGHTS'} / {panel||'OVERVIEW'}</span><h1>{page==='BodyCoach'?'Health OS coach':'Understand your patterns'}<span>.</span></h1><p className="subtle">Deterministic calculations. Visible evidence. Associations, never assumed causes.</p></div>
      {page==='BodyCoach'&&<section className="glass card stack"><h3>Ask across your approved data</h3><details><summary>Evidence approved for sharing</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(coachEvidence,null,2)}</pre></details><textarea className="input" aria-label="Ask Health OS Coach" placeholder="What changed in my recovery this week?" value={description} onChange={e=>setDescription(e.target.value)}/><label className="row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Share this displayed summary with my configured AI provider.</label><button className="btn btn-hot" disabled={!description||!consent||aiBusy} onClick={()=>void run(async()=>{setAiBusy(true);try{const response=await automation.request<{answer:string}>('/api/biology/coach',{question:description,consent,evidence:coachEvidence});setEstimate({answer:response.answer});}finally{setAiBusy(false);}})}>Ask with this evidence</button>{estimate&&<p style={{whiteSpace:'pre-wrap'}}>{String(estimate.answer)}</p>}<p className="subtle">Photos and raw symptom/dose records are excluded. The preview shows everything shared.</p></section>}
      {readinessCard}<details className="glass card"><summary>Explore baselines, comparisons & energy estimates</summary><div className="bio-two-col"><section className="glass card stack"><h3>Personal baselines & anomalies</h3>{metrics.map(m=>{const b=baseline(all,m,date);return <div key={m} className="bio-baseline"><div className="bio-section-title"><strong>{m}</strong><span className="chip">{b.samples<14?'Insufficient history':b.anomalous?'Outside recent range':'Personal range'}</span></div><p className="subtle">Today {formatted(b.current?.value,1)} · prior 28-day average {formatted(b.average,1)} · {b.samples} observed days · deviation {formatted(b.deviation,1)}%</p><SignalChart label={m} unit={preferredVitals(all,m).at(-1)?.unit||''} points={preferredVitals(all,m).slice(-28).map(r=>({date:dateOf(r.timestamp),value:r.value??null}))}/></div>;})}<p className="subtle">Anomaly flags require 14 prior daily samples and a deviation beyond two standard deviations. They describe observations and do not diagnose illness.</p></section><section className="glass card stack"><h3>Sleep ↔ self-reported energy</h3><Metric label="Correlation" value={corr.r===null?'Not enough data':corr.r.toFixed(2)} note={`${corr.samples} matched days · ${corr.confidence} confidence`}/>{pairs.length>0?<EvidenceScatter pairs={pairs} label="Sleep (h) versus energy (/10)"/>:<StatePanel state="insufficient" title="No matched observations" body="Log sleep and energy for the same days to build this comparison."/>}<p className="subtle">{pairs[0]?.date||'—'} to {pairs.at(-1)?.date||'—'}. Same-day records are paired; other factors may contribute. This cannot establish causality.</p><button className="btn btn-soft" onClick={()=>download('body-os-correlation.json',corr)}>Export evidence</button><h3>Weight trend</h3><SignalChart label="Recorded weight" unit="kg" points={weights.slice(-30).map(w=>({date:w.date,value:w.weight}))}/><p className="subtle">7-reading average: {formatted(mean(weights.slice(-7).map(w=>w.weight)),1)} kg · {weights.length} weigh-ins</p><h3>Adaptive expenditure</h3><p>{formatted(tdee.value)} kcal/day · {tdee.confidence}</p></section></div></details>
      <section className="glass card stack"><h3>Keep exploring</h3><div className="row wrap"><button className="btn btn-hot" onClick={()=>app.setPage('Analyzer')}>Training Analytics Lab</button><button className="btn btn-soft" onClick={()=>app.setPage('Reports')}>Reports</button><button className="btn btn-soft" onClick={()=>app.setPage('Experiments')}>Personal experiments</button><button className="btn btn-soft" onClick={()=>app.setPage('SkinProgress')}>Care progress</button></div></section>
    </>;
  }
  else if(page==='Experiments') content=<>{collection('experiment','N-of-1 experiments')}{stored.filter(r=>r.type==='experiment').map(r=>{const result=experimentResult(r,all,date);return <section key={r.id} className="glass card stack"><h3>{r.metadata.question||r.name}</h3><p>{r.metadata.intervention||'No intervention described'} · {result.start} · {result.elapsedDays}/{result.interventionDays} days</p><p className="subtle">Outcome: {result.metric} ({result.unit||'unit unavailable'}) · prior {result.baselineDays} days</p><div className="bio-grid"><Metric label="Before" value={formatted(result.before,2)} note={`${result.baselineSamples} observed days`}/><Metric label="During" value={formatted(result.during,2)} note={`${result.interventionSamples} observed days`}/><Metric label="Difference" value={formatted(result.difference,2)} note={result.confidence}/></div>{result.adherence&&<p>Target: {result.adherence.target} {result.adherence.unit} {result.adherence.metric}/day · reached on {result.adherence.metDays}/{result.elapsedDays} elapsed days · {result.adherence.observedDays} days recorded. Unlogged days are unknown.</p>}{result.excludedUnitSamples>0&&<p className="subtle">{result.excludedUnitSamples} outcome readings excluded because their units could not be compared.</p>}<p className="subtle">A before/during comparison can be affected by other changes. Results do not establish causality.</p></section>;})}</>;
  else if(page==='Research') {
    const pref=stored.filter(r=>r.type==='researchConsent').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]; const enrolled=pref?.metadata.consent===true;
    content=<section className="glass card stack"><span className="bio-eyebrow">OPTIONAL RESEARCH</span><h1>{enrolled?'Local export enabled':'Not enrolled'}<span>.</span></h1><p className="subtle">No data is sent to a research service. Participation currently means preparing a selected local export for a purpose you define. Photos, medication, symptoms and illness records are excluded. Exports contain dates and physiological measurements and are not anonymous.</p><dl><dt>Purpose</dt><dd>{pref?.metadata.purpose||'Not set'}</dd><dt>Retention</dt><dd>{pref?.metadata.retention||'No export retention policy set'}</dd><dt>Included domains</dt><dd>{pref?.metadata.domains||'None'}</dd></dl><div className="row wrap"><button className="btn btn-soft" onClick={()=>log('researchConsent',pref)}>Review preferences</button>{enrolled&&<><button className="btn btn-hot" onClick={()=>{const domains=String(pref.metadata.domains||'').split(',').map(s=>s.trim());const records=stored.filter(r=>domains.includes(r.domain)&&['sleep','checkIn','vital','water','meal'].includes(r.type)).map(r=>({domain:r.domain,type:r.type,date:dateOf(r.timestamp),value:r.value,unit:r.unit,metadata:Object.fromEntries(Object.entries(r.metadata).filter(([,v])=>typeof v==='number'))}));download('body-os-research-export.json',{purpose:pref.metadata.purpose,retention:pref.metadata.retention,records});}}>Export selected research data</button><button className="btn btn-soft" onClick={()=>void run(()=>bio.save({...pref,metadata:{...pref.metadata,consent:false}}))}>Withdraw consent</button></>}</div><p className="subtle">Withdrawal stops future exports. Delete any files you already exported separately; local tracking history is preserved.</p></section>;
  }
  else if(page==='Habits') content=<>{panel==='Weekly Review'?<section className="glass card stack"><h3>Weekly review</h3><textarea className="input" aria-label="Weekly review notes" value={description} onChange={e=>setDescription(e.target.value)}/><button className="btn btn-hot" onClick={()=>void run(async()=>{await app.api.saveWeeklyReview({date,notes:description,weekStart:date});await app.refresh();toast.push('Weekly review saved','ok');})}>Save review</button>{db.weeklyReviews.map(r=><p key={r.id}>{JSON.stringify(r)}</p>)}</section>:<><Records initialView="habits"/>{stored.filter(r=>r.type==='habit').map(r=>{const done=todays.find(d=>d.type==='habitDone'&&d.metadata.parentId===r.id);return <div className="glass card bio-record" key={r.id}><strong>{r.name}</strong><button className="btn btn-soft" disabled={Boolean(done)} onClick={()=>void run(()=>bio.save({type:'habitDone',domain:'Today',name:`${r.name} completed`,metadata:{parentId:r.id}}))}>{done?'✓ Done today':'Mark complete'}</button></div>;})}</>}</>;
  else if(page==='Nudges') content=<>{collection('nudgePreference','Contextual nudges')}<section className="glass card stack"><h3>What matters next</h3>{nudges.map(n=><button key={n.title} className="bio-nudge" onClick={()=>app.setPage(n.page)}><strong>{n.title}</strong><span>{n.reason}</span></button>)}<p className="subtle">Nudges appear in-app only. Quiet hours, enabled state and display limit apply. No background push notifications are scheduled.</p></section></>;
  else if(page==='Search') content=<SearchWorkspace/>;
  else if(page==='Sync') content=<><section className="glass card stack"><span className="bio-eyebrow">SYNC & BACKUP</span><h1>Your data stays yours<span>.</span></h1><p role="status">{bio.status} · {stored.length} biological records</p><p className="subtle">Local records remain available without a cloud account. Connect an optional account to sync; pending changes and conflicts are reviewed in the connection panel below.</p><div className="row wrap"><button className="btn btn-hot" onClick={()=>void bio.sync()}>Sync pending records</button><button className="btn btn-soft" onClick={()=>void run(async()=>download('body-os-complete-backup.json',{version:2,legacy:await app.api.getBackup(),biology:bio.records}))}>Export complete backup</button></div><label>Restore biological records from a backup<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const data=JSON.parse(await f.text());setPreview(data.biology||data.records||data);});}}/></label>{preview&&<><p>{preview.length} biological records. Existing records are merged by ID; newer local records remain.</p><button className="btn btn-hot" onClick={()=>void run(async()=>{await bio.importRecords(preview);setPreview(null);})}>Confirm restore</button></>}{bio.conflicts.map(r=><div className="bio-record" key={r.id}><strong>Conflict: {r.name}</strong><div className="row"><button className="btn btn-soft" onClick={()=>void run(()=>bio.resolveConflict(r.id,'cloud'))}>Use Supabase version</button><button className="btn btn-soft" onClick={()=>void run(()=>bio.resolveConflict(r.id,'browser'))}>Keep browser version</button></div></div>)}{bio.error&&<p className="subtle">{bio.error}</p>}<p className="subtle">Training and Care backups and restoration remain available in Settings.</p></section>{bio.fallbackRecords>0&&<section className="glass card stack"><h3>Unsynced fallback entries</h3><p className="subtle">{bio.fallbackRecords} entries were saved before account sync. Review your backup, then add them to this signed-in account.</p><button className="btn btn-hot" onClick={()=>void run(()=>bio.adoptFallback())}>Import fallback entries into my account</button></section>}<CloudSyncPanel/></>;
  else if(page==='Permissions') content=<section className="glass card stack"><h1>Permissions & privacy<span>.</span></h1>{[['Health Connect','Import only on web; no device permission requested.'],['Notifications','Permission is requested when you enable browser reminders. Delivery requires this app to be running; background delivery is not guaranteed.'],['Camera','Barcode scanning requests camera access when you start the scanner. You can deny access and enter digits manually. Meal photos use your selected file.'],['Photos','Only selected files are read. Progress photos use the existing private library.'],['AI','Each biological coach or meal request requires an explicit checkbox.'],['Research','Not enrolled by default. Selected local exports only.'],['Account storage','Records belong to your signed-in account. Supported biological entries remain on this device while sync is pending.']].map(([label,detail])=><div className="bio-contributor" key={label}><strong>{label}</strong><span>{detail}</span></div>)}</section>;
  else if(page==='Profile') content=<section className="glass card stack"><h1>{db.profile.displayName||'Your profile'}<span>.</span></h1><p>Weight unit: {db.profile.units} · Height: {db.profile.height||'Not recorded'}</p><button className="btn btn-hot" onClick={()=>app.setPage('Settings')}>Edit profile in Settings</button></section>;
  else content=null;
  return <div className="bio-page stack">{!bio.ready&&<p role="status">Opening local biological records…</p>}{error&&<p role="alert" className="bio-error">{error}</p>}{content}<AnalysisJobs/>{editor&&<BioEditor key={`${editor.kind}-${editor.initial?.id||'new'}`} {...editor} onClose={()=>setEditor(null)}/>}<Modal open={Boolean(confirmDelete)} title="Delete this record?" onClose={()=>setConfirmDelete(null)}><p>The deletion is saved in your local record history. Export a backup first if you need a copy.</p><button className="btn btn-hot" onClick={()=>void run(async()=>{await bio.remove(confirmDelete!);setConfirmDelete(null);})}>Delete record</button></Modal></div>;
}
