import { useEffect, useMemo, useState } from 'react';
import { useApp } from '../state/AppContext';
import { summarizeHealth, healthReadingSchema } from '../../shared/health';
import { today } from '../lib/utils';
import { cloudFetch } from '../lib/cloud-api';

export function Health(){
  const app=useApp();const [date,setDate]=useState(today),[source,setSource]=useState(''),[reports,setReports]=useState<any[]>([]),[error,setError]=useState('');
  const readings=useMemo(()=>(app.db?.healthReadings||[]).filter(r=>healthReadingSchema.safeParse(r).success),[app.db]);
  const sources=[...new Set(readings.map(r=>r.source))];const selected=source?readings.filter(r=>r.source===source):readings;
  const summaries=summarizeHealth(selected,date);const recent=selected.filter(r=>r.date===date).sort((a,b)=>b.startTime.localeCompare(a.startTime));
  useEffect(()=>{void cloudFetch('/api/medical-reports').then(async r=>{if(!r.ok)throw new Error('Could not read medical report records.');setReports((await r.json()).reports||[]);}).catch(e=>setError(e.message));},[app.db]);
  return <div className="page-shell fade"><header className="page-hero"><div><span className="page-eyebrow">CONNECTED HEALTH DATA</span><h1 className="page-title">Health</h1><p className="page-sub">Readings synced from your devices and account, with each source kept visible.</p></div><button className="btn btn-soft" onClick={()=>void app.refresh()}>Refresh cloud data</button></header>
    <section className="page-panel stack" style={{padding:24}}><div className="row" style={{flexWrap:'wrap'}}><label className="stack">Date<input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="stack">Source<select className="input" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources · shown separately</option>{sources.map(s=><option key={s}>{s}</option>)}</select></label><span className="subtle">{readings.length.toLocaleString()} synced readings</span></div><p className="subtle">Overlapping readings are flagged and are not added together. Sleep is shown on its saved date. Previously imported readings remain available.</p></section>
    {summaries.length===0?<section className="page-panel" style={{padding:24}}><h3>No readings for this date</h3><p className="subtle">Choose another date or import health readings. Workout logging and Care do not require a connected health device.</p></section>:<div className="grid-2">{summaries.map(s=><section className="page-panel" key={`${s.kind}:${s.source}`} style={{padding:24}}><span className="page-eyebrow">{s.kind.replace(/([a-z])([A-Z])/g,'$1 $2')}</span><h2>{s.value===null?'Review overlaps':Math.round(s.value*100)/100} {s.value!==null?s.unit:''}</h2><p>{s.source}</p><p className="subtle">{s.count} reading(s) · last imported {new Date(s.importedAt).toLocaleString()}</p>{s.overlap&&<p role="status">Intervals overlap within this source. Inspect the readings below.</p>}</section>)}</div>}
    <section className="page-panel stack" style={{padding:24}}><h3>Readings on {date}</h3>{recent.slice(0,100).map(r=><div className="page-list-item" key={r.id}><div><strong>{r.kind} · {r.value} {r.unit}</strong><p className="subtle">{r.sourceDisplayName||r.source} · {new Date(r.startTime).toLocaleTimeString()}–{new Date(r.endTime).toLocaleTimeString()}</p></div></div>)}{recent.length>100&&<p className="subtle">Showing the newest 100 of {recent.length} readings. The full set is included in your cloud export.</p>}</section>
    <section className="page-panel stack" style={{padding:24}}><h3>Medical report records</h3><p className="subtle">Saved records are preserved with their original metadata. They are not interpreted here.</p>{error&&<p role="alert">{error}</p>}{!reports.length&&!error&&<p className="subtle">No medical report records are saved.</p>}{reports.map(r=><div className="page-list-item" key={r.id}><strong>{r.title||r.name||r.fileName||'Medical report'}</strong><span className="subtle">{r.date||r.createdAt?.slice(0,10)||''}</span></div>)}</section>
  </div>;
}
