import { CachedReports } from '../components/AutomaticReview';
import { MedicalIntelligence } from '../components/MedicalIntelligence';
import { useState } from 'react';
import { useBiologicalData } from '../lib/use-biological-data';
import { dateOf } from '../../shared/biology';
import { shiftDay, summarizeRange } from '../../shared/biological-intelligence';
import { SignalChart } from '../components/SignalChart';
import { csvCell, downloadArtifact, escapeHtml } from '../lib/health-os-export';

const fmt=(v:number|null|undefined,d=1)=>v==null?'—':v.toLocaleString(undefined,{maximumFractionDigits:d});
export function HealthReportsWorkspace(){
  const {app,records}=useBiologicalData(),today=dateOf(new Date().toISOString()),[from,setFrom]=useState(shiftDay(today,-6)),[to,setTo]=useState(today);
  const valid=from<=to&&Date.parse(to)-Date.parse(from)<366*86400000,report=valid?summarizeRange(records,app.db!,app.skin,from,to):null;
  const stats=report?[{label:'Workouts',value:report.workouts},{label:'Average sleep',value:`${fmt(report.averageSleep)} h`},{label:'Average readiness',value:`${fmt(report.averageReadiness,0)} /100`},{label:'Average protein',value:`${fmt(report.averageProtein,0)} g`},{label:'Care adherence',value:`${fmt(report.careAdherence,0)}%`},{label:'Scheduled dose adherence',value:`${fmt(report.supplementAdherence,0)}%`}]:[];
  const exportCsv=()=>{if(!report)return;const keys=Object.keys(report.series[0]);downloadArtifact('health-os-report.csv',[keys.map(csvCell).join(','),...report.series.map(row=>keys.map(k=>csvCell(row[k as keyof typeof row])).join(','))].join('\r\n'),'text/csv');};
  const exportPrint=()=>{if(!report)return;downloadArtifact('health-os-report.html',`<!doctype html><html><meta charset="utf-8"><title>Health OS report</title><style>body{font:16px system-ui;max-width:800px;margin:60px auto;padding:24px;color:#352419}h1{color:#b94b12}table{width:100%;border-collapse:collapse}td,th{padding:15px;text-align:left;border-bottom:1px solid #eee}@media print{body{margin:0}}</style><h1>Health OS</h1><p>${escapeHtml(from)} – ${escapeHtml(to)}</p><table>${stats.map(s=>`<tr><th>${escapeHtml(s.label)}</th><td>${escapeHtml(s.value)}</td></tr>`).join('')}</table><p>Summaries use recorded observations. Missing days are excluded from averages. Estimates and source coverage affect interpretation.</p></html>`,'text/html');};
  return <div className="flow-workspace stack"><header className="bio-page-head"><p className="bio-eyebrow">INSIGHTS / HEALTH REPORTS</p><h1>Your health, across the days.</h1><p className="subtle">Bring the connected picture into one report. Choose the period you want to review.</p></header><MedicalIntelligence/><CachedReports/><section className="glass card stack"><div className="flow-choices">{[{label:'Today',days:1},{label:'This week',days:7},{label:'This month',days:30}].map(p=><button key={p.label} onClick={()=>{setFrom(shiftDay(today,1-p.days));setTo(today);}}>{p.label}</button>)}</div><div className="flow-field-grid"><label>From<input className="input" type="date" value={from} onChange={e=>e.target.value&&setFrom(e.target.value)}/></label><label>To<input className="input" type="date" value={to} onChange={e=>e.target.value&&setTo(e.target.value)}/></label></div>{!valid&&<p role="alert">Choose an ordered range of up to one year.</p>}<div className="row wrap"><button className="btn btn-hot" disabled={!report} onClick={()=>report&&downloadArtifact('health-os-report.json',JSON.stringify(report,null,2))}>Export JSON</button><button className="btn btn-soft" disabled={!report} onClick={exportCsv}>Export CSV</button><button className="btn btn-soft" disabled={!report} onClick={exportPrint}>Printable report</button></div></section>{report&&<><div className="overview-signals">{stats.map(s=><article className="glass card" key={s.label}><p className="bio-eyebrow">{s.label}</p><h2>{s.value}</h2></article>)}</div><section className="glass card stack"><SignalChart label="Readiness" unit="/100" points={report.series.map(s=>({date:s.date,value:s.Readiness}))}/><SignalChart label="Sleep" unit="h" points={report.series.map(s=>({date:s.date,value:s.Sleep}))}/><p className="subtle">{report.nutritionDays} days with nutrition logs · {report.completeNutritionDays} marked complete. Averages use recorded days and preserve gaps.</p></section></>}</div>;
}
