import { useMemo, useState } from 'react';
import { useBiologicalData } from '../lib/use-biological-data';
import { useTimelineActions } from '../lib/use-timeline-actions';
import { dateOf } from '../../shared/biology';
import { shiftDay, summarizeRange } from '../../shared/biological-intelligence';
import { downloadArtifact, escapeHtml, csvCell } from '../lib/health-os-export';
import { MedicalIntelligence } from '../components/MedicalIntelligence';
import { SignalChart } from '../components/SignalChart';

const kinds=['Daily','Weekly','Monthly','Training','Nutrition','Body','Medical','Doctor','Custom'] as const;
type Kind=typeof kinds[number];
export function ReportStudio() {
  const {app,bio,records,stored}=useBiologicalData(),actions=useTimelineActions(),today=dateOf(new Date().toISOString());
  const [kind,setKind]=useState<Kind>('Weekly'),[from,setFrom]=useState(shiftDay(today,-6)),[to,setTo]=useState(today),[saved,setSaved]=useState(false);
  const valid=!!from&&!!to&&from<=to&&to<=today&&(Date.parse(to)-Date.parse(from))/86400000<366;
  const report=useMemo(()=>valid?summarizeRange(records,app.db!,app.skin,from,to):null,[valid,records,app.db,app.skin,from,to]);
  const metrics=report?[{name:'Workouts',value:report.workouts,unit:'sessions',domain:'Training'},{name:'Sleep',value:report.averageSleep,unit:'h',domain:'Recovery'},{name:'Readiness',value:report.averageReadiness,unit:'/100',domain:'Recovery'},{name:'Calories',value:report.averageCalories,unit:'kcal',domain:'Nutrition'},{name:'Protein',value:report.averageProtein,unit:'g',domain:'Nutrition'},{name:'Latest recorded weight',value:report.series.filter(row=>row.Weight!==null).at(-1)?.Weight??null,unit:'kg',domain:'Body'},{name:'Observed weigh-ins',value:report.series.filter(row=>row.Weight!==null).length,unit:'days',domain:'Body'},{name:'Care completion',value:report.careAdherence,unit:'%',domain:'Care'}].filter(row=>!['Training','Nutrition','Body'].includes(kind)||row.domain===kind):[];
  const format=(value:number|null)=>value===null?'—':value.toLocaleString(undefined,{maximumFractionDigits:1});
  const exportSeries:Record<string,string|number|null>[]=report?report.series.map((row):Record<string,string|number|null>=>{if(kind==='Training')return {date:row.date,Volume:row.Volume,Strength:row.Strength};if(kind==='Nutrition')return {date:row.date,Calories:row.Calories,Protein:row.Protein,Carbohydrates:row.Carbohydrates};if(kind==='Body')return {date:row.date,Weight:row.Weight};return row;}):[];
  const seriesUnits:Record<string,string>={Sleep:'h',Readiness:'/100',Energy:'/10',Stress:'/10',Protein:'g',Calories:'kcal',Carbohydrates:'g',HRV:'ms','Resting HR':'bpm',Steps:'steps',Weight:'kg',Volume:`${app.db!.profile.units} × reps`,Strength:app.db!.profile.units,'Care severity':'/10',Humidity:'%'};
  const exportData=()=>({kind,from,to,...(!['Training','Nutrition','Body'].includes(kind)?report:kind==='Training'?{workouts:report?.workouts}:kind==='Nutrition'?{nutritionDays:report?.nutritionDays,completeNutritionDays:report?.completeNutritionDays}:{}),metrics,seriesUnits:Object.fromEntries(Object.keys(exportSeries[0]||{}).map(key=>[key,seriesUnits[key]||'ISO calendar date'])),series:exportSeries});
  const html=()=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Health OS ${escapeHtml(kind)} report</title><style>body{font:16px system-ui;color:#172018;max-width:900px;margin:40px auto;padding:24px}table{width:100%;border-collapse:collapse}td,th{padding:12px;text-align:left;border-bottom:1px solid #ccc}h1{letter-spacing:-1px}@media print{body{margin:0}}</style></head><body><h1>Health OS · ${escapeHtml(kind)} report</h1><p>${escapeHtml(from)}–${escapeHtml(to)}</p><table><thead><tr><th>Metric</th><th>Recorded value</th></tr></thead><tbody>${metrics.map(row=>`<tr><th>${escapeHtml(row.name)}</th><td>${escapeHtml(format(row.value))} ${escapeHtml(row.unit)}</td></tr>`).join('')}</tbody></table><p>${report?.nutritionDays??0} nutrition days observed. Missing observations are excluded from averages. Personal trends are not medical diagnoses.</p></body></html>`;
  const choose=(value:Kind)=>{setKind(value);setSaved(false);if(['Daily','Weekly','Monthly'].includes(value)){setFrom(shiftDay(today,1-({Daily:1,Weekly:7,Monthly:30}[value as 'Daily'|'Weekly'|'Monthly'])));setTo(today);}};
  const snapshots=stored.filter(row=>row.type==='journal'&&row.metadata.subtype==='reportSnapshot').sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,24);
  return <div className="flow-workspace stack"><header className="bio-page-head"><p className="bio-eyebrow">REPORTS</p><h1>Report Studio</h1><p className="subtle">Preview, save and export your recorded history.</p></header>
    <section className="glass card stack"><div className="flow-choices" aria-label="Report type">{kinds.map(value=><button key={value} aria-pressed={kind===value} className={kind===value?'active':''} onClick={()=>choose(value)}>{value}</button>)}</div>{!['Medical','Doctor'].includes(kind)&&<><div className="flow-field-grid"><label>From<input className="input" type="date" max={to} value={from} onChange={event=>{setFrom(event.target.value);setSaved(false);}}/></label><label>To<input className="input" type="date" min={from} max={today} value={to} onChange={event=>{setTo(event.target.value);setSaved(false);}}/></label></div>{!valid&&<p role="alert">Choose an ordered range of up to one year ending today or earlier.</p>}</>}{['Medical','Doctor'].includes(kind)&&<p className="subtle">Select the clinical records and report window in the medical workspace below.</p>}
      {!['Medical','Doctor'].includes(kind)&&<div className="row wrap"><button className="btn btn-hot" disabled={!report||!!actions.busy||saved} onClick={()=>void actions.run('report-snapshot',async()=>{await bio.save({type:'journal',domain:'Insights',name:`${kind} report · ${from}–${to}`,source:'Health OS Report Studio',metadata:{subtype:'reportSnapshot',from,to,reportType:kind,summary:JSON.stringify({metrics,nutritionDays:report!.nutritionDays,completeNutritionDays:report!.completeNutritionDays,weight:kind==='Body'?report!.series.map(row=>({date:row.date,value:row.Weight})):undefined})}});setSaved(true);})}>{saved?'Snapshot saved':'Save snapshot'}</button><button className="btn btn-soft" disabled={!report} onClick={()=>downloadArtifact(`health-os-${kind.toLowerCase()}-report.json`,JSON.stringify(exportData(),null,2))}>Export JSON</button><button className="btn btn-soft" disabled={!report} onClick={()=>{if(!report)return;const keys=Object.keys(exportSeries[0]);downloadArtifact('health-os-report.csv',[keys.map(key=>csvCell(seriesUnits[key]?`${key} (${seriesUnits[key]})`:key)).join(','),...exportSeries.map(row=>keys.map(key=>csvCell(row[key])).join(','))].join('\r\n'),'text/csv');}}>Export CSV</button><button className="btn btn-soft" disabled={!report} onClick={()=>downloadArtifact('health-os-report.html',html(),'text/html')}>Printable report</button></div>}
      <div className="row wrap"><button className="btn btn-soft" onClick={()=>app.setPage('Settings','Reports')}>Email & schedules</button><button className="btn btn-soft" onClick={()=>app.setPage('Reports','Workout Reports')}>Saved workout reports & email</button></div>
    </section>
    {['Medical','Doctor'].includes(kind)?<MedicalIntelligence/>:report&&<section className="stack" aria-label="Report preview"><div className="web-evidence-grid">{metrics.map(row=><article className="health-panel" key={row.name}><h2>{row.name}</h2><strong className="web-baseline-number">{format(row.value)} <small>{row.unit}</small></strong></article>)}</div><section className="glass card"><SignalChart label={kind==='Body'?'Weight':kind==='Nutrition'?'Protein':kind==='Training'?'Training volume':'Readiness'} unit={kind==='Body'?'kg':kind==='Nutrition'?'g':kind==='Training'?`${app.db!.profile.units} × reps`:'/100'} points={report.series.map(row=>({date:row.date,value:row[kind==='Body'?'Weight':kind==='Nutrition'?'Protein':kind==='Training'?'Volume':'Readiness']}))}/><p className="subtle">{from}–{to} · {report.nutritionDays} days with nutrition logs, {report.completeNutritionDays} marked complete. Averages exclude missing observations.</p></section></section>}
    {actions.error&&<p role="alert">{actions.error}</p>}
    <details className="glass card"><summary>Saved snapshots · {snapshots.length}</summary>{snapshots.map(row=><article key={row.id}><h3>{row.name}</h3><p className="subtle">Saved {new Date(row.timestamp).toLocaleString()} · {row.source}</p><pre className="bio-json">{String(row.metadata.summary||'')}</pre><button className="btn btn-soft" onClick={()=>downloadArtifact('health-os-snapshot.json',JSON.stringify(row,null,2))}>Export snapshot</button></article>)}</details>
  </div>;
}
