import { AppointmentAgenda } from '../components/AppointmentAgenda';
import { MiniSparkline } from '../components/VisualMetrics';
import { SignalChart } from '../components/SignalChart';
import { DomainHero } from '../components/DomainHero';
import { MedicalActionCenter } from '../components/MedicalActionCenter';
import { OSIcon } from '../components/OSIcon';
import { useBiologicalData } from '../lib/use-biological-data';
import { useQuickLog } from '../components/QuickLog';
import type { Page } from '../lib/types';
import type { Section } from '../lib/os-navigation';
import { baseline, dateOf, preferredVitals } from '../../shared/biology';
import { anomalySignals, correlations, daySeries, weightTrend } from '../../shared/biological-intelligence';

const fmt=(v:number|null|undefined,d=0)=>v==null?'—':v.toLocaleString(undefined,{maximumFractionDigits:d});
export function SectionOverview({section,choose}:{section:'Health'|'Body'|'Insights';choose:(page:Page,panel?:string)=>void}){
  const {app,records}=useBiologicalData(),quick=useQuickLog(),date=dateOf(new Date().toISOString()),db=app.db!;
  const weight=weightTrend(records,date),sources=new Set(records.map(r=>r.source)),anomalies=anomalySignals(records,date),series=daySeries(records,db,app.skin,date,28),associations=correlations(records,db,app.skin,date,28);
  const available=associations.filter(c=>c.r!==null);
  const vitalMetrics=[{name:'Resting HR',unit:'bpm',panel:'Heart'},{name:'HRV',unit:'ms',panel:'Heart'},{name:'Steps',unit:'steps',panel:'Activity'},{name:'Oxygen',unit:'%',panel:'Oxygen'}];
  const readings=records.filter(r=>r.type==='vital'),observedDays=new Set(series.filter(s=>Object.entries(s).some(([k,v])=>k!=='date'&&v!==null)).map(s=>s.date)).size;
  const tiles:{title:string;detail:string;page:Page;panel:string;icon:Section}[]=section==='Health'?[{title:'Your vital signs',detail:'Heart, activity and your other recorded readings.',page:'Health' as Page,panel:'Manual Readings',icon:'Health'},{title:'Medication & supplements',detail:'Your saved schedule and dose history.',page:'Health' as Page,panel:'Medications',icon:'Recover'},{title:'Symptoms & observations',detail:'Keep the context behind your health signals.',page:'Health' as Page,panel:'Symptoms',icon:'Care'},{title:'Connected sources',detail:'Review imports, source priority and data quality.',page:'Health' as Page,panel:'Connected Sources',icon:'Sync'}]:section==='Body'?[{title:'Weight',detail:'Your readings and longer-term direction.',page:'Body' as Page,panel:'Weight',icon:'Body'},{title:'Measurements',detail:'Record circumference and composition together.',page:'Body' as Page,panel:'Measurements',icon:'Care'},{title:'Body composition',detail:'See the composition readings you’ve recorded.',page:'Body' as Page,panel:'Body Composition',icon:'Insights'},{title:'Measurement history',detail:'Review, edit or remove previous measurements.',page:'Body' as Page,panel:'Measurement History',icon:'Today'}]:[{title:'Trends',detail:'Explore your recorded signals across time.',page:'Insights' as Page,panel:'Trends',icon:'Insights'},{title:'Correlations',detail:'Explore paired observations across your domains.',page:'Insights' as Page,panel:'Correlations',icon:'Health'},{title:'Personal baselines',detail:'Compare recent signals with your own history.',page:'Insights' as Page,panel:'Personal Baselines',icon:'Body'},{title:'Experiments',detail:'Choose a question and track one change.',page:'Experiments' as Page,panel:'',icon:'Train'}];
  return <div className="flow-workspace stack">
    <DomainHero section={section} kicker={section==='Health'?'YOUR SIGNALS, YOUR CONTEXT':section==='Body'?'PROGRESS AT YOUR OWN PACE':'THE BIGGER PICTURE'} title={section==='Health'?'A clearer picture of you.':section==='Body'?'Small changes. A fuller picture.':'Find the rhythm behind your records.'} description={section==='Health'?'Bring your readings and daily observations together. Start with what matters today.':section==='Body'?'Follow your direction over time, with room for the natural ups and downs.':'Your training, food, recovery and health can tell a connected story as your history grows.'} primary={{label:section==='Insights'?'Explore your trends':'Log a reading',action:()=>section==='Insights'?choose('Insights','Trends'):quick.open('vital',undefined,undefined,section==='Body'?{metric:'Weight',unit:db.profile.units}:undefined)}} secondary={{label:section==='Health'?'Review sources':section==='Body'?'All measurements':'Training Analytics Lab',action:()=>choose(section==='Health'?'Health':section==='Body'?'Body':'Analyzer',section==='Health'?'Connected Sources':section==='Body'?'Measurement History':'')}} metric={{value:section==='Health'?readings.length:section==='Body'?fmt(weight.trend,1):observedDays,label:section==='Health'?'readings recorded':section==='Body'?'kg · 7-day trend':'days with records',note:section==='Body'?'Based on available preferred readings':'Built from your saved data',progress:null}} stats={section==='Health'?[{label:'Available sources',value:sources.size},{label:'Symptoms logged',value:records.filter(r=>r.type==='symptom').length},{label:'Recent signals',value:anomalies.length}]:section==='Body'?[{label:'Weigh-ins',value:weight.points.length},{label:'30-day change',value:weight.change30===null?'—':`${fmt(weight.change30,1)} kg`},{label:'Measurements',value:db.measurements.length}]:[{label:'Connected domains',value:new Set(records.map(r=>r.domain)).size},{label:'Pairs with evidence',value:available.length},{label:'Signals to review',value:anomalies.length}]}/>
    {section==='Health'&&<AppointmentAgenda/>}{section==='Health'&&<section className="overview-signals">{vitalMetrics.map(m=>{const r=preferredVitals(records,m.name).at(-1);return <button className="glass" key={m.name} onClick={()=>choose('Health',m.panel)}><span className="bio-eyebrow">{m.name}</span><MiniSparkline label={m.name} unit={m.unit} tone="var(--health)" points={preferredVitals(records,m.name).slice(-14).map(v=>({date:dateOf(v.timestamp),value:v.value}))}/><strong>{fmt(r?.value,m.name==='Oxygen'?1:0)}<small>{m.unit}</small></strong><span>{r?`${dateOf(r.timestamp)} · ${r.source}`:'Ready when you have a reading'}</span></button>;})}</section>}
    {section==='Body'&&<section className="glass card"><SignalChart label="Recorded weight" unit="kg" points={weight.points.slice(-28).map(p=>({date:p.date,value:p.weight}))}/></section>}
    {section==='Insights'&&<section className="glass card"><SignalChart label="Readiness" unit="/100" points={series.map(p=>({date:p.date,value:p.Readiness}))}/></section>}
    {section==='Health'&&<MedicalActionCenter view="overview"/>}
    <div className="flow-section-title"><h2>{section==='Insights'?'Choose a question':'Your next step'}</h2><span className="subtle">Everything has its own space</span></div>
    <div className="overview-destinations">{tiles.map(t=><button className="glass" key={t.title} onClick={()=>choose(t.page,t.panel)}><span className="overview-tile-icon"><OSIcon name={t.icon}/></span><span><strong>{t.title}</strong><small>{t.detail}</small></span><span aria-hidden="true">↗</span></button>)}</div>
    <section className="overview-note glass"><div><span className="bio-eyebrow">{section==='Body'?'KEEP THE PERSPECTIVE':'A LITTLE CONTEXT'}</span><h2>{section==='Body'?'One reading is just one moment.':section==='Health'?'Your history makes the picture clearer.':'Patterns need a little time.'}</h2><p>{section==='Body'?'Trends use your recorded measurements. Daily fluctuations can reflect many things; use the history to see your direction.':section==='Health'?`${readings.length} readings from ${sources.size} available sources. Source priority keeps overlapping daily vitals from being counted twice.`:`${available.length} paired patterns currently have enough observations for a correlation. Missing days remain missing; associations do not establish cause.`}</p></div><OSIcon name={section} size={64}/></section>
  </div>;
}
