import { ReleaseSettings } from '../components/ReleaseSettings';
import { UxDiagnostics } from '../components/UxDiagnostics';
import { Modal } from '../components/Modal';
import { post } from '../lib/api';
import { useDraftState } from '../lib/use-draft';
import { HomePersonalization } from '../components/HomePersonalization';
import { SaveStatus } from '../components/SaveStatus';
import { useEffect, useState } from 'react';
import { useApp } from '../state/AppContext';
import { useCloudAccount } from '../state/CloudAccountContext';
import { useToast } from '../components/Toast';
import { CloudConnections } from '../components/CloudConnections';
import { testExerciseMedia } from '../lib/exercise-references';

export function WebSettings({profileOnly=false,initialTab=''}:{profileOnly?:boolean;initialTab?:string}={}) {
  const app = useApp(), cloud = useCloudAccount(), toast = useToast();
  const [restore,setRestore]=useState<{backup:unknown;preview:{newRecords:number;unchanged:number;conflicts:number;total:number;differentOwner:boolean}}|null>(null);
  const [tab, setTab] = useState(initialTab==='Reports'?'Reports':'Profile');
  useEffect(()=>{if(initialTab==='Reports'&&!profileOnly)setTab('Reports');},[initialTab,profileOnly]);
  const [busy, setBusy] = useState(false);
  const [mediaTests, setMediaTests] = useState<Partial<Record<'youtube', { state: 'testing' | 'ok' | 'error'; message: string }>>>({});
  const settingsDraft = useDraftState<Record<string, any>>('settings:public',{ profileName: app.settings?.profileName || '', height: app.settings?.height || '', units: app.settings?.units || 'kg', weeklyGoal: app.settings?.weeklyGoal || 4, restSeconds: app.settings?.restSeconds || 90, aiProvider: app.settings?.aiProvider || 'openrouter', aiModel: app.settings?.aiModel || 'openrouter/free', aiApiKey: '', tavilyApiKey: '', braveSearchApiKey: '', weeklyReportEnabled: (app.settings as any)?.weeklyReportEnabled === true, monthlyReportEnabled: (app.settings as any)?.monthlyReportEnabled === true, reportSchedule: app.settings?.reportSchedule || 'Sunday 20:00', emailTimezone: 'Asia/Kolkata', workoutReportEnabled: (app.settings as any)?.workoutReportEnabled !== false }, ['aiApiKey','tavilyApiKey','braveSearchApiKey']);
  const form=settingsDraft.value,setForm=settingsDraft.setValue;
  const field = (key: string, label: string, type = 'text') => <label className="stack" key={key}><span>{label}</span><input className="input" type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} autoComplete={type === 'password' ? 'new-password' : undefined} /></label>;
  async function act(work: () => Promise<unknown>, message: string) {
    setBusy(true); try { await work(); toast.push(message, 'ok'); } catch (e) { toast.push((e as Error).message, 'err'); } finally { setBusy(false); }
  }
  async function save() { await app.api.saveSettings(form); await app.refresh(); setMediaTests({}); setForm(f => ({ ...f, aiApiKey: '', tavilyApiKey: '', braveSearchApiKey: '' })); await settingsDraft.clear().catch(()=>{}); }
  async function testMedia(provider: 'youtube') {
    setBusy(true);
    setMediaTests(previous => ({ ...previous, [provider]: { state: 'testing', message: 'Saving and testing…' } }));
    try {
      const message = await testExerciseMedia(provider);
      setMediaTests(previous => ({ ...previous, [provider]: { state: 'ok', message } }));
    } catch (error) {
      setMediaTests(previous => ({ ...previous, [provider]: { state: 'error', message: (error as Error).message } }));
    } finally { setBusy(false); }
  }
  function mediaConnection(provider: 'youtube', label: string) {
    const test = mediaTests[provider];
    return <section className="stack" aria-label={`${label} connection`}>
      <strong>{label}</strong>
      <p className="subtle">Provided by Health OS for all users. No API key required.</p>
      <button type="button" className="btn btn-soft" disabled={busy} onClick={() => void testMedia(provider)}>Test {label}</button>
      {test && <p className={test.state === 'ok' ? 'chip ready-ok' : 'subtle'} role={test.state === 'error' ? 'alert' : 'status'}>{test.message}</p>}
    </section>;
  }
  return <div className="page-shell fade"><SaveStatus status="idle" detail={settingsDraft.status}/><HomePersonalization/>
    <header className="page-hero"><div><span className="page-eyebrow">YOUR WORKSPACE</span><h1 className="page-title">{profileOnly ? 'Your profile' : 'Settings'}</h1><p className="page-sub">{profileOnly ? 'Make this workspace your own.' : 'Manage your preferences, reports and connected tools.'}</p></div><span className="chip ready-ok">Supabase cloud</span></header>
    <div className="row" role="tablist" aria-label="Settings sections" style={{ flexWrap: 'wrap', marginBottom: 24 }}>{(profileOnly ? ['Profile'] : ['Profile', 'Reports', 'Connections', 'Data & account']).map(t => <button type="button" key={t} role="tab" aria-selected={tab === t} className={`btn ${tab === t ? 'btn-hot' : 'btn-soft'}`} onClick={() => setTab(t)}>{t}</button>)}</div>
    <section className="page-panel stack" style={{ maxWidth: 760, padding: 24, gap: 20 }}>
      {tab === 'Profile' && <><label className="stack">Appearance<select className="input" value={app.appearance} onChange={event => app.setAppearance(event.target.value as 'light' | 'dark' | 'system')}><option value="light">Light</option><option value="dark">Dark</option><option value="system">Use device setting</option></select></label>{field('profileName', 'Your name')}<label className="stack">Weight units<select className="input" value={form.units} onChange={e => setForm({ ...form, units: e.target.value })}><option value="kg">Kilograms</option><option value="lb">Pounds</option></select></label>{field('height', 'Height (cm)', 'number')}{field('weeklyGoal', 'Weekly workout goal', 'number')}{field('restSeconds', 'Rest timer (seconds)', 'number')}<label className="row"><input type="checkbox" checked={app.db?.trainingConfig.preplannedWeekMode !== false} disabled={busy} onChange={e => void act(async () => { await app.api.saveTrainingConfig({ preplannedWeekMode: e.target.checked }); await app.refresh(); }, 'Training mode updated.')} />Use a planned training week</label><p className="subtle">Turn this off to choose exercises as you train. Use Planner for a structured week.</p></>}
      {tab === 'Reports' && <><h3 style={{ margin: 0 }}>Reports delivered to your inbox</h3><p>Reports go to your verified account email: <strong>{cloud.user?.email}</strong>.</p><p className="subtle">Your workout saves to Supabase first. Email delivery runs in the cloud and continues when you close the app. AI workout reports include your sets, readiness, volume, workout assessment and exercise feedback. Failed delivery gets two immediate retries, then stays queued for automatic retry.</p><label className="row"><input type="checkbox" checked={form.workoutReportEnabled} onChange={e => setForm({ ...form, workoutReportEnabled: e.target.checked })} />Email a report after each workout</label><label className="row"><input type="checkbox" checked={form.weeklyReportEnabled} onChange={e => setForm({ ...form, weeklyReportEnabled: e.target.checked })} />Email weekly summaries</label>{field('reportSchedule', 'Weekly schedule, for example Sunday 20:00')}<label className="row"><input type="checkbox" checked={form.monthlyReportEnabled} onChange={e => setForm({ ...form, monthlyReportEnabled: e.target.checked })} />Email the previous month on the first day at 20:00 India time</label><button type="button" className="btn btn-soft" disabled={busy} onClick={() => void act(() => app.api.sendDummyEmail(), 'Test email accepted for delivery. Check your inbox and spam folder.')}>Send test email</button><button type="button" className="btn btn-soft" onClick={() => app.setPage('Reports', 'Workout Reports')}>Open saved reports</button></>}
      {tab === 'Connections' && <><h3 style={{ margin: 0 }}>AI coaching</h3><label className="stack">Provider<select className="input" value={form.aiProvider} onChange={e => setForm({ ...form, aiProvider: e.target.value })}><option value="openrouter">OpenRouter</option><option value="nvidia">NVIDIA</option></select></label>{field('aiModel', 'Model ID')}{field('aiApiKey', app.settings?.hasAiApiKey ? 'API key saved · enter a key to replace it' : 'Provider API key', 'password')}<button type="button" className="btn btn-soft" disabled={busy} onClick={() => void act(async () => { await save(); const result = await app.api.testAi(); if (!result.ok) throw new Error(result.error || 'AI connection failed.'); }, 'AI connection verified.')}>Save & test AI</button><hr /><h3 style={{ margin: 0 }}>Web research</h3>{field('tavilyApiKey', 'Tavily search key (optional)', 'password')}{field('braveSearchApiKey', 'Brave Search key (optional)', 'password')}<p className="subtle">Tavily supports search and reading public product pages. Brave supports search. Research includes source links for your review.</p><h3 style={{ margin: 0 }}>Exercise guides</h3>{mediaConnection('youtube', 'YouTube guides')}<p className="subtle">Exercise guides load automatically and are saved in the community library for everyone.</p><CloudConnections /></>}
      {tab === 'Data & account' && <><ReleaseSettings/><hr/><UxDiagnostics/><h3 style={{ margin: 0 }}>Your data lives in Supabase</h3><p className="subtle">All workspaces read the same cloud records. Keep an export for your own archive.</p><button type="button" className="btn btn-soft" disabled={busy} onClick={() => void act(async () => { const data = await app.api.getBackup(); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `health-os-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }, 'Backup exported.')}>Export all records</button><label className="stack">Import a Health OS backup<input className="input" type="file" accept="application/json,.json" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) void act(async () => { const backup=JSON.parse(await file.text());const preview=await post<any>('/api/backup/preview',backup);setRestore({backup,preview}); }, 'Backup checked. Review the preview before importing.'); }} /></label><hr /><p>Signed in as <strong>{cloud.user?.email}</strong></p><button type="button" className="btn btn-soft" disabled={busy} onClick={() => void cloud.syncNow()}>Refresh cloud records</button><button type="button" className="btn btn-soft" disabled={busy} onClick={() => void cloud.signOut()}>Sign out</button></>}
      {tab !== 'Data & account' && <button type="button" className="btn btn-hot" disabled={busy||!settingsDraft.ready} onClick={() => void act(save, 'Settings saved to your cloud account.')}>{busy ? 'Working…' : 'Save settings'}</button>}
    </section><Modal open={!!restore} title="Review backup import" onClose={()=>setRestore(null)}>{restore&&<div className="stack"><p>{restore.preview.total} records checked: {restore.preview.newRecords} new, {restore.preview.unchanged} unchanged, {restore.preview.conflicts} conflicts.</p><p>New records are added. Current conflicting records are preserved. The import does not replace your account.</p>{restore.preview.differentOwner&&<p>This backup was exported from another account. Confirm that these records belong in your signed-in account.</p>}<button className="btn btn-hot" disabled={busy} onClick={()=>void act(async()=>{const result=await app.api.restoreBackup(restore.backup as Parameters<typeof app.api.restoreBackup>[0]) as any;await app.refresh();setRestore(null);if(result.conflicts)toast.push(`${result.conflicts} conflicting records were preserved.`,'info');},'Backup imported into your cloud account.')}>Confirm import</button><button className="btn btn-soft" disabled={busy} onClick={()=>setRestore(null)}>Cancel import</button></div>}</Modal>
  </div>;
}
