import { mkdirSync, writeFileSync } from 'node:fs';
import { bioForms } from '../src/client/lib/biology-forms.ts';
const quote = (text: string) => JSON.stringify(text).replaceAll('$', '\\$');
const fields = Object.entries(bioForms).map(([type, form]) => {
  const items = form.fields.map(field => `CaptureField(${quote(field.key)}, ${quote(field.label)}, ${field.kind === 'number' ? Number(field.min ?? 0).toFixed(1) : 'null'}, ${field.kind === 'number' ? Number(field.max ?? 100000).toFixed(1) : 'null'}, ${quote(field.kind || 'text')}, ${Boolean(field.required)}, listOf(${(field.options || []).map(quote).join(', ')}))`);
  return `        Capture(${quote(type)}, ${quote(form.domain)}, ${quote(form.title)}, ${quote(form.unit || '')}, listOf(${items.join(', ')}))`;
});
const path = 'apps/android-native/app/src/main/java/app/healthos/nativeapp';
mkdirSync(path, {recursive:true});
writeFileSync(`${path}/CanonicalCaptures.kt`, `// Generated by scripts/android-capture-contracts.mts from the existing web/domain form contract.\npackage app.healthos.nativeapp\n\nobject CanonicalCaptures {\n    val all = listOf(\n${fields.join(',\n')}\n    )\n}\n`);
console.log(`Generated ${fields.length} canonical native capture schemas.`);
