// Rebuild email-safe raster indicators without external image or font dependencies.
import fs from 'node:fs/promises';
import { chromium } from '@playwright/test';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { MoonStar,Activity,Zap,Flower2,Flame,Smile,Droplets,Leaf,Stars,Footprints,HeartPulse,TriangleAlert,Sparkles,Brain,Lightbulb,CircleCheck,CircleSlash,Clock3,ListChecks,Dumbbell } from 'lucide-react';
import { REPORT_EMAIL_ASSETS } from '../src/shared/report-email-assets.js';
const assets={...REPORT_EMAIL_ASSETS};
const definitions={sleep:[MoonStar,'#7456b8','#f2edf8'],soreness:[Activity,'#b94d72','#f9edf1'],energy:[Zap,'#946329','#f5efe2'],stress:[Flower2,'#7456b8','#f2edf8'],motivation:[Flame,'#c65d21','#fcf0e7'],mood:[Smile,'#b94d72','#f9edf1'],hydration:[Droplets,'#2675bb','#ecf3fa'],protein:[Leaf,'#24834b','#ecf6ef'],quality:[Stars,'#7456b8','#f2edf8'],steps:[Footprints,'#24834b','#ecf6ef'],heart:[HeartPulse,'#b94d72','#f9edf1'],pain:[TriangleAlert,'#ba3038','#faeeee'],readiness:[Sparkles,'#2675bb','#ecf3fa'],analysis:[Brain,'#7456b8','#f2edf8'],coach:[Lightbulb,'#7456b8','#f2edf8'],completed:[CircleCheck,'#24834b','#ecf6ef'],skipped:[CircleSlash,'#686863','#eeece7'],duration:[Clock3,'#2675bb','#ecf3fa'],routine:[ListChecks,'#806b40','#f4eee1'],reps:[Dumbbell,'#c65d21','#fcf0e7']};
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:192,height:192}});
 const render=async(svg)=>{await page.setContent(`<style>html,body{margin:0;background:transparent}svg{display:block;width:192px;height:192px}</style>${svg}`);return (await page.screenshot({omitBackground:true})).toString('base64');};
 for(const [name,[Icon,color,bg]] of Object.entries(definitions)) {
  const icon=renderToStaticMarkup(React.createElement(Icon,{size:24,stroke:color,strokeWidth:1.8}));
  assets[name]=await render(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><rect width="36" height="36" rx="11" fill="${bg}"/><g transform="translate(6 6)">${icon}</g></svg>`);
 }
 for(let score=0;score<=100;score++) {
  const color=score>=60?'#2675bb':score>=40?'#946329':'#ba3038';
  const label=score>=80?'READY':score>=60?'CONTROLLED':score>=40?'REDUCED':'RECOVERY';
  assets['score'+score]=await render(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192"><circle cx="96" cy="96" r="78" fill="#fff" stroke="#e3e0d9" stroke-width="10"/><circle cx="96" cy="96" r="78" fill="none" stroke="${color}" stroke-width="10" stroke-linecap="round" stroke-dasharray="${score*4.9009} 490.09" transform="rotate(-90 96 96)"/><text x="96" y="99" text-anchor="middle" font-family="Arial,sans-serif" font-size="52" font-weight="700" fill="#202124">${score}</text><text x="96" y="124" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" font-weight="700" fill="${color}">${label}</text></svg>`);
 }
 await fs.writeFile('src/shared/report-email-assets.js','// Generated by scripts/generate-report-indicators.mts. Brand is preserved from the current Health OS assets.\nexport const REPORT_EMAIL_ASSETS = '+JSON.stringify(assets)+';\n');
 console.log('Generated '+Object.keys(assets).length+' inline report assets.');
} finally {await browser.close();}
