import crypto from 'node:crypto';
import { Router } from 'express';
import { z } from 'zod';
import { bioSchema, dateOf } from '../../shared/biology.js';
import { evidenceRefSchema, followupInputSchema, matchingRepeatResults, medicalTimeline, rankedMedicalInbox, researchFields, prospectiveResearchRows } from '../../shared/medical-actions.js';
import { changeMedicalActions, readMedicalActions, reconcileLocalMedical } from '../services/medical-actions.js';
import { listMedicalReports, medicalAudit } from '../services/medical-store.js';
import { publishSourceEvent } from '../services/automation-store.js';
import { automationDataset } from '../services/automation-runtime.js';

export const medicalActionsRouter=Router();
const snapshotInput=z.object({records:z.array(bioSchema).max(10000).optional()});
function recordsFrom(input:z.infer<typeof snapshotInput>){return input.records||automationDataset().records;}
function validateRefs(refs:z.infer<typeof evidenceRefSchema>[],suppliedRecords?:z.infer<typeof bioSchema>[]){const reports=listMedicalReports(),state=readMedicalActions(),records=suppliedRecords||automationDataset().records;for(const ref of refs){if(ref.kind==='report'&&!reports.some(r=>r.id===ref.id&&r.status==='reviewed'&&(!ref.resultId||r.results.some(v=>v.id===ref.resultId))))throw new Error('Evidence report or result is no longer available');if(ref.kind==='followup'&&!state.followups.some(f=>f.id===ref.id))throw new Error('Follow-up evidence unavailable');if(ref.kind==='checkin'&&!state.checkins.some(c=>c.id===ref.id))throw new Error('Check-in evidence unavailable');if(ref.kind==='record'&&!records.some(r=>r.id===ref.id&&!r.deletedAt))throw new Error('Record evidence unavailable');}}
medicalActionsRouter.post('/snapshot',(req,res)=>{const input=snapshotInput.parse(req.body);const records=recordsFrom(input),state=reconcileLocalMedical(records);res.json({state,inbox:rankedMedicalInbox(state),timeline:medicalTimeline(listMedicalReports(),records,state)});});
medicalActionsRouter.post('/rebuild',(req,res)=>{const input=snapshotInput.parse(req.body);res.json({state:reconcileLocalMedical(recordsFrom(input),undefined,true)});});
medicalActionsRouter.get('/audit',(_req,res)=>{const rows=getDbAudit();res.json({entries:rows});});
medicalActionsRouter.put('/inbox/:id',(req,res)=>{
  const input=z.object({status:z.enum(['reviewed','completed','dismissed','snoozed']),snoozedUntil:z.string().datetime({offset:true}).optional()}).parse(req.body);
  if(input.status==='snoozed'&&(!input.snoozedUntil||input.snoozedUntil<=new Date().toISOString()))return res.status(400).json({error:'Choose a future snooze time'});
  const item=changeMedicalActions(state=>{const item=state.inbox.find(i=>i.id===req.params.id);if(!item||item.status==='expired')return null;Object.assign(item,input,{resolvedAt:input.status==='snoozed'?undefined:new Date().toISOString()});return item;});
  if(!item)return res.status(404).json({error:'Inbox item unavailable'});medicalAudit(`inbox-${input.status}`,item.id);publishSourceEvent('medical.inbox_item.resolved',item.id,dateOf(new Date().toISOString()),input);res.json({item});
});
medicalActionsRouter.post('/followups',(req,res)=>{const input=followupInputSchema.extend({provenance:z.enum(['user','doctor_instruction','report']).default('user'),records:z.array(bioSchema).max(10000).optional()}).parse(req.body);validateRefs(input.sourceRefs,input.records);if(input.provenance!=='user'&&!input.notes.trim())return res.status(400).json({error:'Record the instruction and its source'});if(input.provenance==='report'&&!input.sourceRefs.some(ref=>ref.kind==='report'&&listMedicalReports().some(r=>r.id===ref.id&&r.status==='reviewed'&&r.narrative.includes(input.notes))))return res.status(400).json({error:'Quote the explicit instruction from a linked reviewed report narrative'});const followup=changeMedicalActions(state=>{const {records:sourceRecords,...fields}=input;const f={...fields,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'pending' as const,provenance:input.provenance};state.followups.push(f);return f;});medicalAudit('followup-created',followup.id);publishSourceEvent('medical.followup.created',followup.id,dateOf(followup.createdAt),followup);res.status(201).json({followup});});
medicalActionsRouter.put('/followups/:id',(req,res)=>{
  const input=z.object({status:z.enum(['pending','scheduled','completed','snoozed','cancelled']),dueAt:z.string().datetime({offset:true}).optional(),snoozedUntil:z.string().datetime({offset:true}).optional(),completionSourceRefs:z.array(evidenceRefSchema).max(10).default([]),confirm:z.literal(true)}).parse(req.body);
  if(input.status==='snoozed'&&(!input.snoozedUntil||input.snoozedUntil<=new Date().toISOString()))return res.status(400).json({error:'Choose a future snooze time'});
  validateRefs(input.completionSourceRefs);
  const followup=changeMedicalActions(state=>{const f=state.followups.find(f=>f.id===req.params.id);if(!f)return null;const candidates=matchingRepeatResults(f,listMedicalReports());if(input.completionSourceRefs.some(ref=>!candidates.some(c=>c.id===ref.id&&c.resultId===ref.resultId)))throw new Error('Completion must use a comparable reviewed repeat result');Object.assign(f,input,{completedAt:input.status==='completed'?new Date().toISOString():undefined,snoozedUntil:input.status==='snoozed'?input.snoozedUntil:undefined});return f;});
  if(!followup)return res.status(404).json({error:'Follow-up unavailable'});medicalAudit(`followup-${input.status}`,followup.id);publishSourceEvent(`medical.followup.${input.status}`,followup.id,dateOf(new Date().toISOString()),input);res.json({followup});
});
medicalActionsRouter.post('/questions',(req,res)=>{const input=z.object({text:z.string().trim().min(1).max(2000),source:z.enum(['user','template']).default('user'),sourceRefs:z.array(evidenceRefSchema).max(300).default([]),records:z.array(bioSchema).max(10000).optional()}).parse(req.body);validateRefs(input.sourceRefs,input.records);const question=changeMedicalActions(state=>{const {records:sourceRecords,...fields}=input;const q={...fields,id:crypto.randomUUID(),createdAt:new Date().toISOString(),answered:false};state.questions.push(q);return q;});medicalAudit('doctor-question-created',question.id);res.status(201).json({question});});
medicalActionsRouter.put('/questions/:id',(req,res)=>{const input=z.object({text:z.string().trim().min(1).max(2000),answered:z.boolean()}).parse(req.body);const question=changeMedicalActions(state=>{const q=state.questions.find(q=>q.id===req.params.id);if(q)Object.assign(q,input);return q;});res.status(question?200:404).json({question});});
medicalActionsRouter.post('/enrollment',(req,res)=>{const input=z.object({consent:z.literal(true),purpose:z.string().trim().min(3).max(500)}).parse(req.body);const enrollment=changeMedicalActions(state=>{if(state.enrollment?.active)return state.enrollment;state.enrollment={active:true,participantId:state.enrollment?.participantId||crypto.randomUUID(),consentedAt:new Date().toISOString(),purpose:input.purpose,fields:researchFields,version:1};return state.enrollment;});medicalAudit('research-consent-granted','local-user');publishSourceEvent('research.consent.changed','local-user',dateOf(new Date().toISOString()),{active:true});res.json({enrollment});});
medicalActionsRouter.delete('/enrollment',(req,res)=>{const input=z.object({deleteData:z.boolean()}).parse(req.body);changeMedicalActions(state=>{if(input.deleteData){state.enrollment=null;state.checkins=[];state.outcomes=[];}else if(state.enrollment){state.enrollment.active=false;state.enrollment.endedAt=new Date().toISOString();}for(const i of state.inbox.filter(i=>i.type==='research_feeling_check'))i.status='expired';});medicalAudit(input.deleteData?'research-enrollment-deleted':'research-consent-withdrawn','local-user');publishSourceEvent('research.consent.changed','local-user',dateOf(new Date().toISOString()),input);res.json({ok:true});});
medicalActionsRouter.post('/checkins',(req,res)=>{if(!readMedicalActions().enrollment?.active)return res.status(409).json({error:'Explicit study enrollment is required'});const input=z.object({feeling:z.enum(['Normal','Tired','Unwell']),noIllnessConfirmed:z.boolean().default(false),inboxId:z.string().optional()}).parse(req.body);if(input.noIllnessConfirmed&&input.feeling==='Unwell')return res.status(400).json({error:'Unwell cannot confirm an illness-free day'});const checkin=changeMedicalActions(state=>{if(!state.enrollment?.active)throw new Error('Explicit study enrollment is required');const now=new Date().toISOString(),date=dateOf(now);const item=state.inbox.find(i=>i.id===input.inboxId&&i.type==='research_feeling_check'&&i.status!=='expired');const existing=state.checkins.find(c=>c.date===date);const c={id:existing?.id||crypto.randomUUID(),at:now,date,feeling:input.feeling,noIllnessConfirmed:input.noIllnessConfirmed,source:'user' as const,sourceRefs:item?.sourceRefs||[]};if(existing)Object.assign(existing,c);else state.checkins.push(c);if(item){item.status='completed';item.resolvedAt=now;}return c;});medicalAudit('research-checkin-confirmed',checkin.id);publishSourceEvent('research.feeling_checkin.completed',checkin.id,checkin.date,checkin);res.json({checkin,symptomDraftAvailable:input.feeling==='Unwell'});});
medicalActionsRouter.post('/outcomes',(req,res)=>{if(!readMedicalActions().enrollment?.active)return res.status(409).json({error:'Active study consent is required'});const input=snapshotInput.extend({recordId:z.string().min(1).max(150),confirm:z.literal(true)}).parse(req.body);const record=recordsFrom(input).find(r=>r.id===input.recordId&&r.type==='illness'&&!r.deletedAt);if(!record)return res.status(404).json({error:'Illness source record unavailable'});const onset=String(record.metadata.start||dateOf(record.timestamp));if(onset>dateOf(new Date().toISOString()))return res.status(400).json({error:'Confirm an observed onset, not a future illness'});const outcome=changeMedicalActions(state=>{if(!state.enrollment?.active)throw new Error('Active study consent is required');state.outcomes||=[];const o={recordId:record.id,onset,recovery:record.metadata.end?String(record.metadata.end):undefined,confirmedAt:new Date().toISOString(),labelSource:'self_report' as const,labelQuality:'self-reported' as const};const old=state.outcomes.find(x=>x.recordId===record.id);if(old)Object.assign(old,o);else state.outcomes.push(o);return o;});medicalAudit('research-outcome-confirmed',record.id);publishSourceEvent('research.illness_outcome.confirmed',record.id,onset,outcome);res.json({outcome});});
medicalActionsRouter.post('/research-days',(req,res)=>{const input=snapshotInput.extend({consent:z.literal(true),from:z.string().date(),to:z.string().date()}).parse(req.body);const span=(Date.parse(input.to)-Date.parse(input.from))/86400000;if(span<0||span>366)return res.status(400).json({error:'Select an ordered range of at most 366 days'});const state=readMedicalActions();if(!state.enrollment)return res.status(409).json({error:'Research enrollment is required'});const dates=Array.from({length:span+1},(_,i)=>new Date(Date.parse(input.from)+i*86400000).toISOString().slice(0,10));const rows=prospectiveResearchRows(state,recordsFrom(input),dates);medicalAudit('prospective-research-export','local-user');res.json({schemaVersion:'prospective-1.0',generatedAt:new Date().toISOString(),outcomeDefinitions:{1:'Explicit self-reported acute illness onset from day d through d+1',3:'Explicit self-reported acute illness onset from day d through d+3',7:'Explicit self-reported acute illness onset from day d through d+7'},fields:researchFields,consent:{...state.enrollment,at:new Date().toISOString()},rows,limitations:'Research only; non-diagnostic. Prior-only features. Missing labels are null. Keep participants separate in evaluation. No external transmission. No free notes, report text, medication or identifying fields.'});});
import { getDb } from '../db/connection.js';
import { decryptSecret } from '../lib/secrets.js';
function getDbAudit(){listMedicalReports();return (getDb().prepare('SELECT at,data FROM medical_audit ORDER BY at DESC LIMIT 100').all() as {at:string;data:string}[]).map(r=>({at:r.at,...JSON.parse(decryptSecret(r.data))}));}
